### ISSUE TITLE
Question: Is possible to choose the day?

### ISSUE THREAD

**Issue by SerraLanao** [alamkanak/Android-Week-View#103]
Is there a way to jump into a date defined by the user?

**Comment by caske33** [comment]
mWeekView.goToDate(...)

**Comment by SerraLanao** [comment]
Oh, i haven't see that!
Thank u very much @caske33 !!

**Comment by chihao12** [comment]
hi there, im not able to jump to a particular date... 

This is how i do it: 

Calendar calendar = Calendar.getInstance();
calendar.set(Calendar.YEAR, 2015);
calendar.set(Calendar.MONTH, 4);
calendar.set(Calendar.DAY_OF_MONTH, 20);
calendar.set(Calendar.HOUR_OF_DAY, 10);
calendar.set(Calendar.MINUTE, 45);
calendar.set(Calendar.SECOND, 0);

 mWeekView.goToDate(calendar);

**Comment by alamkanak** [comment]
Use `mWeekView.goToDate();`
Closing issue.

**Comment by chihao12** [comment]
When i use it, the ui will hang and not move to the desired date. @alamkanak

**Comment by caske33** [comment]
@chihao12 @alamkanak I think that's because there was a bug with goToDate that is fixed by now, but not yet released to maven.
