### ISSUE TITLE
I can't use the scrollListener

### ISSUE THREAD

**Issue by josefrvaldes** [alamkanak/Android-Week-View#108]
- Hi! I'm trying to make it work and I can't see it. Android studio tells me that it doesn't exist.. 

Am I doing something wrong??

I can't do something like.. mWeekView.setScrollListener(new...)

thanks!

**Comment by caske33** [comment]
I think @alamkanak needs to release a new version to maven before you can use it.

**Comment by josefrvaldes** [comment]
Yes, but as I see that it appears in the repository main page, in the Interfaces field.. I thought that maybe it was already uploaded.
Thank you anyway caske33!

**Comment by alamkanak** [comment]
Fixed in the new v1.2.3
