### ISSUE TITLE
Weekly event and weekly scrolling

### ISSUE THREAD

**Issue by emanueleDiVizio** [alamkanak/Android-Week-View#11]
I couldn't get to create weekly event, probably because an onWeekChangeListener is not implemented. My suggestion is to implement a method to scroll from week to week (From monday to monday), an onWeekChangeListener to populate the weekView and a method to start the week from a preferred day, other than today. Thanks a lot

**Comment by AndroidDeveloperLB** [comment]
Any news about this feature? Was it added eventually?

If not, maybe this could be helpful for this feature:
https://stackoverflow.com/q/47514072/878126
?
EDIT: seems this library uses a single view that draws everything in a customized way. This won't help.

**Comment by CTKnight** [comment]
This is a feature in my app, I use a work around:

1. Modify the source of week view and disable horizontal swipping in the view(this part is not in my fork)

2. Place a weekview per fragment set it to display 7 days events, use a fragment page adapter to achieve smooth horizontal swipping.

**Comment by AndroidDeveloperLB** [comment]
@CTKnight This won't work well, because swiping between them will also swipe the hours, and in addition, the hours might be different between pages.
I've found this fork which does it well , without ViewPager : 
https://github.com/openium/Android-Week-View

But for some reason he didn't do a pull request. I've tested it and so far the only issue with it seems to be that he created a new class that extends WeekView instead of putting the new code in WeekView .

**Comment by CTKnight** [comment]
@AndroidDeveloperLB you are right, extra efforts can be made to align hours if you use view pager (that's the part I leave for my teammates XD). My solution also creates a new class. This can't painless, for weekview doesn't leave much space to customize though.

**Comment by AndroidDeveloperLB** [comment]
@CTKnight I don't like the implementation here of WeekView, but it's just the only decent library I've found.
Here all that's drawn in a flat view that handles all and has 2000+ lines, making it hard to modify and understand.

Google Calendar app, for example, does use ViewPager and in fact multiple views in it. I've found it in the DDMS tool. I wanted to do it myself, but it just takes too much time, so I was instructed to use what I can find.

The library here has many issues that I've found:

- https://github.com/alamkanak/Android-Week-View/issues/494 - can't find a solution. But I need to show just week for now, and it seems it doesn't occur as long as I don't switch them
- https://github.com/alamkanak/Android-Week-View/issues/495 - sample issue, might be in library too, but found a fix just for the formatting. Not for RTL locale though.
- https://github.com/alamkanak/Android-Week-View/issues/497 -  sample issue, might be in library too, but found a fix
- https://github.com/alamkanak/Android-Week-View/issues/498 - this actually doesn't occur on the fork of [here](https://github.com/Quivr/Android-Week-View) , but there I've noticed a new issue, [here](https://github.com/Quivr/Android-Week-View/issues/94), which actually doesn't exist on its fork [here](https://github.com/openium/Android-Week-View).
