### ISSUE TITLE
how to limit scrolling to one month ?

### ISSUE THREAD

**Issue by Hariharanswamy** [alamkanak/Android-Week-View#111]
i want to horizontal scrolling to one month.. how can i achieve this ?

**Comment by caske33** [comment]
duplicate of #6

**Comment by Hariharanswamy** [comment]
@caske33 it is to limit only one week... i want to limit for a month.. and it is dynamically.. sometimes more than a month

**Comment by caske33** [comment]
I meant #29 then. It's a known issue, but it doesn't have a solution currently.

**Comment by alamkanak** [comment]
Duplicate of #29
