### ISSUE TITLE
How to add new events when day is changed?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [alamkanak/Android-Week-View#112]
Hi!

I have implemented day change listener as:  `mWeekView.setScrollListener(this);` and now in callback:

@Override
	public void onFirstVisibleDayChanged(Calendar newFirstVisibleDay,
			Calendar oldFirstVisibleDay) {
}

i want to add new events to the WeekView but not sure how can i achieve this. 

Thanks. 

@caske33 @alamkanak

**Comment by caske33** [comment]
The scrollListener has nothing to do with it. For providing events you have to implement `WeekView.MonthChangeListener.onMonthChange()`, it's important that you don't ignore the parameters from that function, or your events will appear 3 times.

**Comment by alamkanak** [comment]
@caske33 is right
