### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by lolobosse** [alamkanak/Android-Week-View#115]
Hi there,

I checked my code many times to avoid submitting useless issues but I think there is really a bug there.

__STEPS TO REPRODUCE:__

* Set this MonthListener:

```java
        mWeekView.setMonthChangeListener(new WeekView.MonthChangeListener() {
            @Override
            public List<WeekViewEvent> onMonthChange(int year, int month) {

                List<WeekViewEvent> freshFromServerList = new ArrayList<>();

                Random r = new Random();
                WeekViewEvent event1 = new WeekViewEvent(1, 1+"", 2015, 4, 17, 0, 0, 2015, 4, 17, 23, 59);
                event1.setColor(Color.argb(175, r.nextInt(256), r.nextInt(256), r.nextInt(256)));

                WeekViewEvent event2 = new WeekViewEvent(2,  2+"", 2015, 4, 17, 1, 0, 2015, 4, 17, 3, 0);
                event2.setColor(Color.argb(175, r.nextInt(256), r.nextInt(256), r.nextInt(256)));

                WeekViewEvent event3 = new WeekViewEvent(3,  3+"", 2015, 4, 17, 1, 15, 2015, 4, 17, 2, 30);
                event3.setColor(Color.argb(175, r.nextInt(256), r.nextInt(256), r.nextInt(256)));

                WeekViewEvent event4 = new WeekViewEvent(4, 4+"", 2015, 4, 17, 2, 0, 2015, 4, 17, 3, 45);
                event4.setColor(Color.argb(175, r.nextInt(256), r.nextInt(256), r.nextInt(256)));

                WeekViewEvent event5 = new WeekViewEvent(5, 5+"", 2015, 4, 17, 3, 46, 2015, 4, 17, 5, 0);
                event5.setColor(Color.argb(175, r.nextInt(256), r.nextInt(256), r.nextInt(256)));

                WeekViewEvent event6 = new WeekViewEvent(6, 6+"", 2015, 4, 17, 4, 0, 2015, 4, 17, 4, 30);
                event6.setColor(Color.argb(175, r.nextInt(256), r.nextInt(256), r.nextInt(256)));

                WeekViewEvent event7 = new WeekViewEvent(7, 7+"", 2015, 4, 17, 3, 46, 2015, 4, 17, 5, 01);
                event7.setColor(Color.argb(175, r.nextInt(256), r.nextInt(256), r.nextInt(256)));

                freshFromServerList.add(event1);
                freshFromServerList.add(event2);
                freshFromServerList.add(event3);
                freshFromServerList.add(event4);
                freshFromServerList.add(event5);
                freshFromServerList.add(event6);
                freshFromServerList.add(event7);

                List<WeekViewEvent> listToReturn = filterList(freshFromServerList, year, month);
                return listToReturn;
            }

            private List<WeekViewEvent> filterList(List<WeekViewEvent> list, int year, int month) {
                ArrayList<WeekViewEvent> listToReturn = new ArrayList<>();
                for (WeekViewEvent wve : list){
                    if (wve.getStartTime().get(Calendar.MONTH)== month && wve.getStartTime().get(Calendar.YEAR)==year){
                        listToReturn.add(wve);
                    }
                }
                return listToReturn;
            }
        });
```

* Observe the view you get:

![screenshot_2015-04-17-16-05-40](https://cloud.githubusercontent.com/assets/5024077/7203650/5f831d86-e51c-11e4-9010-6e0e9db19ea2.png)

__EXPECTED BEHAVIOUR:__

* We should have a rectangle from `3:46` to `5:00` with name: `5`
* The same from `4:00` to `4:30` with name: `6`
* The same from `3:46` to `5:00` with name: `7`

__WHERE I ALREADY SEARCHED:__

* I have looked in the `WeekView` class to see if it gets all the data from the `MonthChangeListener`and it does
* I went through the collision methods and they seem to be ok (all the meetings are in collision due to the big first meeting).

__WHAT WOULD BE COOL:__

* It'd be very nice, if someone could have a look at it and could confirm if it is a bug or if I made a mistake (I'd prefer a mistake).
* If it's a bug, I'm ready to fix it and submit PR but I'm new to this library and, although, it's really well built, I could spend hours to find a trivial logical error and correct it. So, maybe @caske33 or @alamkanak ? :smile:

**Comment by caske33** [comment]
I'm really not sure why it doesn't show. i haven't yet looked at the collision code as it seemed to work just fine for me...

I've found a small bug in your code though: `wve.getStartTime().get(Calendar.MONTH)== month`, you have to keep in account that month is 1-based while java's Calendar MONTH is 0-based. So it should be `wve.getStartTime().get(Calendar.MONTH)+1==month`, this probably won't fix it, but just so you know.

**Comment by lolobosse** [comment]
Ok, I looked further in it: if you remove the big appointment it's working as usual. Thanks for the correction (but still not working :unamused: )! BTW, I'm just testing your library to include it in a much bigger project that's why I'm testing the edge cases. I'm currently debugging it but found nothing wrong; I keep you updated.

**Comment by caske33** [comment]
I've been using this library (or at least my fork) in production for about 1.5 months now. I haven't heard any complaints yet. (https://play.google.com/store/apps/details?id=be.kulapp.mobile).

And just a guess, but does it work when the events starts at 00:01AM instead of 00:00AM?

**Comment by lolobosse** [comment]
No, could have been a good idea but it doesn't change anything :unamused:

I'm at the debug, I know that it's between `compute` and `expand`. I'll try
to figure it out

2015-04-17 17:56 GMT+02:00 Jens Claes <notifications@github.com>:

**Comment by lolobosse** [comment]
I got it fixes. I'm on mobile I do a PR ASAP

**Comment by lolobosse** [comment]
So how is the review going? The error is quite trivial: instead of taking the first column to get the number of rows (which can be false because of the big appointment I created which takes the whole column and set the maxRow to 1), I set the maximum number of rows depending on the maximum contained in the most filled column --> It works. I would say it's a __critical bug__ :exclamation: :boom:

**Comment by caske33** [comment]
I haven't tested it out, but it looks right.

But in the end @alamkanak is the only core maintainer so he has to decide and he's quite busy...

**Comment by caske33** [comment]
@alamkanak can you take a look at this?

**Comment by antonkrasov** [comment]
@lolobosse thanks a lot a had exactly the same issues. App was live in Play Store with it for 2 months, before one clients reported the issues.
@alamkanak please merge this fix. It's very hard to debug and understand where is the issue. Agree that it's critical.

**Comment by lolobosse** [comment]
@antonkrasov Has been merged. Thanks @alamkanak ! :+1:
