### ISSUE TITLE
goToDate offset is wrong when working in "dayView"

### ISSUE THREAD

**Issue by adfleshner** [alamkanak/Android-Week-View#119]
When setVisibledays is 1 the offset barely moves. 
Currently I have a MonthView that I click on and it gives me a Calendar object that I pass to the next activity. Where the weekView is located(Currently set to 1 day showing set via xml "dayView" ). after that I call .goToDate function with that calendar value. If I go to today no offset works great. I Click on the next day on the monthview when i gets to the weekview it has only shifted over a little bit. if i click on 2 days  it shifts a little more. When I click on 39 to 40 days in the future I finally get to tomorrow. ( its not 100% ) so i currently have a multiplier but if I go a month into the future it starts to go to far. I can send video if needed.

**Comment by caske33** [comment]
This should be fixed if a new version of the library is published to maven.

**Comment by adfleshner** [comment]
I currently am using 1.2.1 is that the latest version?

**Comment by caske33** [comment]
It's the latest version published to maven. However, after that version code was committed that will fix this issue. @alamkanak still has to release this code to maven however.

**Comment by adfleshner** [comment]
I got ya. I will keep my little "workaround" until it is released . I will continue to watch this for a build number increase. Thank you.

**Comment by adamski8** [comment]
@caske33 That would be great, if you could release fixed version. Thanks.

**Comment by caske33** [comment]
@adamski8 Unfortunately, I don't have the authority to relase this to maven....

**Comment by adfleshner** [comment]
@caske33 is there a place online currently I am able to download the code and use the fixed version until it is uploaded to maven?

**Comment by caske33** [comment]
You can clone this project as a git submodule (under directory weekview for example) for your project and then add the `include :weekview:library` to your settings.gradle and a `compile project(':weekview:library')` to your build.gradle (instead of the other weekview compile line)

**Comment by alamkanak** [comment]
@caske33 @adfleshner New version released

**Comment by adfleshner** [comment]
@alamkanak Thank you!

**Comment by Nidhee** [comment]
@adfleshner As you said in your issue, You are using MonthView. Is MonthView  of this calendar view developed ? Or did you update library ? I want to am looking for MonthView with WeekView and DayView. Please guide, how get MonthView
.

**Comment by entropitor** [comment]
Month view doesn't exist yet: #2 
(although you can have a 31-day view).

**Comment by Nidhee** [comment]
@caske33 Can you guide how can I have 31-day view.

**Comment by entropitor** [comment]
set the number of days to 31 :) (see readme as well)
