### ISSUE TITLE
AsyncLoading of events

### ISSUE THREAD

**Issue by tyczj** [alamkanak/Android-Week-View#122]
Right now as I see it, it looks like events need to be loaded when `onMonthChange` is called which means there isnt a way to load events in a separate thread since events have to be returned in the onMonthChange callback is that correct?

**Comment by lolobosse** [comment]
I guess #57 is what you want.

**Comment by caske33** [comment]
This is implemented in my fork (under organization Quivr) but I need another PR's to be merged before I can acheive this. 

https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158 describes how you can acheive this already
