### ISSUE TITLE
Setting BackgroundColors Programatically Fails

### ISSUE THREAD

**Issue by HarveyAtwal** [alamkanak/Android-Week-View#123]
Hello, I am in the process of developing a calendar using user defined colors. However, the background colors are not updating and most likely stuck to default.

The following code will not change the header text color to black.
```
        mWeekView = (WeekView) mLayout.findViewById(R.id.weekView);
        mWeekView.setTodayHeaderTextColor(getResources().getColor(R.color.black));
```

**Comment by caske33** [comment]
I think this is fixed via #134
