### ISSUE TITLE
Does not show more than 2 events for same time or overlapping time?

### ISSUE THREAD

**Issue by akshaymanathkar** [alamkanak/Android-Week-View#124]
I have 4 event scheduled for 5/12/15 
1) from 9:00 am to 2:30 pm
2) from 10:00 am to 11:30 am
3) from 11:30 to 2:30 pm 
4) from 1:45 pm to 2:45 pm

It does not show me event '3)' event on my calendar

**Comment by lolobosse** [comment]
I know, it is a bug that I fixed but hasn't been merge, have a look at issue #115

**Comment by lolobosse** [comment]
It has been merged, you can close this issue
