### ISSUE TITLE
ScrollListener problem

### ISSUE THREAD

**Issue by raplider** [alamkanak/Android-Week-View#126]
ScrollListener does not work sometimes because of the fact that the column is not adjacent. There is a small gap. Sorry for my English.
![photo_2015-05-14_16-41-48](https://cloud.githubusercontent.com/assets/4466505/7632806/efc96b60-fa58-11e4-83e7-1f8d8e093a48.jpg)

**Comment by lolobosse** [comment]
Can you post your code, in order that we can able to reproduce it ? Thanks :+1: :smile:
