### ISSUE TITLE
Don't go to 'Today' when open the screen

### ISSUE THREAD

**Issue by diogo10** [alamkanak/Android-Week-View#127]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my_audit);

        //mWeekView.goToDate(Calendar.getInstance());// dont work
        //mWeekView.goToToday();//dont work
    }

I didnt find anything at Issues

**Comment by caske33** [comment]
Are you using the latest version of the library (v1.2.3)?

**Comment by diogo10** [comment]
Yes.....

compile 'com.github.alamkanak:android-week-view:1.2.3'

I try so many things =/

**Comment by caske33** [comment]
I'm not really sure what could be wrong here.

(btw the `//mWeekView.goToToday()` is uncommented in your code right? because with the `//` at the front of the line, it won't work)

**Comment by diogo10** [comment]
no no I uncommented my code...I put there only for you see that I tried with this code...

**Comment by caske33** [comment]
Now that I'm thinking about it, I don't really get the problem:
On which day is the dayview starting? (if it's not starting on today, because that's what those 2 methods will do)

(maybe to you mean to use `goToHour()`? As goToDate and goToToday only change the date, not the hour)

**Comment by diogo10** [comment]
@caske33  I put  mWeekView.goToHour(12); but didnt work too...Do you have this problem ?

**Comment by caske33** [comment]
no, normally that should work.

**Comment by diogo10** [comment]
My oncreate is..........


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my_audit);
        getSupportActionBar().setBackgroundDrawable(new      ColorDrawable(getResources().getColor(R.color.my_green)));

        mWeekView = (WeekView) findViewById(R.id.weekView);
        mWeekView.setOnEventClickListener(this);
        mWeekView.setMonthChangeListener(this);
        mWeekView.goToToday();
        new GetAuditWSAsyncTask(this).execute("http://localhost:8081/IenquireReportRESTFull/rest/jsonServices/audits");


    }

I really dont know what I am doing wrong...I tried put in onResume() but dont work too

**Comment by diogo10** [comment]
@caske33 I found one solution...no pretty but...work...

   @Override
    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
        
        //my code with the events      
 
       Calendar calendar = Calendar.getInstance();
        if(newMonth == (calendar.get(Calendar.MONTH)+1))
        mWeekView.goToToday();

        return events;

}


Thanks @caske33 anyway

**Comment by caske33** [comment]
I'm not really sure why you are calling goToToday(). Is the calendar not starting on the right day for you?

**Comment by diogo10** [comment]
yes, dont start on the current day.

**Comment by caske33** [comment]
On which day is it starting? And have you changed the number of visible days?

**Comment by diogo10** [comment]
started the week before the current week...I dont change the number of visible days....its really strange.

**Comment by subbuboyapati** [comment]
Hi, change this line of code https://github.com/alamkanak/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L403
to
```
int difference = (7 + (mToday.get(Calendar.DAY_OF_WEEK) - mFirstDayOfWeek)) % 7;
```
Now the code works perfectly.

**Comment by diogo10** [comment]
Great man =D Thanks very much
