### ISSUE TITLE
setHeaderColumnBackgroundColor problem

### ISSUE THREAD

**Issue by raplider** [alamkanak/Android-Week-View#128]
trying to change the color as follows: 
mWeekView = (WeekView) findViewById(R.id.weekView);
mWeekView.setHeaderColumnBackgroundColor(color);

but nothing happens
(v1.2.3)
---updated---
I looked at the source code and probably found problem. 
In setHeaderColumnBackgroundColor before calling "invalidate()" need add row 
 mHeaderColumnBackgroundPaint.setColor(mHeaderColumnBackgroundColor);

example:
public void setHeaderColumnBackgroundColor(int headerColumnBackgroundColor) {
        mHeaderColumnBackgroundColor = headerColumnBackgroundColor;
        mHeaderColumnBackgroundPaint.setColor(mHeaderColumnBackgroundColor);
        invalidate();
}

This must be done for all the similar functions which use Paint ();

**Comment by lolobosse** [comment]
Can you make a pull request from your code in order that we can check it ? Thanks :smile:

**Comment by raplider** [comment]
[Pull requests #134](https://github.com/alamkanak/Android-Week-View/pull/134)

**Comment by lolobosse** [comment]
Cool, then, we need to wait for @alamkanak to merge it.

**Comment by caske33** [comment]
Should be fixed in the next version.
