### ISSUE TITLE
How to add a new event by tapping on an empty view ?

### ISSUE THREAD

**Issue by rachitmishra** [alamkanak/Android-Week-View#13]
I think i will have to add empty events with a boolean flag, and on tapping them i can get it, if the event is empty, create new, else show details for previous events ??

**Comment by alamkanak** [comment]
Issue solved: #34.

```
mWeekView.setEmptyViewClickListener(new WeekView.EmptyViewClickListener() {
    @Override
    public void onEmptyViewClicked(Calendar time) {
        ...
    }
});
```

**Comment by rachitmishra** [comment]
@alamkanak Wao! Awesome man! due to my busy schedule i was not able to work with this!
I will love to contribute! Thanx!

**Comment by 3rand** [comment]
thank you

**Comment by tuanlamsts** [comment]
Hi guys,
How can I add new event by interface "onEmptyViewClicked" ?
In this interface I got time selected. how can I draw the event with it ?
This is my code:
newEvent = new WeekViewEvent(time.getTimeInMillis(), getEventTitle(time), time, time);
newEvent.setColor(getResources().getColor(android.R.color.holo_red_light));
//how to add event for drawing
mWeekView.invalidate();

**Comment by tuanlamsts** [comment]
Any guys can help ?

**Comment by 3rand** [comment]
Well normally you hold events in a list (List<WeekViewEvent>), so you created a new event (newEvent) and add it to that list now.
