### ISSUE TITLE
Set Calendar on WeekView - noOfVisibleDays="7"

### ISSUE THREAD

**Issue by Bruno-Piccinin-RealComm** [alamkanak/Android-Week-View#132]
Hi,

I have a problem when I start the app sample with noOfVisibleDays="7" in layout:

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MyActivity"
        android:background="#fff">
    
        <com.alamkanak.weekview.WeekView
            android:id="@+id/weekView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:eventTextColor="@android:color/white"
            app:textSize="12sp"
            app:hourHeight="60dp"
            app:headerColumnPadding="8dp"
            app:headerColumnTextColor="@color/toolbar_text"
            app:headerRowPadding="12dp"
            app:columnGap="8dp"
            app:noOfVisibleDays="7"
            app:headerRowBackgroundColor="@color/toolbar"
            app:dayBackgroundColor="#05000000"
            app:todayBackgroundColor="#1848adff"
            app:headerColumnBackground="#ffffffff"
            app:todayHeaderTextColor="@color/accent"/>
    
    </RelativeLayout>

but when the application start, the first day visible is not TODAY but it seems it is (TODAY - 11).

For example today(22/05/2015) I used the application and editing the layout with:
- noOfVisibleDays="2" sets first day visible of calendar on TODAY 22/05/2015
- noOfVisibleDays="3" sets first day visible of calendar on TODAY 22/05/2015
- noOfVisibleDays="4" sets first day visible of calendar on TODAY 22/05/2015
- noOfVisibleDays="5" sets first day visible of calendar on TODAY 22/05/2015
- noOfVisibleDays="6" sets first day visible of calendar on TODAY 22/05/2015
- noOfVisibleDays="7" sets first day visible of calendar on TODAY 11/05/2015 (22/05/2015 - 11 = 11/05/2015)

I tried to use the following methods:

        mWeekView.goToToday();
        mWeekView.goToDate(Calendar.getInstance());

but nothing worked.
I really need a big help to solve this problem. Any ideas?

Best Regards
Bruno Piccinin

**Comment by subbuboyapati** [comment]
Hi Bruno-Piccinin-RealComm,
I am also facing the same issue.
Are you using as a library or compiled library?

**Comment by caske33** [comment]
I'm guessing this has to do with: https://github.com/alamkanak/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L401-L405.

**Comment by subbuboyapati** [comment]
Uncomment this line so that you will gotoToday:
https://github.com/alamkanak/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L1406

**Comment by Bruno-Piccinin-RealComm** [comment]
Following this link
https://github.com/alamkanak/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L1406
suggested by **subbuboyapati**, it works perfectly.

Thanks all of you for the sudden help

You have saved me ;)

**Comment by caske33** [comment]
@Bruno-Piccinin-RealComm that comment shouldn't be uncommented because it will load a lot of months when you go to a far date. Better is to move https://github.com/alamkanak/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L398-L406 up above the other if-block. Or fix those lines because I'm guessing the real bug is in those lines of code.

**Comment by Bruno-Piccinin-RealComm** [comment]
Ok @caske33 ,
I followed your advice.

Thank you

**Comment by caske33** [comment]
Can you reopen this bug again @Bruno-Piccinin-RealComm? Because it's not really solved yet.

**Comment by subbuboyapati** [comment]
Hi @Bruno-Piccinin-RealComm ,
change this line of code https://github.com/alamkanak/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L403
to 
```
int difference = (7 + (mToday.get(Calendar.DAY_OF_WEEK) - mFirstDayOfWeek)) % 7;
````
Now the code works perfectly.

**Comment by caske33** [comment]
@subbuboyapati Could you maybe make a pull request for that?

**Comment by subbuboyapati** [comment]
Sure @caske33. Tomorrow i will do that.

**Comment by caske33** [comment]
Thanks!

**Comment by subbuboyapati** [comment]
Hi @caske33, i created pull request Please merge this change to master.

**Comment by caske33** [comment]
@subbuboyapati I wish I could... Unfortunately, only @alamkanak can do that because he's the only maintainer...
