### ISSUE TITLE
Weekview multiple duplication 

### ISSUE THREAD

**Issue by farhan0syakir** [alamkanak/Android-Week-View#135]
Android week view showing duplication weekviewevent

I do not know why, I've check the<code> event</code> no duplication there, but it looks like this.
![screenshot_2015-05-28-00-43-21](https://cloud.githubusercontent.com/assets/10477597/7843417/c3418692-04d3-11e5-9262-050675a5955f.png)

I use code like this
<code>
public class JadwalFragment
        extends Fragment
        implements WeekView.MonthChangeListener,WeekView.EventClickListener,WeekView.EventLongPressListener{
    private static final int TYPE_DAY_VIEW = 1;
    private static final int TYPE_THREE_DAY_VIEW = 2;
    private static final int TYPE_WEEK_VIEW = 3;
    private int mWeekViewType = TYPE_THREE_DAY_VIEW;
    Spinner monthSpinner;
    WeekView mWeekView;
    TextView tahun;
    Button button,goToTodayBtn,tambahJadwalBtn;
    String id,user,judul,startDate,tahunMulai,bulanMulai,tanggalMulai,jamMulai,menitMulai,detikMulai,endDate,tahunSelesai,bulanSelesai,tanggalSelesai,jamSelesai,menitSelesai,detikSelesai;
    String statusBook;
    NumberPicker yearpicker;
    static int counter=0;

    public JadwalFragment(){}

    Fragment fragment = null;
    JSONArray android = null;
    List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();
    List<Long> eventIdContainer = new ArrayList<>();

    Intent nextScreen;
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState)  {

        View rootView = inflater.inflate(R.layout.fragment_jadwal, container, false);
        Calendar today = Calendar.getInstance();

        mWeekView = (WeekView) rootView.findViewById(R.id.weekView);

        // Set an action when any event is clicked.
        mWeekView.setOnEventClickListener(this);

        // The week view has infinite scrolling horizontally. We have to provide the events of a
        // month every time the month changes on the week view.
        mWeekView.setMonthChangeListener(this);

        // Set long press listener for events.
        mWeekView.setEventLongPressListener(this);

        Calendar cal = Calendar.getInstance();
        addListener();
        return rootView;
    }

    public void addListener(){
        //add listener here
    }
    @Override
    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
        // Populate the week view with some events.
        try{
            new JSONParse(getActivity(),myUrl).execute().get();
        }catch (Exception e){
            System.out.println(e);
        }
        return events;
    }

    class JSONParse extends KakakuhBaseJSONParserAsyncTask {

        public JSONParse(Context context, String url) {
            super(context, url);
        }

        @Override
        protected void onPostExecute(JSONObject json) {
            try {
                // Getting JSON Array from URL
                android = json.getJSONArray("data");
                for(int i = 0; i < android.length(); i++){
                    JSONObject c = android.getJSONObject(i);
                    // Storing  JSON item in a Variable
                    id = c.getString("id_jadwal");
                    user = c.getString("user_id");
                    title = c.getString("title");
                    statusBook = c.getString("status_book");
                    //Date format 2015-05-18 09:33:00
                    startDate = c.getString("start_date");
                    endDate = c.getString("end_date");

                    try {
                        Date parsedStartDate = null, parsedEndDate = null;
                        parsedStartDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(startDate);
                        parsedEndDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(endDate);

                        Calendar startTime = Calendar.getInstance();
                        startTime.setTime(parsedStartDate);
                        Calendar endTime = Calendar.getInstance();
                        endTime.setTime(parsedEndDate);

                        WeekViewEvent event = new WeekViewEvent(Integer.parseInt(id), judul, startTime, endTime);
                        if(Integer.parseInt(statusBook)==0){
                            event.setColor(getResources().getColor(R.color.available));
                        }else{
                            event.setColor(getResources().getColor(R.color.booked));
                        }
                        if(!eventIdContainer.contains(event.getId())){//for checking we use list of id
                            events.add(event);
                            eventIdContainer.add(event.getId());
                        }else{
                            System.out.println("this value already exist");
                        }

                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                }
                pDialog.dismiss();

            } catch (JSONException e) {
                e.printStackTrace();
            }
            //debugging
            for(int i = 0 ; i<events.size();i++){
                System.out.print(events.get(i).getName()+" ");
            }
            System.out.println(counter++);
        }

    }
}

</code>

**Comment by caske33** [comment]
You should only return events within the month requested (in onMonthChange): that method will be called 3 times in order to preload the next and previous month so the scrolling is smooth. But now you're returning the events 3 times, so they get rendered 3 times.

**Comment by lolobosse** [comment]
Same as #81

**Comment by farhan0syakir** [comment]
well, i've already do it

i debug the code like this
<code>
public void onMonthChange(int newMonth, int newYear){
   //print "in onmonthchange your array size is"
}

class Asynctask{
     onPostExecute(){
          //print "in asyntaskyour array size is"
    {
}

</code>

it come like this
in asynctask your array task is 0
in asynctask your array task is 9
in asynctask your array task is 0 

in onMonthchane your array size is 9
in onMonthchane your array size is 9
in onMonthchane your array size is 9

**Comment by caske33** [comment]
It's really unclear what you are trying to say. Could you clarify your comment more?

**Comment by farhan0syakir** [comment]
I'm so sorry.

well here is my code
<code>
public class myClass
        extends Fragment
        implements WeekView.MonthChangeListener,WeekView.EventClickListener,WeekView.EventLongPressListener{
Fragment fragment = null;
JSONArray android = null;
List<WeekViewEvent> events=new ArrayList<>();
    

        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState)  {

               View rootView = inflater.inflate(R.layout.myfragment, container, false);
        
               mWeekView = (WeekView) rootView.findViewById(R.id.weekView);

              mWeekView.setOnEventClickListener(this);

              mWeekView.setMonthChangeListener(this);
              mWeekView.setEventLongPressListener(this);

              return rootView
        }

    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
        // Populate the week view with some events.
        try{
            String myUrl = "http://mywebservice/retrieve?year="+newYear+"&month="+ (newMonth-1);
            new JSONParse(getActivity(),myUrl).execute().get();
            System.out.print("my url is = "+myUrl+" size after asynctask =" + events.size());
        }catch (Exception e){
            System.out.println(e);
        }
        return events;
    }

class JSONParse extends KakakuhBaseJSONParserAsyncTask {
        String url = "";
        public JSONParse(Context context, String url) {
            super(context, url);
            this.url = url;
        }


        @Override
        protected void onPostExecute(JSONObject json) {
            events = new ArrayList<>();
            try {
                // Getting JSON Array from URL
                android = json.getJSONArray("data");
                for(int i = 0; i < android.length(); i++){
                    JSONObject c = android.getJSONObject(i);
                    
                    try {
                         //after parsing from json
                        Calendar startTime = Calendar.getInstance();
                        startTime.setTime(parsedStartDate);
                        Calendar endTime = Calendar.getInstance();
                        endTime.setTime(parsedEndDate);

                        WeekViewEvent event = new WeekViewEvent(tempInt, judul, startTime, endTime);
                        events.add(event);
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                }
                System.out.println("my url is = "+url +" and size in asynctask is "+events.size());
                pDialog.dismiss();

            } catch (JSONException e) {
                e.printStackTrace();
            }

        }

    }
}
</code>

and my result is

 I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=3 size after asynctask =10
 I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=4 size after asynctask =10
 I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=5 size after asynctask =10
 I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=3 and size in asynctask is 0
 I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=4 and size in asynctask is 0
 I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=5 and size in asynctask is 10

i mean
all my 10 events is in month 5 but my onMonthChange adding 10 events 3 times in every refresh.

do you have any idea

**Comment by caske33** [comment]
Is your webservice implemented right? 

And the `events` arraylist seems really weird. Is it shared with the state of the activity? (inside the asynctask)

**Comment by farhan0syakir** [comment]
I'm pretty sure my web service implemented right

yes it's true, it's shared. if it's ok?

**Comment by caske33** [comment]
well, during month=3, you might be returning the events you fetched during month=5

**Comment by farhan0syakir** [comment]
well i add <code>
events = new Arraylist<>();</code> before execute JSONParse so my code become this

<code>
public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
    // Populate the week view with some events.
    try{
        events = new ArrayList<>();
        String myUrl = "http://mywebservice/retrieve?year="+newYear+"&month="+ (newMonth-1);
        new JSONParse(getActivity(),myUrl).execute().get();
        System.out.print("my url is = "+myUrl+" size after asynctask =" + events.size());
    }catch (Exception e){
        System.out.println(e);
    }
    return events;
}
</code>

and my output
I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=3 size after asynctask =0
I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=4 size after asynctask =0
I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=5 size after asynctask =0
I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=3 and size in asynctask is 0
I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=4 and size in asynctask is 0
I/System.out﹕ my url is http://http://mywebservice/retrieve?year=2015&month=5 and size in asynctask is 10

and nothing on calender displayed:(

**Comment by farhan0syakir** [comment]
do you have any example of retrieve database from JSON or prevent duplicate display?

**Comment by farhan0syakir** [comment]
Thanks my code work!
i store the arraylist events on temporary arraylist and clean up events after execute:+1: 

my code look like this
<code>
public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
    // Populate the week view with some events.
    List<WeekViewEvent> tempEvents=null;
    try{
        String myUrl = "http://mywebservice/retrieve?year="+newYear+"&month="+ (newMonth-1);
        new JSONParse(getActivity(),myUrl).execute().get();
        tempEvents= new ArrayList<>(events);
        events = new ArrayList<>();
    }catch (Exception e){
        System.out.println(e);
    }
    return tempEvents;
}
</code>

thank you, good work

**Comment by lolobosse** [comment]
Cool, please close the issue because @alamkanak is not really managing the issue tracker and it'll be cool if we could keep it as clean as possible :smile:
