### ISSUE TITLE
Scroll is slow in new version 1.2.3

### ISSUE THREAD

**Issue by GabiR** [alamkanak/Android-Week-View#139]
I have tried 1.2.0, 1.2.1 and 1.2.3. The scroll runs very smooth in 1.2.0 and 1.2.1, but it is very slow in 1.2.3.

**Comment by caske33** [comment]
Could you give your configuration (layout-file) in which your declare the weekview?

**Comment by GabiR** [comment]
layout file:

<?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:orientation="vertical" android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/background_white"
        >

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:layout_margin="5dp"
        android:layout_gravity="center_horizontal">
        <TextView
            android:layout_marginRight="13dp"
            android:textSize="23dp"
            android:textStyle="bold"
            android:clickable="true"
            android:textColor="@color/albastru"
            android:background="?android:attr/selectableItemBackground"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Pe zile"
            android:id="@+id/btnCalZile"/>

        <TextView
            android:layout_marginRight="13dp"
            android:textSize="23dp"
            android:textStyle="bold"
            android:clickable="true"
            android:background="?android:attr/selectableItemBackground"
            android:textColor="@color/albastru"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Timeline"
            android:id="@+id/btnTimeline"/>

        <TextView
            android:textSize="23dp"
            android:textStyle="bold"
            android:clickable="true"
            android:textColor="@color/albastru"
            android:background="?android:attr/selectableItemBackground"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Pe luni"
            android:id="@+id/btnCalLuni"/>

      </LinearLayout>

    <TextView
        android:id="@+id/text_calendar"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@color/transparent"
        android:gravity="right"
        android:paddingBottom="5dp"
        android:text="Calendar"
        android:textColor="@color/albastru"
        android:layout_alignParentLeft="true"
        android:layout_marginLeft="10dp"
        android:layout_marginTop="7dp"
        android:textSize="28dp"/>

    <LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:orientation="horizontal"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content">

        <ImageView
            android:id="@+id/prevMonth"
            android:src="@drawable/calendar_left_arrow_selector"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">
        </ImageView>
        <TextView
            android:id="@+id/currentDateTxt"
            android:layout_weight="0.6"
            android:textColor="#000000"
            android:textAppearance="?android:attr/textAppearanceMedium"
            android:background="@drawable/calendar_bar"
            android:text=""
            android:gravity="center"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">
        </TextView>
        <ImageView
            android:id="@+id/nextMonth"
            android:src="@drawable/calendar_right_arrow_selector"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">
        </ImageView>
    </LinearLayout>

        <com.alamkanak.weekview.WeekView
            android:id="@+id/weekView"
            android:layout_width="match_parent"
            android:layout_height="370dp"
            android:layout_margin="10dp"
            app:eventTextColor="@android:color/white"
            app:textSize="12sp"
            app:hourHeight="60dp"
            app:headerColumnPadding="8dp"
            app:headerColumnTextColor="#8f000000"
            app:headerRowPadding="12dp"
            app:columnGap="8dp"
            app:noOfVisibleDays="7"
            app:headerRowBackgroundColor="#ffefefef"
            app:dayBackgroundColor="#05000000"
            app:todayBackgroundColor="#1848adff"
            app:headerColumnBackground="#ffffffff"/>

    </LinearLayout>



configuration:

//tablet
if (checkScreenInches(getActivity()) >= 7) {
    calendarView.setNumberOfVisibleDays(7);
    calendarView.setColumnGap((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 3,
getResources().getDisplayMetrics()));
    calendarView.setTextSize((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, 15,
getResources().getDisplayMetrics()));
    calendarView.setEventTextSize((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, 15,
getResources().getDisplayMetrics()));

}  //small smartphone
else if (checkScreenInches(getActivity()) < 4) {
    calendarView.setNumberOfVisibleDays(5);
    calendarView.setColumnGap((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 2,
getResources().getDisplayMetrics()));
    calendarView.setTextSize((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, 8,
getResources().getDisplayMetrics()));
    calendarView.setEventTextSize((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, 10,
getResources().getDisplayMetrics()));

} //big smartphone

else {
    calendarView.setNumberOfVisibleDays(7);
    calendarView.setColumnGap((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 2,
getResources().getDisplayMetrics()));
    calendarView.setTextSize((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, 10,
getResources().getDisplayMetrics()));
    calendarView.setEventTextSize((int)
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, 12,
getResources().getDisplayMetrics()));

}



2015-06-05 12:07 GMT+03:00 Jens Claes <notifications@github.com>:

**Comment by caske33** [comment]
Ok, I'm not seeing anythin suspicious in there so I guess it's a bug with the library indeed. Does it occur on both small smartphones as the tablets (i.e. 5 and 7 days visible days)?

**Comment by lolobosse** [comment]
Cannot it be linked to #83 ?

**Comment by GabiR** [comment]
No, it isn't really about the speed, it blocks. And yes it occurs on both 5
and 7 days configurations.

În data de vineri, 5 iunie 2015, Laurent Meyer <notifications@github.com> a
scris:

**Comment by lolobosse** [comment]
Ok I'll try to reproduce it today.

**Comment by lolobosse** [comment]
Cannot reproduce it on the newest version of the lib, do you have your code online in order that we really can check it ?

**Comment by marunjar** [comment]
I'm havin similar issues, scrolling isn't smooth any more and it stocks every once and a while.
I just had a look at the android docs and it looks like we can improve scrolling a little bit.

I'll try to fix it and make a first pr if i have something.
