### ISSUE TITLE
Help with methods to add events

### ISSUE THREAD

**Issue by JHNBOS** [alamkanak/Android-Week-View#142]
Hello everyone, for school we are making Android apps. And I want to create a calendar in which you can add events. I've read the open and closed issues, but most are not complete.

If anyone can help me, would really appreciate!

Thanks

**Comment by caske33** [comment]
You'll probably want to use the EmptyViewClickListener.

Not really sure what else you're really asking. Try to be more specific, otherwise it's hard to help.

**Comment by JHNBOS** [comment]
Thanks for your reply. I am asking for a way to create events with a title, date etc. using user input

**Comment by caske33** [comment]
I would suggest to take a look at the sample app on how to create events. Regarding user input, I think you best read some general android tutorials.
