### ISSUE TITLE
Implement a calendar getter

### ISSUE THREAD

**Issue by lolobosse** [alamkanak/Android-Week-View#143]
Hi guys,

I try to extend the library to have more features: I thought it could be a good idea to have a calendar getter directly working out of the box. I had no problem integrating it and getting my events in it. BUT, I have questions:

 * Do you think this feature should be supported by the library itself? Or should we do an independent project? 
 * I have a backward compatibility problem, the lib is compatible from API 9 and these `CalendarContract.Events` and `CalendarContract.Calendars` only exists since API 14. That's why I'm wondering what's the best solution for the integration of this feature in the library.

**Comment by caske33** [comment]
With "calendar getter", you mean getting the calendars that are on the phone already?

I think this should be an extension library. That would also solve the API-issues.

**Comment by alamkanak** [comment]
@lolobosse The first thing that comes into my mind is to have a helper class (more like an adapter) that will retain the events set by the user.

**Comment by alamkanak** [comment]
Sorry, posted my last comment in the wrong issue.

**Comment by caske33** [comment]
I'm going to close this because I think this behaviour shouldn't be part of the library. Maybe an extension-library or so, but not in the core.
