### ISSUE TITLE
OnDraw() is being called in a loop

### ISSUE THREAD

**Issue by tajchert** [alamkanak/Android-Week-View#146]
Event without any touches or changes onMonthChange is called in a loop (each time with month = 5,6,7 (where only 5 is correct)) and whole WeekView is redrawn.
Just go to Developer options -> Monitoring and profile GPU usage as a bars to see how crazy redrawing of this view are.

**Comment by tajchert** [comment]
Ok, so problem was that I called:
setHourHeight
goToDate
goToHour 
in a onMonthChange  which resulted in redrawing view. After removing it from listener it is fine.
So my bad but it would be nice to mention this in Wiki or catch such situation.

**Comment by caske33** [comment]
PS The month parameter of onMonthChange is 1-based. So "the correct one" would be 6. And the reason those 3 months are requested is because the previous, current and next month are loaded, so that you can scroll smoothly into those months without problems.
