### ISSUE TITLE
OnMonthChange event with Progress Dialog

### ISSUE THREAD

**Issue by Bruno-Piccinin-RealComm** [alamkanak/Android-Week-View#147]
Is it possible to show a Progress Dialog during onMonthChange loading?

In my onMonthChange event I call a WS that return the data to show in my calendar and i would to show a progress dialog when onMonthChange is running, because at the moment when the onMonthChange is called (mostly on starting app), the screen is all black until the onMonthChange is finished it's work.

**Comment by caske33** [comment]
You should check https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158 to see how to load events async. The onMonthChange is not meant to be used in an async way.

**Comment by alamkanak** [comment]
@caske33's answer is correct. Check https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158
