### ISSUE TITLE
Explain Methods 

### ISSUE THREAD

**Issue by tommypacker** [alamkanak/Android-Week-View#161]
Hey guys, could you explain the startTime.set(Calendar.MONTH, int) and startTime.set(Calendar.YEAR, int) methods?

What exactly goes into the in parameter?

Thanks

**Comment by Axel6** [comment]
For the first one the month from 0 to 11, and for the second the year.

You can find all the information about Java Calendar class here http://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html.

**Comment by tommypacker** [comment]
One more question, how come when my WeekViewEvent list is an instance variable, I get two events on my calendar? I can only get my calendar to work properly if the list is a local variable

**Comment by tommypacker** [comment]
Nvm, figured it out
