### ISSUE TITLE
Serializable class

### ISSUE THREAD

**Issue by Axel6** [alamkanak/Android-Week-View#162]
Hi, 

I need to put WeekViewEvent instances in a Bundle so could you please make the class to implement Serializable?

Thanks

**Comment by lolobosse** [comment]
I'm not a big fan of the serialization... If I were you, I would convert the object to JSON string with the Google GSON lib and attach it to the Bundle.

**Comment by caske33** [comment]
You can now subclass WeekViewEvent, so you can make it serializable yourself.
