### ISSUE TITLE
Height of last hour is smaller

### ISSUE THREAD

**Issue by chawdee** [alamkanak/Android-Week-View#163]
Dear all,
    I found the last hour is smaller than others. Can I set the layout or scroll bottom to make it equal?. My work must add event with image, the image is cut on the last hour.

Thank you.

1. Every hours are 2.46 cm height.
![1](https://cloud.githubusercontent.com/assets/5681376/9036113/71d26a64-3a08-11e5-9bf0-92dc0536124b.png)

2. Only last hour is 2.14 cm height.
![2](https://cloud.githubusercontent.com/assets/5681376/9036131/9fea75d6-3a08-11e5-9d97-206961faf904.png)

**Comment by lolobosse** [comment]
Ok, that's a bug... :cry: :sob: 

I think I spotted and then ignored it, I guess you can reduce the optical effect of it by adding a padding at the bottom of your view. But if you want to fix it: go for it ! :+1: :clap:

**Comment by caske33** [comment]
Fixed by #195
