### ISSUE TITLE
How to change the Title of the Event?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [alamkanak/Android-Week-View#164]
Hi, 

Is it possible to change title/text shown on the event?

Thanks.

**Comment by chawdee** [comment]
You can set the title on WeekViewEvent.mName. In the sample project, this field is composed on method getEventTitle.

**Comment by caske33** [comment]
@chawdee is correct. You can set this field in the constructor too, as the 2nd parameter (if you don't use the empty constructor)
