### ISSUE TITLE
WeekView scrolls to 00:00 am when scrolling

### ISSUE THREAD

**Issue by timkoers** [alamkanak/Android-Week-View#170]
When scrolling the weekView very fast it happens more often, but when scrolling the weekView. 
The weekView goes scrolls up to 00:00 am, is this a bug?
Or is this because I'm calling
weekView.notifyDatasetChanged();
                    weekView.forceLayout();
                    weekView.requestLayout();

From within the OnMonthChangeListener?

Thanks in advance?

Tim

**Comment by caske33** [comment]
Are you scrolling horizontally or vertically?

**Comment by timkoers** [comment]
Horizontally

**Comment by caske33** [comment]
That doesn't happen with me, so I'm guessing that the functions you're calling cause that "bug"

**Comment by lolobosse** [comment]
Can you post the code you're using in order that we ensure that it's not a bug ?

**Comment by timkoers** [comment]
The bug was calling one of these (or all of them :-P)

weekView.notifyDatasetChanged();
weekView.forceLayout();
weekView.requestLayout();

Thanks!
