### ISSUE TITLE
empty event listener

### ISSUE THREAD

**Issue by richa-glorify** [alamkanak/Android-Week-View#171]
i want to make empty spaces clickable & filled spaces(with events) non-clickable. So can you please guide me how could i implement this?

**Comment by lolobosse** [comment]
Hi @richa-glorify, just implement `setEmptyViewClickListener` and not `setOnEventClickListener`

**Comment by richa-glorify** [comment]
thanks.
actually i did used setEmptyViewClickListener but forgot to add this:
mWeekView.setEmptyViewClickListener(this);
that's why it wasn't working.
Anyways, thanx.
