### ISSUE TITLE
Ability to lock scrolling to a certain region

### ISSUE THREAD

**Issue by timkoers** [alamkanak/Android-Week-View#172]
Is there the ability to lock the scrolling to a certain region?

I haven't found one.

Thanks,

Tim

**Comment by caske33** [comment]
That's not possible yet

**Comment by timkoers** [comment]
Any plans of adding this fuction? It will be an amazing feature to only show the events that are needed to be shown.

**Comment by caske33** [comment]
Not yet, but you're free to take a shot. it's a highly requested feature, so many people would thank you.

**Comment by caske33** [comment]
Going to close this one in favor of #6
