### ISSUE TITLE
Monthly Calendar View

### ISSUE THREAD

**Issue by ChrisDolge** [alamkanak/Android-Week-View#175]
Hi, 

thanks for great plugin. 

Is it possible to add a monthly view?

**Comment by caske33** [comment]
It has been requested before, but it's not yet on the roadmap yet as there are not a lot of people developing for the library right now.

But feel free to take a shot and make a pull request!

**Comment by kprathap23** [comment]
It's a good idea to have Monthly View in this Library..Its very helpful

**Comment by caske33** [comment]
Btw I'm gonna close this in favor of #2
