### ISSUE TITLE
Scroll issues when the hour height is changed

### ISSUE THREAD

**Issue by madalinb** [alamkanak/Android-Week-View#178]
Hello. I changed the hourHeight to 10dp ( app:hourHeight="10dp") and the scrolling doesn't work anymore. See the pictures below. 
![1](https://cloud.githubusercontent.com/assets/5980227/9926991/1c2f03b8-5d23-11e5-9e96-bac630d5efad.png)
![2](https://cloud.githubusercontent.com/assets/5980227/9926993/1c3476b8-5d23-11e5-9573-830513f73742.png)
![3](https://cloud.githubusercontent.com/assets/5980227/9926992/1c321526-5d23-11e5-8e80-f7431a2d6a5b.png)

**Comment by madalinb** [comment]
The solution we found was to check content height before setup the mCurrentOrigin.y. 
So, in 'drawTimeColumnAxes' method add the following lines at the beginning:
....
        if (mCurrentScrollDirection == Direction.VERTICAL) {
            float contentHeight = (getHeight() - mHeaderTextHeight + mHeaderRowPadding * 2);
            if (contentHeight >= mHourHeight * 24) {
                mCurrentOrigin.y = 0;
            } else if (mCurrentOrigin.y - mDistanceY > 0) {
                mCurrentOrigin.y = 0;
            } else if (mCurrentOrigin.y - mDistanceY < -(mHourHeight * 24 + mHeaderTextHeight + mHeaderRowPadding * 2 - getHeight())) {
                mCurrentOrigin.y = -(mHourHeight * 24 + mHeaderTextHeight + mHeaderRowPadding * 2 - getHeight());
            } else
                mCurrentOrigin.y -= mDistanceY;
        }
.....

and in 'drawHeaderRowAndEvents' method add:
....
            float contentHeight = (getHeight() - mHeaderTextHeight + mHeaderRowPadding * 2);
            if (contentHeight >= mHourHeight * 24)
                mCurrentOrigin.y = 0;
......
after 
            // Prepare the separator lines for hours.
            int i = 0;

Hope it helps!

**Comment by caske33** [comment]
Does this still happen in 1.2.5?
