### ISSUE TITLE
Scroll only one day at a time

### ISSUE THREAD

**Issue by db-dblank** [alamkanak/Android-Week-View#185]
Currently if I scroll fast it scrolls many days at a time.

Is it possible to always scroll one day at a time? Like Google Calendar.

Thanks.

**Comment by lolobosse** [comment]
Yes, it is, it's working this way in my implementation (but it's not open source, I shall not release the code). You have to play with the `onFling` method and set a flag like `dayHasChanged`

**Comment by caske33** [comment]
there is also an attribute xScrollSpeed or something like that. If you set it to a lower value, it will scroll one day at a time.

**Comment by lolobosse** [comment]
Yeah that's even better
