### ISSUE TITLE
Set Moday as the default firstday of the week

### ISSUE THREAD

**Issue by ErenRavenHeart** [alamkanak/Android-Week-View#186]
I have set the  gotodate like this,

        date.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
        mWeekView.goToDate(date); 

on my oncreate function to set Moday as the default firstday of the week however when I set the noOfVisibleDays to 7 the displayed first day of the week is not Monday, on the other hand if i set it to 3 it works perfectly.I really need it to display 7 Visible Days because I want to let the user know its class schedule from monday to sunday on the applications startup. please help.

**Comment by caske33** [comment]
`setFirstDayOfWeek()`

**Comment by ErenRavenHeart** [comment]
Hello 
So i did what you said but the weekview still doesn't start at monday..
