### ISSUE TITLE
Start Calendar from particular hour

### ISSUE THREAD

**Issue by jagdishkk1989** [alamkanak/Android-Week-View#19]
Hi,
Can we display the calendar from particular hour in week view like from 6:00 AM to 8:00 PM. If anyone have idea please reply.Thanks in advance...

**Comment by vedp6789** [comment]
@alamkanak  Thanks for the library, and we can customize it also if there is something missing.

**Comment by fnfis** [comment]
Hi , Is it possible can start calendar hours  row from 8 Am to 10 PM in place of 12 Am to 11 PM.Please any one share how i can do like this.

**Comment by monikarora** [comment]
Hi,
i want show hour in week view 9 AM to 8 PM , 9 PM to 8 AM don't show in week view.
![device-2017-03-30-192024](https://cloud.githubusercontent.com/assets/17878500/24507461/23085968-157e-11e7-9f57-9a72d98ec765.png)
i already remove bottom space ,but i can't hide top space 
If anyone know  please help me.Thanks

**Comment by monikarora** [comment]
Hey @fnfis  check this link  https://github.com/alamkanak/Android-Week-View/issues/42

**Comment by monikarora** [comment]
Hey @fnfis   try this link  https://github.com/mrwhite1/WeekViewLibrary

**Comment by monikarora** [comment]
Hey @fnfis  check this link https://github.com/alamkanak/Android-Week-View/issues/42#ref-issue-47245694

**Comment by monikarora** [comment]
Hey @fnfis check this link https://github.com/alamkanak/Android-Week-View/issues/42#ref-issue-47245694

**Comment by neelmevada** [comment]
Need to show single weekview Display 10am to 6pm only is that possible ?

**Comment by jeetendra-kumar** [comment]
@neelmevada yes it is possible.
