### ISSUE TITLE
How to modify the date in vertical order

### ISSUE THREAD

**Issue by SANTOSHBHARATI** [alamkanak/Android-Week-View#197]
![img](https://cloud.githubusercontent.com/assets/5242358/10483634/00076d48-729e-11e5-8acf-3671ab83754e.png)

**Comment by marunjar** [comment]
You can use the default formatting if you do not set a DateTimeInterpreter, that should be fine in most cases.

Or as you can see in the sample app you can use your own DateTimeInterpreter to format date and hour and that's the code for
     
	mWeekView.setDateTimeInterpreter(new DateTimeInterpreter() {
		@Override
		public String interpretDate(Calendar date) {
			SimpleDateFormat weekdayNameFormat = new SimpleDateFormat("EEE", Locale.getDefault());
			String weekday = weekdayNameFormat.format(date.getTime());
			SimpleDateFormat format = new SimpleDateFormat(" M/d", Locale.getDefault());

			// All android api level do not have a standard way of getting the first letter of
			// the week day name. Hence we get the first char programmatically.
			// Details: http://stackoverflow.com/questions/16959502/get-one-letter-abbreviation-of-week-day-of-a-date-in-java#answer-16959657
			if (shortDate)
				weekday = String.valueOf(weekday.charAt(0));
			return weekday.toUpperCase() + format.format(date.getTime());
		}

		@Override
		public String interpretTime(int hour) {
			return hour > 11 ? (hour - 12) + " PM" : (hour == 0 ? "12 AM" : hour + " AM");
		}
	});

**Comment by SANTOSHBHARATI** [comment]
Same code I have used but it is coming like above attached screenshot. 
Not able to change vertical time from 0 PM to 12 PM I have tried even in library sample also same .

**Comment by caske33** [comment]
The code above will give you 0PM if hour==12

```mWeekView.setDateTimeInterpreter(new DateTimeInterpreter() {
    @Override
    public String interpretDate(Calendar date) {
        SimpleDateFormat weekdayNameFormat = new SimpleDateFormat("EEE", Locale.getDefault());
        String weekday = weekdayNameFormat.format(date.getTime());
        SimpleDateFormat format = new SimpleDateFormat(" M/d", Locale.getDefault());

        // All android api level do not have a standard way of getting the first letter of
        // the week day name. Hence we get the first char programmatically.
        // Details: http://stackoverflow.com/questions/16959502/get-one-letter-abbreviation-of-week-day-of-a-date-in-java#answer-16959657
        if (shortDate)
            weekday = String.valueOf(weekday.charAt(0));
        return weekday.toUpperCase() + format.format(date.getTime());
    }

    @Override
    public String interpretTime(int hour) {
        if(hour == 12) { return "0PM";}
        return hour > 11 ? (hour - 12) + " PM" : (hour == 0 ? "12 AM" : hour + " AM");
    }
});```

should work
