### ISSUE TITLE
android:allowBackup should not be set by a library

### ISSUE THREAD

**Issue by mndfcked** [alamkanak/Android-Week-View#198]
The android:allowBackup=true option in the manifest causes errors while merging with our manifest. We've set it to false.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':StudIPAndroidApp:processBetaDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:20:9-36
  	is also present at [com.github.alamkanak:android-week-view:1.2.3] AndroidManifest.xml:9:18-44 value=(true)
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:13:5-15:19 to override
```
Since this can have security implications, setting this option should be up to the app developer.

**Comment by caske33** [comment]
@alamkanak Do you happen to know the reason why it's there in the first place? It seems to originate from the very first commit.

**Comment by cdeange** [comment]
@caske33 I would imagine it's there because it was autogenerated by Android Studio/Eclipse. IMO there shouldn't be an `<application>` tag in the library module at all.

**Comment by caske33** [comment]
The problem is that I don't really know that much about Android Libraries and how the Application tag works. Do you have any resource that explains what the effects are? Because if it's generated with Android Studio / Eclipse, I'd guess the defaults are ok?

@lolobosse @marunjar Do you guys have experience with this stuff.

**Comment by marunjar** [comment]
sry, have no idea about this.
manifest merging is a little bit complicated [1]
in this case i think the allowBackup attribute should be removed completely


[1] http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger
