### ISSUE TITLE
how can i drag the event?

### ISSUE THREAD

**Issue by a1018875550** [alamkanak/Android-Week-View#199]
it have listenter to drag the event?

**Comment by a1018875550** [comment]
and did you look the aCalendar on ios;colude this like that?

**Comment by caske33** [comment]
It's not possible yet. 

No idea what you mean with the 2nd comment.

**Comment by a1018875550** [comment]
Can I write myself to drag the event?if is possible,how do I do?

**Comment by caske33** [comment]
You can add the library as a git and gradle submodule. (`project(':Android-Week-View:library')` instead of `compile`)

**Comment by a1018875550** [comment]
maybe you don't understand my meaing;I want to add the drag the event to mySelf;So how do i do?

**Comment by caske33** [comment]
If you add the library as a git and gradle submodule, you can start editing the library yourself. 

Or you can develop it yourself using the example application provided with the library and then submit a Pull Request.

**Comment by caske33** [comment]
I'm going to close this in favor of #157
