### ISSUE TITLE
I want don't use the hour,How do i do?

### ISSUE THREAD

**Issue by a1018875550** [alamkanak/Android-Week-View#203]
I want don't use the hour,Listed events;I want to show the evet on day;not in hour;So how do I do?Thanks!

**Comment by caske33** [comment]
What do you mean exactly?

**Comment by a1018875550** [comment]
I don't  want use the hour ，how should I do

**Comment by caske33** [comment]
So you only want to show which events on which day? 

You could adapt some attributes regarding the hourLines to make them dissapear I guess. And maybe overwrite the Interpreter of the time so it always returns the empty string. But I'm thinking this library doesn't make much sense without the hour.
