### ISSUE TITLE
onFirstVisibleDayChanged gives wrong results.

### ISSUE THREAD

**Issue by James665** [alamkanak/Android-Week-View#204]
I have a textview in the top of my xml file. When I scrolling a DayView , the current date should be displayed in this textview. But sometimes day scrolling is not fully ( Header textLabel changed , when I scroled day horizontally,but my textview is not). When I correct  this(scroll again this day for a little to the left side), my textview shows the correct date.
My problem such like this
https://github.com/alamkanak/Android-Week-View/issues/126
How fix this or can I clear header text label   and  display at him nothing all the time?

**Comment by caske33** [comment]
can you show the part of your code that is relevant?

**Comment by James665** [comment]
@Override
    public void onFirstVisibleDayChanged(Calendar newFirstVisibleDay, Calendar oldFirstVisibleDay) {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMMM dd , EEEE ", Locale.ENGLISH);
        String mText = simpleDateFormat.format(newFirstVisibleDay.getTime());
                mControl.setText(mText);
    }

If I scroll to the right side, the text in  mControl does not match the selected day. if I'm a little scroll again, text in the mControl changed for the correct.

if I use

@Override
    public void onFirstVisibleDayChanged(Calendar newFirstVisibleDay, Calendar oldFirstVisibleDay) {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMMM dd , EEEE ", Locale.ENGLISH);
        String mText = simpleDateFormat.format(newFirstVisibleDay.getTime());
        mWeekView.goToDate(newFirstVisibleDay);
        mControl.setText(mText);
    }

Then scrolling and the date displaying are synchronous. It`s that ,what I need.... But... if I scoll to the left,scrolling is very fast.

DayView scrolling better  for all when there is no ScrollListener.
But in this case  scrolling and the date displaying are not synchronous. 
![xmpl](https://cloud.githubusercontent.com/assets/15358666/10850021/2a644954-7f2c-11e5-9404-f950acee2770.jpg)

**Comment by caske33** [comment]
Hmm. seems like a bug indeed. 

Do you know how we can reproduce this bug?

**Comment by James665** [comment]
You can create a textview with current date and try to synchronize it with your dayview. (In my case that`s a button that show(hide) a calendar . and everytime I set text with selected date in it) .

**Comment by James665** [comment]
in what term the bug can be fixed ?

**Comment by caske33** [comment]
I'm not sure. I'd have to test if it still occurs in the latest code which isn't released to maven yet and then I need to figure out why it isn't working exactly.

**Comment by caske33** [comment]
@James665 Does this bug still occur in 1.2.5?

**Comment by caske33** [comment]
Going to close this in favor of #126
