### ISSUE TITLE
Push Notification / Alarm for events

### ISSUE THREAD

**Issue by obaslan** [alamkanak/Android-Week-View#207]
I know this is a very generic question but I had a hard time finding a simple answer online. Is there a way of showing push notifications in the status bar/ triggering an alarm if there is an upcoming event? 

I am sure almost everyone who uses this repository will eventually need to do implement this functionality. So it will be very helpful to many.

Thanks in advance

**Comment by caske33** [comment]
Considering this is a library for showing the weekview, not really for anything else around it.

That being said, I would take a look at https://developer.android.com/reference/android/app/AlarmManager.html. Or just google for Push Notifications / Alarms and apply it to your use case.
