### ISSUE TITLE
Header Text changing

### ISSUE THREAD

**Issue by android1brainbitz** [alamkanak/Android-Week-View#208]
Is there any way to change the header text of WeekView . I did not find anything like that.

**Comment by caske33** [comment]
I believe you have to implement a DateTimeInterpreter and implement https://github.com/alamkanak/Android-Week-View/blob/develop/library/src/main/java/com/alamkanak/weekview/DateTimeInterpreter.java#L9 and then pass an instance of that class to the weekview via `setDateTimeInterpreter()`
