### ISSUE TITLE
Sample app is not working on the development branch

### ISSUE THREAD

**Issue by Lanzeroth** [alamkanak/Android-Week-View#209]
I was working with the 1.2.3, and I decided to try to use the development branch, but the sample events are not working, and If I try to add them programmatically it just shows one (calling notifyDatasetChanged(); )

Do you have any clue of what could be happening, or do any extra step is needed now?

**Comment by marunjar** [comment]
this "bug" seems to be introduced by 853ca78
now every event has to have an unique id but the sample app isn't updated yet.

**Comment by caske33** [comment]
@Lanzeroth @kunalwagle This should be fixed in the latest commit.
