### ISSUE TITLE
Problem with mWeekView.getFirstVisibleDay()

### ISSUE THREAD

**Issue by DaConceicao-Nelson** [alamkanak/Android-Week-View#21]
Hi,
When i try to use `mWeekView.getFirstVisibleDay()`, I've a problem. When I'm in 3 days view, `mWeekView.getFirstVisibleDay()` does not always return the correct day. Sometimes it returns the previous day. 

I made a sample that returns the first date displayed by the view and this is the result :

1. `mWeekView.getFirstVisibleDay()` returns the good day
![screenshot_2014-11-04-09-15-52](https://cloud.githubusercontent.com/assets/5536480/4896622/018acdc8-63fd-11e4-9273-e52be8d1abc4.png)

2. `mWeekView.getFirstVisibleDay()` returns a bad day
![screenshot_2014-11-04-09-16-18](https://cloud.githubusercontent.com/assets/5536480/4896627/0d839a06-63fd-11e4-8fe9-e541ff580c9b.png)

Do you have an idea to solve this problem?

Thank's for your help !

**Comment by caske33** [comment]
Does this problem still occur in the latest version? (I think it might be affected by scrolling, and there were some changes to scrolling behaviour in the past commits).

**Comment by DaConceicao-Nelson** [comment]
With the latest version , this problem seems to be fixed ! Thank's a lot !
