### ISSUE TITLE
How to show to lines as header

### ISSUE THREAD

**Issue by ChrisDolge** [alamkanak/Android-Week-View#214]
Hi

First it is great library. :+1: 

I want to show a two line header for every day. 

And here's a screenshot of roughly what I'm going for:
<img width="422" alt="bildschirmfoto 2015-12-01 um 15 38 17" src="https://cloud.githubusercontent.com/assets/6907301/11503578/9931d74c-9841-11e5-9a06-a1ba472cc290.png">

Here's a screenshot of what the calendar looks like:
<img width="442" alt="bildschirmfoto 2015-12-01 um 15 39 14" src="https://cloud.githubusercontent.com/assets/6907301/11503605/b1a41d26-9841-11e5-99de-244162782d31.png">

Any suggestion ?

**Comment by caske33** [comment]
I don't think this is possible without tweaking the library yourself. But the library is rather straight forward, so I'd say: give it a shot!

(if you make it generic, we might even be able to integrate it for everyone, for example to show all-day events there).

**Comment by ChrisDolge** [comment]
Ok , 

I'll have a look. :wink:

**Comment by ChrisDolge** [comment]
@caske33 I close this issue , because I found a solution, but it isn't generic at the moment. 

And I have not the time yet. 

Sorry
