### ISSUE TITLE
How to get the current month from weekview

### ISSUE THREAD

**Issue by ChrisDolge** [alamkanak/Android-Week-View#215]
Hi, 

is there a point where i get the current month from weekview ? If I use onMonthChange listener , I don't get the current but I get the next.

Thats what I looking for:
Calendar calendar = weekView.getCurrentMonth();

**Comment by caske33** [comment]
onMonthChange listener uses a 1-based month number. The default Calendar API uses a 0-based month number. That's probably why it looks like you get the next month.
