### ISSUE TITLE
Different current firstVisibleDays after init WeekView

### ISSUE THREAD

**Issue by ChrisDolge** [alamkanak/Android-Week-View#216]
If I set numberOfVisibleDays = 3 in xml, weekview show the currentday as firstVisibleDay. 

![bildschirmfoto 2015-12-03 um 11 56 03](https://cloud.githubusercontent.com/assets/6907301/11558767/da6a2222-99b4-11e5-84df-504f6ad57c7a.png)

If I change numberOfVisibleDay to 7 , weekview show not the currentday as firstVisibleDay.

![bildschirmfoto 2015-12-03 um 11 54 41](https://cloud.githubusercontent.com/assets/6907301/11558745/b4433020-99b4-11e5-9f1f-d3135e1206c8.png)

I think numberOfVisibleDays = 7 , should also show the currentday as firstVisibleDay.

This was tested with the sample app.

**Comment by caske33** [comment]
with 7 I think you start on monday by default.

**Comment by ChrisDolge** [comment]
Yes you are right.

I add further variable to disable or enable this part of code.

Thx for respone :+1:
