### ISSUE TITLE
Go to particular dayview by clicking on the day rather than todays dayview

### ISSUE THREAD

**Issue by tanve** [alamkanak/Android-Week-View#220]
Go to particular dayview by clicking on the day rather than todays dayview and viewing perticular days day view

**Comment by caske33** [comment]
I'm not quite sure what you mean with that, can you elaborate?

**Comment by kprathap23** [comment]
mWeekView.goToDate(Calendar cal)

**Comment by tanve** [comment]
if  clicked on empty view or event  in weekview it should move to day view  of perticular date

**Comment by caske33** [comment]
If you can click on that event, aren't you already on that day?

But I guess you can implement it with the EmptyViewClickListener and the ClickEventListener or something like that. And then use the mWeekView.goToDate(Calendar cal) function.

**Comment by obaslan** [comment]
It should be something like the following:
inside OnCreate

weekView.setEmptyViewClickListener(emptyViewClickListener);
weekView.setOnEventClickListener(eventClickListener);

Outside your OnCreate

private WeekView.EmptyViewClickListener emptyViewClickListener = new WeekView.EmptyViewClickListener() {
		@Override public void onEmptyViewClicked(Calendar calendar) {
                 weekView.setNumberOfVisibleDays(1);
                weekView.goToDate(calendar);


		}
	};

private WeekView.EventClickListener eventClickListener = new WeekView.EventClickListener() {
		@Override
		public void onEventClick(WeekViewEvent weekViewEvent, RectF rectF) {
                weekView.setNumberOfVisibleDays(1);                
                weekView.goToDate( weekViewEvent.getStartTime() );


		}

	};
