### ISSUE TITLE
Displaying events from cloud - help

### ISSUE THREAD

**Issue by LeoJHarris** [alamkanak/Android-Week-View#222]
Hi, just wondering how it might be possible to get events from the cloud and display using this library, I have a async task that gets a list of events from the cloud, however the MonthChangeListerner() displays the events, the async task will finish after it has initialised the MonthChangeListerner() which means that that the events list will likely be empty (as in my case). This seems quite tricky to display events that exist on the cloud. Any suggestions? Thanks in advance.

**Comment by lolobosse** [comment]
I basically did that a long time ago and it's not very tricky: you have some `invalidate()` and `notifyDataSetChanged()` and the view so what you have to do is to is to make it load empty and, then, at the end of your `AsyncTask` just call `WeekView.notifyDataSetChanged()` (maybe you need to run that on UI Thread but not even sure) and you should have your data.

Hope it helps

**Comment by LeoJHarris** [comment]
Awesome, will give it a go and post the results. Thanks!

**Comment by LeoJHarris** [comment]
Hi, have manged to get the data but its not displaying it, I have declared mWeekView.notifyDatasetChanged() and mWeekView.invalidate() in the on onPostExecute of the async task, in the doInBackground() I am populating my List<WeekViewEvent> and the onMonthChange just returns an empty list. Seems from debugging (see screenshots) that mWeekView.notifyDatasetChanged() and mWeekView.invalidate() in the onPostExecute get executed before it gets the data, which is why I suppose it loads the data but doesn not display it as the the notifyDatasetChanged and invalidate happen before I have the data. See the screenshots.
![notify](https://cloud.githubusercontent.com/assets/5468757/11743280/264fb82a-a06b-11e5-9da7-7e148bda2fef.png)
![onmonthchange](https://cloud.githubusercontent.com/assets/5468757/11743281/2655e7cc-a06b-11e5-8c9e-e7a7bd535cdf.jpg)

**Comment by caske33** [comment]
@LeoJHarris Are you sure you are returning the right list?

**Comment by LeoJHarris** [comment]
Its working now, it was passing the right list, the dates for events weren't quite correct though, I'm using the newMonth but not the newYear variables and its fine. Your quite correct invalidate() is not necessary.

**Comment by nrazon** [comment]
@LeoJHarris Can you share your logic of getting events from cloud(asynctask). I am trying to implements but stucked on no event months and causing infinite calls to onmonthchange

**Comment by LeoJHarris** [comment]
@nrazon This worked for me, in the doInBackground get the events from the cloud and as @lolobosse stated you need to call in notifyDataSetChanged() in the onPostExecute of the asynctask so it will redraw the Weekview. In onMonthChange() just check that whatever list it has is not null and not empty otherwise create your WeekViewEvent objects and return your list of events, so the first time it runs onMonthChange() it should just contain a empty list that you declared global. When the Async task completes and calls notifyDataSetChanged() it should have that list now populated with your events from the doInBackground from the cloud.
