### ISSUE TITLE
How do i prevent the same event being clicked again and again ?

### ISSUE THREAD

**Issue by Swapnil-Garg16** [alamkanak/Android-Week-View#224]
How do i prevent the same event being clicked again and again ?

**Comment by caske33** [comment]
I guess, you can keep a `Set<Long>` in your application which keeps track of the id's of the events that have been clicked

**Comment by Swapnil-Garg16** [comment]
How to do that ? How to generate the id of an event clicked ?

**Comment by caske33** [comment]
```mWeekView.setOnEventClickListener(new EventClickListener(){
    void onEventClick(WeekViewEvent event, RectF eventRect){
        //get event id from WeekViewEvent
    }
}
