### ISSUE TITLE
Day View Events not showing Properly

### ISSUE THREAD

**Issue by kprathap23** [alamkanak/Android-Week-View#226]
I am testing in different ways  to show events in dayview/weekview.  using below dates, i cannot see the last two events showing in dayview/weekview. Can somebody test this.

 @Override
    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {

        // Populate the week view with some events.
        List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();

        Calendar startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 0);
        startTime.set(Calendar.MINUTE, 0);
        startTime.set(Calendar.MONTH, newMonth - 1);
        startTime.set(Calendar.YEAR, newYear);
        Calendar endTime = (Calendar) startTime.clone();
        endTime.set(Calendar.HOUR_OF_DAY, 24);
        endTime.set(Calendar.MONTH, newMonth - 1);
        WeekViewEvent event = new WeekViewEvent(1, getEventTitle(startTime), startTime, endTime);
        event.setColor(getResources().getColor(R.color.event_color_01));
        events.add(event);

        startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 6);
        startTime.set(Calendar.MINUTE, 0);
        startTime.set(Calendar.MONTH, newMonth - 1);
        startTime.set(Calendar.YEAR, newYear);
        endTime = (Calendar) startTime.clone();
        endTime.set(Calendar.HOUR_OF_DAY, 10);
        endTime.set(Calendar.MINUTE, 0);
        event = new WeekViewEvent(2, getEventTitle(startTime), startTime, endTime);
        event.setColor(getResources().getColor(R.color.event_color_04));
        events.add(event);

        startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 11);
        startTime.set(Calendar.MINUTE, 20);
        startTime.set(Calendar.MONTH, newMonth - 1);
        startTime.set(Calendar.YEAR, newYear);
        endTime = (Calendar) startTime.clone();
        endTime.set(Calendar.HOUR_OF_DAY, 12);
        endTime.set(Calendar.MINUTE, 0);
        event = new WeekViewEvent(3, getEventTitle(startTime), startTime, endTime);
        event.setColor(getResources().getColor(R.color.event_color_02));
        events.add(event);

        startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 13);
        startTime.set(Calendar.MINUTE, 20);
        startTime.set(Calendar.MONTH, newMonth - 1);
        startTime.set(Calendar.YEAR, newYear);
        endTime = (Calendar) startTime.clone();
        endTime.set(Calendar.HOUR_OF_DAY, 16);
        endTime.set(Calendar.MINUTE, 0);
        event = new WeekViewEvent(4, getEventTitle(startTime), startTime, endTime);
        event.setColor(getResources().getColor(R.color.event_color_01));
        events.add(event);

        return events;
    }

First two events are showing. remaining two events are not showing.

The third and fourth events should come under 2nd event.

**Comment by caske33** [comment]
Which version of the library are you using?

**Comment by kprathap23** [comment]
Latest version 
compile 'com.github.alamkanak:android-week-view:1.2.3

**Comment by caske33** [comment]
Does the sample app work for you? Because I can't see anything wrong with the code you posted.

**Comment by kprathap23** [comment]
Sample app working fine. I changed the dates according to my data and tested. But it doesn't work with my test data. Two events are missing.. Can you please check with my test data as I pasted above.

**Comment by caske33** [comment]
I think this might be a bug that's already fixed.

@lolobosse Didn't you have a similar problem?

**Comment by marunjar** [comment]
hi, just tried this with 1.2.4 and it seems to work fine

**Comment by kprathap23** [comment]
This bug fixed in new version 1.2.4. Thanks for everyone.
