### ISSUE TITLE
Removing the event

### ISSUE THREAD

**Issue by Swapnil-Garg16** [alamkanak/Android-Week-View#227]
When I click on an event to remove it ( using onEventClick) it removes the very first event I registered , then second and so on.

**Comment by caske33** [comment]
What are you doing exactly in your application?

(I'm closing this because I don't think it's a bug in the library. I'll reopen it if it turns out to be one)

**Comment by Swapnil-Garg16** [comment]
When I click on an empty cell , the event gets registered for that particular date and time. Now I want that when I click on the registered event , it should be removed. 

Code :  
package com.example.hp.newcalendar;

import android.content.DialogInterface;
import android.graphics.RectF;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;

import com.alamkanak.weekview.WeekView;
import com.alamkanak.weekview.WeekViewEvent;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class CalendarActivity extends AppCompatActivity implements WeekView.MonthChangeListener,WeekView.EmptyViewClickListener,WeekView.EventClickListener {

    private WeekView mWeekView;
    private ArrayList<WeekViewEvent> mNewEvents;
    private WeekView.EventClickListener mEventClickListener;
    String slots[] = new String[1000];
    int i = -1;
    String curr;
    int p;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_calendar);
        mWeekView = (WeekView) findViewById(R.id.weekView);
        mWeekView.setMonthChangeListener(this);
        mNewEvents = new ArrayList<>();
        mWeekView.setEmptyViewClickListener(this);
        mWeekView.setOnEventClickListener(this);
    }

    @Override
    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
        // Populate the week view with some events.
        List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();
        ArrayList<WeekViewEvent> newEvents = getNewEvents(newYear, newMonth);
        events.addAll(newEvents);
        return events;
    }

    private ArrayList<WeekViewEvent> getNewEvents(int year, int month) {

        // Get the starting point and ending point of the given month. We need this to find the
        // events of the given month.
        Calendar startOfMonth = Calendar.getInstance();
        startOfMonth.set(Calendar.YEAR, year);
        startOfMonth.set(Calendar.MONTH, month - 1);
        startOfMonth.set(Calendar.DAY_OF_MONTH, 1);
        startOfMonth.set(Calendar.HOUR_OF_DAY, 0);
        startOfMonth.set(Calendar.MINUTE, 0);
        startOfMonth.set(Calendar.SECOND, 0);
        startOfMonth.set(Calendar.MILLISECOND, 0);
        Calendar endOfMonth = (Calendar) startOfMonth.clone();
        endOfMonth.set(Calendar.DAY_OF_MONTH, endOfMonth.getMaximum(Calendar.DAY_OF_MONTH));
        endOfMonth.set(Calendar.HOUR_OF_DAY, 23);
        endOfMonth.set(Calendar.MINUTE, 59);
        endOfMonth.set(Calendar.SECOND, 59);

        // Find the events that were added by tapping on empty view and that occurs in the given
        // time frame.
        ArrayList<WeekViewEvent> events = new ArrayList<WeekViewEvent>();
        for (WeekViewEvent event : mNewEvents) {
            if (event.getEndTime().getTimeInMillis() > startOfMonth.getTimeInMillis() &&
                    event.getStartTime().getTimeInMillis() < endOfMonth.getTimeInMillis()) {
                events.add(event);

            }
        }
        return events;
    }

    @Override
    public void onEmptyViewClicked(final Calendar time) {

        curr = String.format("%02d:00 on %s/%d/%d", time.get(Calendar.HOUR_OF_DAY), time.get(Calendar.MONTH) + 1, time.get(Calendar.DAY_OF_MONTH), time.get(Calendar.YEAR));


                AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(
                        this);

                alertDialogBuilder.setTitle("Prompt");
                alertDialogBuilder
                        .setMessage("Mark " + curr + " as available ?");
                alertDialogBuilder.setCancelable(false);
                alertDialogBuilder.setPositiveButton("Yes", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        Log.d("tag2", "else");
                        i++;
                        Calendar endTime = (Calendar) time.clone();
                        slots[i] = curr;
                        // Toast.makeText(CalendarActivity.this, "" + slots[i], Toast.LENGTH_SHORT).show();

                        endTime.add(Calendar.HOUR_OF_DAY, 1);
                        WeekViewEvent event = new WeekViewEvent(20, "New event", time, endTime);
                        mNewEvents.add(event);
                        mWeekView.notifyDatasetChanged();
                    }
                });
                alertDialogBuilder.setNegativeButton("No", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        // if this button is clicked, just close
                        // the dialog box and do nothing
                        dialog.cancel();
                    }
                });

                // create alert dialog
                AlertDialog alertDialog = alertDialogBuilder.create();
               
                // show it
                alertDialog.show();
            }
    @Override
    public void onEventClick(final WeekViewEvent event, RectF eventRect) {
        AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(
                this);
        alertDialogBuilder.setTitle("Prompt");
        alertDialogBuilder
                .setMessage("Are you sure you want to remove this slot ?");
        alertDialogBuilder.setCancelable(false);
        alertDialogBuilder.setPositiveButton("Yes", new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialog, int id) {
                mNewEvents.remove(event);
                mWeekView.notifyDatasetChanged();
            }
        });
        alertDialogBuilder.setNegativeButton("No", new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialog, int id) {
                // if this button is clicked, just close
                // the dialog box and do nothing
                dialog.cancel();
            }
        });
        // create alert dialog
        AlertDialog alertDialog = alertDialogBuilder.create();
        // show it
        alertDialog.show();
    }
}

**Comment by caske33** [comment]
What's the behaviour you're seeing?

**Comment by Swapnil-Garg16** [comment]
Suppose I have registered 4 events. Now when I try to delete the last event or any event , deletion starts from the very first event registered i.e , If i click on the third event the first gets deleted . then if I click on the fourth event , the second one gets deleted ( Deletion is going on in serial manner , that is  , in the order in which the events were registered ) .

**Comment by caske33** [comment]
That's because you only have one id: `20`

You always remove the first event with the same id as given by the library...

See: https://github.com/alamkanak/Android-Week-View/blob/develop/library/src/main/java/com/alamkanak/weekview/WeekViewEvent.java#L133

**Comment by Swapnil-Garg16** [comment]
So how can I get different ID for different events ? So that only those will be deleted which are clicked.

**Comment by caske33** [comment]
- have a global counter that is incremented every time you add an event
- use a random variable (if the range is large enough, no collisions should occur)

**Comment by anandraj16992** [comment]
I am updating weekview on resume of activity . But it shows same event multiple time with same name. So how to reset weekview ? So I can update event everytime without this multiple issue.
