### ISSUE TITLE
goToDate

### ISSUE THREAD

**Issue by Harrison-Miller** [alamkanak/Android-Week-View#23]
Using the goToDate function doesn't seem to work as intended. For example:
Calendar myDate = Calendar.getInstace();
myDate.set(Calendar.DATE, 5);
myDate.set(Calendar.MONTH, 1);
mWeekView.goToDate(myDate);
Results in the equivalent of calling goToToday().
I've gotten some success from doing the following: myDate.add(Calendar.Date, x)
However this doesn't seem to work for anything beyond the current month.

**Comment by caske33** [comment]
@alamkanak This problem should be fixed and this can be closed.

**Comment by Hugo-Pereira** [comment]
this doesn't work for me.
I checked and mWidthPerDay is 0 when the goToDate is called

**Comment by caske33** [comment]
@Hugo-Pereira my PR #53 will fix that

**Comment by alamkanak** [comment]
Problem fixed. See #69

**Comment by hpdeveloper88** [comment]
Do a single and very simple change:

Replace this
mRefreshEvents = true;

with
mRefreshEvents = false;

Method goToDate(Calendar date) should looks like:

    public void goToDate(Calendar date) {
        mScroller.forceFinished(true);
        date.set(Calendar.HOUR_OF_DAY, 0);
        date.set(Calendar.MINUTE, 0);
        date.set(Calendar.SECOND, 0);

        mRefreshEvents = false;

        Calendar today = Calendar.getInstance();
        today.set(Calendar.HOUR_OF_DAY, 0);
        today.set(Calendar.MINUTE, 0);
        today.set(Calendar.SECOND, 0);

        int dateDifference = (int) (date.getTimeInMillis() - today.getTimeInMillis()) / (1000 * 60 * 60 * 24);
        mCurrentOrigin.x = - dateDifference * (mWidthPerDay + mColumnGap);

    	
        invalidate();
    }
