### ISSUE TITLE
Want to enable the click only for 4-5 cells

### ISSUE THREAD

**Issue by Swapnil-Garg16** [alamkanak/Android-Week-View#233]
I want that in this weekview , 15th dec 4 00-5 00 am , 17th dec 17 00-18 00 pm can be clicked . Rest of all cant be clicked. How can I do this ?

**Comment by caske33** [comment]
Just ignore the other events, or handle them seperatly?

(use the emptyviewClickListener or eventClickListener, depending on what you want to do)
