### ISSUE TITLE
Future- and pastWeekendBackgroundColor

### ISSUE THREAD

**Issue by Sadek93** [alamkanak/Android-Week-View#234]
Hey hey,

I'm rly liking your library, currently using it for my universities schedule app.

Sadly the named attributes aren't working for me. I dont now why, I can set showDistinctWeekendColor  and the color in my layout but it doesnt change anything and I can't find any Method to set them with my weekView object.

**Comment by caske33** [comment]
getter `isShowDistinctWeekendColor`, setter `setShowDistinctWeekendColor`

You have to set the `showDistinctPastFutureColor` option to true as well though. Potentially setting `futureBackgroundColor` and `pastBackgroundColor` to the same color if you only want the weekend behaviour.
