### ISSUE TITLE
onEmptyViewClicked not firing

### ISSUE THREAD

**Issue by ToddManUtah** [alamkanak/Android-Week-View#240]
I've implemented this view in a fragment and it's AWESOME!!!  Great job everyone.

I'm having a problem with the onEmptyViewClicked method.  For some reason, it's not firing.  My fragment implements WeekView.EmptyViewClickListener.  

Other events like onEventClick are working great.  

Any ideas?

**Comment by caske33** [comment]
Does the longpress work?

**Comment by ToddManUtah** [comment]
Nope.  I thought the 2 might be tied together.  So I tried it and got the same problem.

**Comment by ToddManUtah** [comment]
I just changed the sample project and got the same result.  Empty click events (long and short) don't work.

**Comment by caske33** [comment]
Hmm, does it work in earlier versions? Because if not really tried it yet. Maybe it got broken by accident in the latest version.

**Comment by ToddManUtah** [comment]
I just started using the library.  I haven't tried earlier version.

**Comment by caske33** [comment]
This is indeed a problem. However I don't have the time to fix this right now. @marunjar can you maybe take a look?

**Comment by marunjar** [comment]
ok, i'll take a look, maybe tomorrow...

**Comment by marunjar** [comment]
i just added the onEmptyViewLongPress to the sample app for debugging (#245) but i works fine for me. 
Just tried it with 1.2.4 and develop branch on some avds and also on real devices. Zoomed in and out and also from day view to full week view.

@ToddManUtah Do i miss something? Do you have any additional infos or some code, e.g. of your changed sample project?

**Comment by caske33** [comment]
(I'm gonna close this until @ToddManUtah confirms there is still a problem).

**Comment by ToddManUtah** [comment]
I'm still seeing the problem. I'm using  a Nexus 9 running Marshmallow. The problem is easily reproduced using the sample project. I'm using the latest release of the code. Both short and long touch in empty space produces no event. Is there something you want me to try?

**Comment by ExtinctAmoeba** [comment]
Is there any fix for this issue?

**Comment by entropitor** [comment]
@ExtinctAmoeba Can you check if this problem is also present in the [Quivr-fork](https://github.com/Quivr/Android-Week-View)?

And if so, can you add some steps to reproduce this error? Because I can't reproduce this error.

**Comment by ExtinctAmoeba** [comment]
@caske33 yes, [Quivr](https://github.com/Quivr/Android-Week-View) fork works good. Thank You, I will look for code differences.

**Comment by entropitor** [comment]
@ExtinctAmoeba I suggest to just start using the Quivr-fork. I will be no longer doing any work on this repository and the only other official contributor to this repository is @alamkanak, who has been inactive for a long time now.
