### ISSUE TITLE
unable to add events though i am able to Async data 

### ISSUE THREAD

**Issue by tanve** [alamkanak/Android-Week-View#241]
my code is 
    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
        // Populate the week view with some events.
        List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();

        HashMap<Integer,WeekeventsModel> Pevent = null;

        try {
            Pevent =    new EventMap(newMonth,newYear).execute().get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }

        int size = Pevent.size();
        for(int i = 0 ; i < size ; i++)
        {
            if(Pevent.containsKey(i)){
                WeekeventsModel Wevents = eventsmap.get(i);
                String datestr = Wevents.getStartdate();
                String dateend = Wevents.getEndDate();
                String title  = Wevents.getTitle();
                String[] parts = datestr.split("T");
                String part1 = parts[0]; // 004
                String part2 = parts[1];
                String part3 = part1+" "+part2;
                String[] Penddate = dateend.split("T");
                String Pe1 = Penddate[0];
                String Pe2 = Penddate[1];
                String Pe3 = Pe1+" "+Pe2;

                SimpleDateFormat parseur = new SimpleDateFormat("MM-dd-yyyy hh:mm:ss");
                Date EventDate = null,EventendDate = null;
                try {

                    EventDate = parseur.parse(part3);
                    EventendDate = parseur.parse(Pe3);
                    Calendar startTime = Calendar.getInstance();
                    startTime.setTime(EventDate);
                    int year = startTime.get(Calendar.YEAR);
                    int month = startTime.get(Calendar.MONTH);
                    int day = startTime.get(Calendar.DAY_OF_MONTH);
                    int hour = startTime.get(Calendar.HOUR_OF_DAY);
                    int minute = startTime.get(Calendar.MINUTE);
                    startTime.set(Calendar.DAY_OF_MONTH,day);
                    startTime.set(Calendar.MONTH, month - 1);
                    startTime.set(Calendar.YEAR, year);
                    startTime.set(Calendar.HOUR_OF_DAY, hour);
                    startTime.set(Calendar.MINUTE, minute);
                    Calendar Enddates = Calendar.getInstance();
                    Enddates.setTime(EventendDate);
                    int Eyear = Enddates.get(Calendar.YEAR);
                    int Emonth = Enddates.get(Calendar.MONTH);
                    int Eday = Enddates.get(Calendar.DAY_OF_MONTH);
                    int Ehour = Enddates.get(Calendar.HOUR_OF_DAY);
                    int Eminute = Enddates.get(Calendar.MINUTE);
                    Enddates.set(Calendar.DAY_OF_MONTH,day);
                    Enddates.set(Calendar.MONTH, month - 1);
                    Enddates.set(Calendar.YEAR, year);
                    Enddates.set(Calendar.HOUR_OF_DAY, hour);
                    Enddates.set(Calendar.MINUTE, minute);
                    WeekViewEvent event = new WeekViewEvent(1, getEventTitle(title), startTime, Enddates);
                    event.setColor(getResources().getColor(R.color.event_color_01));
                    events.add(event);

                } catch (ParseException e) {
                    e.printStackTrace();
                }

            }

        }
return events;
}
 i am unable to get events on calendar though getting data and binding them to events list

**Comment by caske33** [comment]
Have you taken a look at https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158 yet?

I think it's better to have the asynctask not in your onMonthChange-method.
