### ISSUE TITLE
Get more events

### ISSUE THREAD

**Issue by linhlq58** [alamkanak/Android-Week-View#249]
I only get events in the first week of month when using setOnMonthChangeListener. Is there any way to get events in whole month?

**Comment by caske33** [comment]
What do you mean exactly you only get events in the first week of the month? You have to provide the events.

**Comment by linhlq58** [comment]
Calendar startTime = Calendar.getInstance();
                startTime.set(Calendar.DAY_OF_WEEK, Calendar.TUESDAY);
                startTime.set(Calendar.HOUR_OF_DAY, 0);
                startTime.set(Calendar.MINUTE, 0);
                startTime.set(Calendar.MONTH, newMonth - 1);
                startTime.set(Calendar.YEAR, newYear);
                Calendar endTime = (Calendar) startTime.clone();
                endTime.set(Calendar.HOUR_OF_DAY, 3);
                endTime.set(Calendar.MONTH, newMonth - 1);
                WeekViewEvent event = new WeekViewEvent(1,
                        "Đường lối cách mạng của ĐCSVN \n B2-HT4", startTime, endTime);
                event.setColor(getResources().getColor(R.color.event_color_01));
                events.add(event);
I set this event on Tuesday. But it only appear once per month.

**Comment by caske33** [comment]
Yes, Calendar.getInstance() gets a calendar with the date set to today. Since you don't change it, except for the DAY_OF_WEEK, it will be on the tuesday of this week. If you want to repeat events, you'll have to do so yourself before providing them to the library.
