### ISSUE TITLE
Need to place a Date Picker.

### ISSUE THREAD

**Issue by Shivamkamat94** [alamkanak/Android-Week-View#253]
Dear sir,
I would like to place a date picker before launching the basicActivity.java , where do i set the starting date for the Week-View.

ps- great Lib, helped a lot..

**Comment by entropitor** [comment]
I guess you can set the date picker in the MainActivity and pass the date along to the basic activity in the intent?

**Comment by Shivamkamat94** [comment]
yes, but i cant find the function in BasicActivity.java to which the date is to be passed, so that it loads from that date .. can u please help out.

**Comment by entropitor** [comment]
you can call `mWeekView.goToDate()`
