### ISSUE TITLE
Events disappear if they span more hours then what is showing in the view

### ISSUE THREAD

**Issue by karbar09** [alamkanak/Android-Week-View#26]
Hello,

I have to display a bunch of events that are long. However, those events seem like they're drawn only when the start_time and end_time for the event can be contained within the view. 

So, below is a screenshot of the events "before scrolling down" ( my guess: start_time and end_time are visible to the user, so, these events are drawn): 
![android_week_view_before](https://cloud.githubusercontent.com/assets/3309996/5241524/5f968cf0-795a-11e4-8ba9-a3ddcb4def68.png)

and "after scrolling down" (scrolled a little bit past 11, to 11:30ish, which is after the start_time. at this point, I think WeekView.drawEvents(..) is called, and some of the events are not re-drawn,  aside from the lone event which begins around 16:00, and lasts for an hour):

![android_week_view_after](https://cloud.githubusercontent.com/assets/3309996/5241523/5f90766c-795a-11e4-9849-1218b1e55cc8.png)

Rather than having the event rectangles disappear, i would like as much of the event as possible to be drawn within the displayed time. Hope the explanation of my issue is clear. Do you know how i can get this to work? 

Thank you,
Karthik

**Comment by caske33** [comment]
@karbar09 Does this still happen in version 1.2.5 of the library?

(I'm going to close this, but if it's still a problem, just reopen it)
