### ISSUE TITLE
Rendering bug in version 1.2.6

### ISSUE THREAD

**Issue by dukerok** [alamkanak/Android-Week-View#262]
Hello, great job, i am pleased to use and look at your library live and improve.

More precisely, i use your library until last 3 updates. And find one annoying bug(with drawing, look at screenshots) after last update (in version 1.2.6)
Bug constantly reproduced in samsung galaxy tab s (android 4.4.2), it`s my target device. Also i tried to reproduce him on another devices
(Sony Xperia z3 android 5.0 and Sony Xperia z Android 4.4.4), but on this devices all work correctly.

I tried to use previous version of library (using Gradle) :
- add  compile 'com.github.alamkanak:android-week-view:1.2.4'. All work correctly, bug doesn`t appear.
- add  compile 'com.github.alamkanak:android-week-view:1.2.5'. Can`t compile because of : "Could not find com.github.alamkanak:android-week-view:1.2.5"

Steps to reproduce the bug.
1. Device - samsung galaxy tab s (android 4.4.2);
2. Create new project with navigation drawer activity (minsdk 14);
3. add  compile 'com.github.alamkanak:android-week-view:1.2.6'
4. create layout

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:tools="http://schemas.android.com/tools"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:paddingLeft="@dimen/activity_horizontal_margin"
            android:paddingRight="@dimen/activity_horizontal_margin"
            android:paddingTop="@dimen/activity_vertical_margin"
            android:paddingBottom="@dimen/activity_vertical_margin"
            tools:context=".CategoryActivity$PlaceholderFragment">

<com.alamkanak.weekview.WeekView
    android:id="@+id/weekView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:eventTextColor="@android:color/black"
    app:textSize="12sp"
    app:hourHeight="60dp"
    app:headerColumnPadding="8dp"
    app:headerColumnTextColor="#8f000000"
    app:headerRowPadding="12dp"
    app:hourSeparatorColor="#808080"
    app:columnGap="8dp"
    app:noOfVisibleDays="7"
    app:showDistinctPastFutureColor = "true"
    app:futureBackgroundColor = "#1500FF00"
    app:pastBackgroundColor = "#0800ff00"
    app:showDistinctWeekendColor ="true"
    app:futureWeekendBackgroundColor = "#15ff0000"
    app:pastWeekendBackgroundColor = "#15ff0000"
    app:headerRowBackgroundColor="#ffefefef"
    app:showNowLine = "true"
    app:nowLineColor = "#aa0000ff"
    app:headerColumnBackground="#ffffffff"/> 
```

</RelativeLayout>
5.  add monthlistener.
6. All work as expected until to slide navigation drawer (look at screenshots);

I appreciate any suggestion on resolving this problem.

// Normal state
![normal state](https://cloud.githubusercontent.com/assets/16688105/12323651/516bea60-bace-11e5-9d49-a71248356e13.png)

// Buggy state after slide navigation drawer
![bug state](https://cloud.githubusercontent.com/assets/16688105/12323650/516b2c74-bace-11e5-897f-d909251e66b7.png)

**Comment by entropitor** [comment]
Is it possible this has to do with your navigation drawer instead of the library?

The only thing I can think of that has changed is the transparancy @marunjar implemented.

**Comment by dukerok** [comment]
Hi, caske ! Thanks for quick answer!

I use the same drawer as used before update to version 1.2.6, and after update the bug begin
to appear (with version 1.2.4 this drawer work fine).
Navigation drawer is generated by Android Studio when create new Navigation Drawer Activity.

I find several workarounds as works for me:
1. disabling Hardware Acceleration for layout fix problem,  but view become to slow;
2. ListView xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:tools="http://schemas.android.com/tools"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   android:choiceMode="singleChoice"
   android:divider="@android:color/transparent"
   android:dividerHeight="0dp"
   android:background="#cccc"
   tools:context=".NavigationDrawerFragment" />

Changing background of drawer from #cccc to #ccc (removing alfa) fix the problem.

Yes, i can use this workaround, but it force me to ignore some design requirements.
Maybe we can together find the root of the problem, to fix it?

**Comment by entropitor** [comment]
If you're navigation drawer has transparancy, isn't it normal that the view below it is displayed?

**Comment by dukerok** [comment]
Maybe i don`t precisely describe the problem.

The main 2 problems is :
1. WeekView drawing above the Drawer.
2. The colors become extremely bright.

Please see the screenshots:

The behaviour that i expect to see (i get it using workaround):
![expected](https://cloud.githubusercontent.com/assets/16688105/12326497/35a5a352-bae2-11e5-9d13-5d58fa0e54df.png)

Incorrect behaviour that i have:
![real](https://cloud.githubusercontent.com/assets/16688105/12326507/3c313aec-bae2-11e5-9cd5-64df33fa2dc9.png)

**Comment by entropitor** [comment]
@dukerok It seems to me that the WeekView is drawn below the navigation drawer. But because the navigation drawer is transparent, you can still see the weekview?

As you can see, 1/12 is less bright than 1/13, because it's behind the (transparent) navdrawer.

**Comment by CAPAKAU** [comment]
I've got kind of similar bug while I'm clicking a view in my navigation drawer.
The WeekView becomes brighter and shows over the navigation drawer.

The navigation drawer has aplha and everythings good till I don't click anything 
![screenshot_2016-02-23-16-18-41](https://cloud.githubusercontent.com/assets/14807886/13256070/79b558d6-da49-11e5-8675-18d0e0bf80e5.png)
![screenshot_2016-02-23-16-19-16](https://cloud.githubusercontent.com/assets/14807886/13256071/79b836a0-da49-11e5-911e-5c4924b09dae.png)

**Comment by CAPAKAU** [comment]
Is there anything I could do to prevent from that behaviour ?

Thanks.

**Comment by CAPAKAU** [comment]
So I checked on different version of Android OS and it seems this behaviour only appears on 
Lolipop 5.1.1
I also tested with 5.0.1 and 5.1 : everything were fine.

**Comment by entropitor** [comment]
Then it seems to me it's a bug in Android 5.1.1 instead of the library?

**Comment by CAPAKAU** [comment]
Sadly, It might be the best answer 
Tests were made on Samsung devices with 5.1.1(GS6)/5.0.1(GS4) and on a Wiko Fever with 5.1 OS.

**Comment by dukerok** [comment]
> Bug constantly reproduced in samsung galaxy tab s (android 4.4.2)

**Comment by CAPAKAU** [comment]
I have the same bug on Android Marshmallow, I don't know what's the problem

**Comment by CAPAKAU** [comment]
Finally found some element : I was using alpha (0.85) on the android.support.design.widget.NavigationView and a background color with alpha (#A0000000). 
So now that I don't use alpha (#000) for the background it's working fine everywhere...

**Comment by FEYZAN** [comment]
It seems that we have to give background to NavigationView to get rid of this problem as @CAPAKAU says. When we give background problem has solved.

**Comment by dukerok** [comment]
in my case, it`s not a single problem with transparency...
