### ISSUE TITLE
Default dateTimeInterpreter should be based on current Locale.

### ISSUE THREAD

**Issue by MaciejCzekanski** [alamkanak/Android-Week-View#263]
Currently date format is "EEEEE M/dd" which is different from one used eg. in Europe. I suggest replacing creating custom SimpleDateFormat with default one:
DateFormat.getDateInstance(int style, Locale locale)

The same goes for time format.

**Comment by entropitor** [comment]
You can change the dateTimeInterpreter to your needs, no?

**Comment by MaciejCzekanski** [comment]
Sure, but why not use default format which works for all countries?

**Comment by entropitor** [comment]
If you create a Pull Request, I can merge it.

Will it still use the "EEEE M/dd" format for Americans?

**Comment by MaciejCzekanski** [comment]
Ok, from what I see, all styles in DateFormat.getDateInstance contain year, which we want to omit.

I could try using:
int flags = DateUtils.FORMAT_ABBREV_WEEKDAY | DateUtils.FORMAT_SHOW_DATE | DateUtils.FORMAT_NO_YEAR;
String monthAndDayText = DateUtils.formatDateTime(context, date, flags);

it should give us day and month formatted according to current user's locale.

I'll test it in coming days and create a pull request if it uses the same format for US.

**Comment by entropitor** [comment]
Okay :)
