### ISSUE TITLE
Date time format 

### ISSUE THREAD

**Issue by hadiarakos** [alamkanak/Android-Week-View#264]
Hello and thank you for you awesome library. 
Can you specify date time format that i have to provide to the web service? 

{
                       "name" : "Test event",
                       "dayOfMonth" : "10"
                       "startTime" : "2016-12-10 12:00:00"
                       "endTime" : "2016-12-10 12:00:00",
                       "color": "#c0c0c0"
                     }
Am i missing something ? 

Thank you again .

**Comment by entropitor** [comment]
You can take a look in the sample app that is in this repository for how to provide events.
