### ISSUE TITLE
How to add multiday event with horizontal highlighting event columns?

### ISSUE THREAD

**Issue by pratiksharma821** [alamkanak/Android-Week-View#265]
Hi,

This is really a cool and helpful library I found. My requirement is to add multiday event in weekview. Like from 1st January to 3rd January, so there will 3 columns will be highlight horizontally and not all vertical highlighting for all hours.

See the attached image for better understanding.

Thanks
![week_view](https://cloud.githubusercontent.com/assets/16641944/12411069/2109f7e6-bea1-11e5-924a-a484a7ed8b6c.png)

**Comment by entropitor** [comment]
This is currently not possible. And I'm not sure if we're willing to maintain that kind of feature as most people won't need it. That's why I'm gonna close this issue.

However, the library is rather small, and hopefully you'll be able to modify the library for your needs.
