### ISSUE TITLE
Cannot resolve symbol 'MonthChangeListener'

### ISSUE THREAD

**Issue by N7Nico** [alamkanak/Android-Week-View#282]
Hi,
While I was following the little tutorial on your README.md and at step 4 I encounter the following error by Android Studio "Cannot resolve symbol 'MonthChangeListener'"...
I integrated the library via gradle,

![2016-02-11 2](https://cloud.githubusercontent.com/assets/7013468/12984222/15150e04-d0ed-11e5-8b1e-642bb1a09395.png)

the xml, the listeners of step 3 and while implementing WeekView.MonthChangeListener android don't recognize it...

![2016-02-11 1](https://cloud.githubusercontent.com/assets/7013468/12984186/eaa46dcc-d0ec-11e5-909b-ee2a889ebda5.png)

By the way it's impossible for me to find a solution on Google...

Thanks in advance for your answer.

Nicolas.

**Comment by entropitor** [comment]
It needs to be MonthLoader.MonthChangeListener nowadays.

**Comment by N7Nico** [comment]
I figured it out finally. Thank by the way.
