### ISSUE TITLE
Change day title and disable horizontal scrolling

### ISSUE THREAD

**Issue by shilch** [alamkanak/Android-Week-View#287]
Hi, I have two questions:

<ul>
<li>how to change the day title to a custom value?</li>
<li>How can I disable swiping between the days?</li>
</ul>

Thank you in advance!

**Comment by shilch** [comment]
ok, second I solved using `app:xScrollingSpeed="0.0"`

**Comment by entropitor** [comment]
for the first: `mWeekView.setDateTimeInterpreter()`

**Comment by shilch** [comment]
thank you
