### ISSUE TITLE
Change month changed event to specific range

### ISSUE THREAD

**Issue by bennythomps** [alamkanak/Android-Week-View#29]
I want to use this library, but can't quite yet because I only have one day (at most one week) of event data available.  I should be able to supply only days within the context of the view.

**Comment by caske33** [comment]
So you want to disable (horizontal) scrolling past a certain day?

**Comment by Morgan2cc** [comment]
Yes. Past and previous.

**Comment by Vlaoff** [comment]
Any news on that ? All others issues redirect to this one, but there is no answer there. 

I need to limit scrolling back to the current date (so user can't view past dates). Is this possible or need to be implemented?

**Comment by caske33** [comment]
This needs to be implemented still

**Comment by caske33** [comment]
Closing in favor of #6
