### ISSUE TITLE
Triplet events

### ISSUE THREAD

**Issue by elsalakk** [alamkanak/Android-Week-View#291]
I have this weird issue were every event is displayed 3 times on the same time slot, basically I use this in combination with a month view I get the event day, start time, end time, month year, from the month view push it to an array, then load it into week view. It works fine, except each event shows 3 times.
![2016-03-07](https://cloud.githubusercontent.com/assets/16761766/13574757/2414ed90-e44b-11e5-8d70-787f18899bde.png)

here is the code:

public List<? extends WeekViewEvent> onMonthChange(int newYear, int newMonth) {
        List<WeekViewEvent> eventsWeek = new ArrayList<WeekViewEvent>();
        Calendar startTime;
        Calendar endTime;

```
    for (int x = 0; x < prgData.eventCounter; x++) {
        startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, prgData.events.get(x).startTime);
        startTime.set(Calendar.MINUTE, 0);
        startTime.set(Calendar.DAY_OF_MONTH, prgData.events.get(x).day);
        startTime.set(Calendar.MONTH, prgData.events.get(x).month-1);
        startTime.set(Calendar.YEAR, prgData.events.get(x).year);
        endTime = (Calendar) startTime.clone();
        endTime.add(Calendar.HOUR, prgData.events.get(x).endTime);
        endTime.set(Calendar.MONTH, prgData.events.get(x).month-1);
        WeekViewEvent event = new WeekViewEvent(prgData.eventCounter, prgData.events.get(x).eventName, startTime, endTime);
        Random rnd = new Random();
        int color = Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256));
        event.setColor(color);
        eventsWeek.add(event);
    }


    return eventsWeek;
}
```

Help much appreciated! P.S. The array contains the correct amount of events, no duplicates.

**Comment by entropitor** [comment]
#81

**Comment by elsalakk** [comment]
You are a life saver. Thank You!!
