### ISSUE TITLE
Event problem

### ISSUE THREAD

**Issue by hova4** [alamkanak/Android-Week-View#294]
I'm trying to add an event, but my event was not displayed
What's wrong? Please help me, good people

This is my java code `

```
        List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();
        Calendar startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 3);
        startTime.set(Calendar.MINUTE, 0);
        startTime.set(Calendar.MONTH, newMonth - 1);
        startTime.set(Calendar.YEAR, newYear);
        Calendar endTime = (Calendar) startTime.clone();
        endTime.add(Calendar.HOUR, 1);
        endTime.set(Calendar.MONTH, newMonth - 1);
        WeekViewEvent event = new WeekViewEvent(1, getEventTitle(startTime), startTime, endTime);
        event.setColor(getResources().getColor(R.color.event_color_01));
        events.add(event);
    }
```

And in general please tell me, how do I add events? It is necessary to see how events looks, then to organize everything from the server

**Comment by hova4** [comment]
And in general please tell me, how do I add events? It is necessary to see how events looks, then to organize everything from the server

**Comment by entropitor** [comment]
are you calling mWeekView.notifyDatasetChanged() after you received events from the server?

**Comment by hova4** [comment]
Now i want it local, not from server. How shoud i do that ?

**Comment by entropitor** [comment]
Have you looked at the sample in the repository?

**Comment by hova4** [comment]
Thanks a lot! i've solved my problem! Thanks fo the awesome library!
