### ISSUE TITLE
Customize Hours Time Line

### ISSUE THREAD

**Issue by ZainabMohd** [alamkanak/Android-Week-View#295]
Hi there,

I want to limit the WeekView hours to show events foe instance only from 8 am to 4 pm only ?

also hoe to customize the event slot by adding more views to it ? and is there anyway to control swiping between days grammatically ?

I'd appreciate your help,

**Comment by entropitor** [comment]
I think all these are covered in previous issues. All of them are still open. Gonna close this in favor of the others.
