### ISSUE TITLE
onMonthChange gets called many times 

### ISSUE THREAD

**Issue by HiradRoshandel** [alamkanak/Android-Week-View#296]
I'm using this WeekView in my fragment and my events keep getting duplicated because onMonthChange getting called many times! Can any one help me with this issue? This is my onMonthChnage listener:

```
public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {

    if (events.size() <= 0 ) {
        updateSchedule();
        return new ArrayList<WeekViewEvent>();
    }


    return events;

}
```

updateSchedule calls  `mWeekView.notifyDatasetChanged();` when the data is fetched from api.
I even tried it with static data in the sample file. It gets called 3-4 times. And yes onCreateView in my fragment is getting called only once! Is it possible to use this in a fragment?

**Comment by entropitor** [comment]
See #81

**Comment by HiradRoshandel** [comment]
thanks! I followed your AsynchronousActivity.java example and it fixed the issue.
