### ISSUE TITLE
onMonthChange is called on user thread?

### ISSUE THREAD

**Issue by Zapnologica** [alamkanak/Android-Week-View#304]
How can I make an async or network call in this call back?

The issue is, this override requires me to return a list of the actually events. Is there anyway that I can use an asynctask to fetch the events from web service and then set them once its done?

I almost feel as if these callbacks should be called in different threads by the library?

**Comment by entropitor** [comment]
See https://github.com/alamkanak/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/AsynchronousActivity.java
