### ISSUE TITLE
onMonthChange(int newYear, int newMonth)

### ISSUE THREAD

**Issue by Zapnologica** [alamkanak/Android-Week-View#306]
Good day,

I decided to use this library for one of my projects. So far it works great.
I have one issue though. The `onMonthChange(int newYear, int newMonth)` change listener.
Now this event is A: not called in a different thread and B: it has to return a list of events.

in my case these events are accessed via a web call on an API.  Which is where my problem comes about.
- You cant make web requests on the UI thread
- I cant make an async network request because then how do I return the List of events, and the re is no otherway to set them.

This go me thinking. Design wise the following would be a better technique.

In my mind, the `onchange listener` should only be there to inform that a change has happened. it should not be the means of getting raw data.

There should be an underlying adapter that sits under the calendarView, and there should be functions and callbacks that make the adapter accessible to the inheriting class. Basically how recycler view and list view work.

here is my idea of the work flow:
1. OnMonthChanged listener is called   (could be changed to on day, on week etc for more customization).
2. Fire off async request to get data from web services, or SQLlite etc.
3. Set the data for the adapter,  mWeekView.setEvents(List<? extends WeekViewEvent> events, time paramters)

An alternative would be that, if you want data and notification to happen at the same time, then you need to make the `onMonthChanged` into a callback and then execute it on a different thread that is handled by the library?

Please let me know on 1: how I can do a quick work around for my issue and then B: comment on my design suggestion.

**Comment by entropitor** [comment]
see sample app AsyncActivity (this github repo).

We have a Loader class, you can have your own implementation of it that follows your design, if you want. Feel free to contribute that back through a Pull Request and we'll take a look then whether or not it's something we want in the library for everyone to use.
