### ISSUE TITLE
Issue with the java file

### ISSUE THREAD

**Issue by Konbuscus** [alamkanak/Android-Week-View#308]
Hello, I'm new to Android, and i'm needing some help to solve this issue, I can't understand why
i'm getting this error "cannot resolve symbol mWeekView" if anyone have the answer, it would be appreciated.

Thanks.

Here is a screenshot : 

![pedro](https://cloud.githubusercontent.com/assets/9660713/14678875/ccbd23d8-0717-11e6-984b-c00c30b18467.PNG)

EDIT : even with the implements, still getting this error

**Comment by entropitor** [comment]
you need to declare a mWeekView field in your activity. See the sample code in the github repo for a sample activity.
