### ISSUE TITLE
NestedScrollView support?

### ISSUE THREAD

**Issue by danielflores108** [alamkanak/Android-Week-View#309]
Hi!
How I can put in "NestedScrollView" and "CoordinatorLayout"?
Not showing.
If use android:fillViewport="true" no scrolling

**Comment by entropitor** [comment]
How would you expect this to work?

(I'm closing this because I don't think it's a bug but will reopen it if I'm wrong)

**Comment by mr-sarsarabi** [comment]
this should actually work. as the name says, it's nested scrolling and can be handled in onInterceptTouchEvent. please open this issue.
