### ISSUE TITLE
Customize week view by date and user

### ISSUE THREAD

**Issue by Jim25** [alamkanak/Android-Week-View#311]
Hello, this is really great library.

I have to make a screen that has calendar events group by days and user like the attach image.

Is there any chance to customize this lib?

Thanks in advance.
![screenshot_2016-04-29-16-44-19](https://cloud.githubusercontent.com/assets/3830423/14913135/fa419c52-0e2a-11e6-9ae4-a3f6e8cf1c5d.png)

**Comment by entropitor** [comment]
You can always customize the library yourself for this. The library is not that ibg. 

This is not something we'll support though.
