### ISSUE TITLE
How to define a event duration 

### ISSUE THREAD

**Issue by jcmartins** [alamkanak/Android-Week-View#312]
I would define a event time duration see exemple below:

12:00
12:45
13:00
13:45
14:00
14:45

**Comment by hova4** [comment]
i want to know it too

**Comment by entropitor** [comment]
I'm not getting the question?

(I'm closing this, because it's not a bug in the library. But feel free to explain a bit more)

**Comment by jcmartins** [comment]
It's not a bug maybe a feature? 
I would like to configure/set the interval time not full hour (60min) 
suppose 45minutes  
12:00
Soccer
12:45
NBA
13:30
NFL
14:15
suppose 120min
12:00
Soccer
14:00
NBA
16:00
NFL
18:00

**Comment by entropitor** [comment]
You can just have events that have the appriopiate start and end time?

**Comment by jcmartins** [comment]
I have an event each 45minutes and I like to show it.

**Comment by entropitor** [comment]
Have you taken a look at the sample application?
