### ISSUE TITLE
Hour 0-23

### ISSUE THREAD

**Issue by niqt** [alamkanak/Android-Week-View#329]
Hi,
is possible have the hour day in the format 00:00 - > 23:00 without AM/PM ?

**Comment by issa-h** [comment]
Hi, you can override the methode setupDateTimeInterpreter like this:

`private void setupDateTimeInterpreter(final boolean shortDate) {
        mWeekView.setDateTimeInterpreter(new DateTimeInterpreter() {
            @Override
            public String interpretDate(Calendar date) {
                SimpleDateFormat weekdayNameFormat = new SimpleDateFormat("EEEE", Locale.FRANCE);
                String weekday = weekdayNameFormat.format(date.getTime());
                SimpleDateFormat monthNameFormat = new SimpleDateFormat("MMMM", Locale.FRANCE);
                String month = monthNameFormat.format(date.getTime());
                SimpleDateFormat yearNameFormat = new SimpleDateFormat("yyyy", Locale.FRANCE);
                String year = yearNameFormat.format(date.getTime());
                SimpleDateFormat dayNumberFormat = new SimpleDateFormat("d", Locale.FRANCE);
                String dayNumber = dayNumberFormat.format(date.getTime());

```
            return weekday.substring(0, 1).toUpperCase() + weekday.substring(1)
                    +" "
                    +dayNumber
                    +" "+
                    month.substring(0, 1).toUpperCase() + month.substring(1)
                    +" "
                    +year;
        }

        @Override
        public String interpretTime(int hour) {
            if(hour<10){
                return "0"+hour+":00";
            }
            else{
                return hour+":00";
            }
        }
    });
}`
```

**Comment by issa-h** [comment]
The important is:

`@Override
        public String interpretTime(int hour) {
            if(hour<10){
                return "0"+hour+":00";
            }
            else{
                return hour+":00";
            }
        }`

**Comment by niqt** [comment]
Thanks
