### ISSUE TITLE
An option to show only the days (Sunday - Saturday) and the timetable, and no dates.

### ISSUE THREAD

**Issue by anobilisgorse** [alamkanak/Android-Week-View#330]
So I am developing an Android app version of our campus student portal.

So there exists a feature that shows the "schedule" of classes one student has, and it looks like this in the web app equivalent:

![sched](https://cloud.githubusercontent.com/assets/8383878/15627039/be8958b2-2509-11e6-86b2-34a9896377d9.png)

Also because the whole timetable seems to be space costly, it would be very efficient that the view instead shows a timetable for one day only, then upon scrolling left or right, it navigates to other days.

This library came close to the feature, there's a week view where it limits to show only one day within a viewport, but it still shows the date, which is very unnecessary. Is it possible to do such thing with this library?

Here's how my app looks like with your library.

![weekview](https://cloud.githubusercontent.com/assets/8383878/15627043/f1b6f38e-2509-11e6-9c17-7acb191e5136.png)

**Comment by entropitor** [comment]
There are other issues for this already.

**Comment by anobilisgorse** [comment]
What issue numbers exactly @caske33? Please state explicitly.
