### ISSUE TITLE
Overlapping event

### ISSUE THREAD

**Issue by vamidi** [alamkanak/Android-Week-View#336]
Hi there everyone,

I have an issue with my application. I download events from the server to my application and then call the onmonthchange event. Only when I do that I get overlapping events. I know that Ionchangemonth is called three times, but I looked at the sample code for getting matches on the month and year events. Hope this is not a duplicate that has been made many times

![screenshot_20160610-180305](https://cloud.githubusercontent.com/assets/10434772/15970989/c9556f0a-2f37-11e6-86f3-f19c4bcfbea8.png)

**Comment by vamidi** [comment]
![screenshot_20160610-180305](https://cloud.githubusercontent.com/assets/10434772/15970989/c9556f0a-2f37-11e6-86f3-f19c4bcfbea8.png)

**Comment by entropitor** [comment]
Are you sure you're not fetching the events multiple times and always adding them to an ArrayList? Because when you call notifyDatasetChanged() the library will call the method again 3 times. 

(I'm gonna close this, as I don't think it's a bug in the library, but feel free to ask more questions)

**Comment by vamidi** [comment]
Yes that is correct I am aware that the notifyDatasetChanged() is called three times. but in every check I do these lines of code 

<code>
        // Return only the events that matches newYear and newMonth.
        List<WeekViewEvent> matchedEvents = new ArrayList<WeekViewEvent>();
        for (WeekViewEvent event : events) {
            if (eventMatches(event, newYear, newMonth)) {
                matchedEvents.add(event);
            }
        }
</code>

**Comment by entropitor** [comment]
And you don't call your network 3 times for the data?

(I mean, are you sure that eventMatches returns the right number of events?)

**Comment by vamidi** [comment]
Sorry for the late response, I tried multiple things to fix the problem, but I cant so I had to remove the part. 

Thanks for your help!

**Comment by entropitor** [comment]
I seems to me that you're somehow not handling the onMonthChange well. Are you sure you only return each event once? (Have you taken a look at what you return?)

**Comment by burak1000** [comment]
I have this problem too.  onMonthChange  called three times and. events overlapped three times.
Im sure about the return value of my onMonthChangeevent. Array size is 1. but i saw three event :( please hep me
