### ISSUE TITLE
Swipe week by week

### ISSUE THREAD

**Issue by florianhenonin** [alamkanak/Android-Week-View#339]
Now, swipe move views day by day.
What about moving week by week in week display mode ?
The behavior might look like ViewPager with infinite fragment containing WeekView in week display mode.
Is that possible easily ?

Please excuse my english.

**Comment by entropitor** [comment]
It's not currently possible, although it has been brought op in #11.

You can change the scrollspeed currently, but that's about it.

(Closing this because it's a duplicate)

**Comment by nivritgupta** [comment]
@florianhenonin  did you find any solutions regarding this
