### ISSUE TITLE
Since February nothing push on maven ...

### ISSUE THREAD

**Issue by thelittlefireman** [alamkanak/Android-Week-View#343]
Hi,
Could you please release a new version on maven, i really need to get the last fixes.

Thanks
Thomas

**Comment by entropitor** [comment]
@alamkanak is the only one that can do that, unfortunately. See also #137 for the discussion about this.

**Comment by thelittlefireman** [comment]
Please let this amazing lib living and not dying, just give the right to another person, accept the pull request or simply push to an other maven ...

Or could you please ask him if we could fork is git and let the project relive on an other git ?

**Comment by entropitor** [comment]
I'm fine with forking, that's why I opened #137 in the first place, but I won't do it alone. Please go to #137 and say you want to help.
