### ISSUE TITLE
Events Not displaying after GET request to server.

### ISSUE THREAD

**Issue by SimonFM** [alamkanak/Android-Week-View#347]
I have a GET request that returns a JSONArray which I then convert in to a WeekViewEvent. 

These events get returned from onMonthChange(). But they do not seem to appear in the view. The list of event list does seem to be populated.

If I use hard-coded events, they appear no problem! 

Would you offer any advice as to why this is happening?

**Comment by entropitor** [comment]
Did you call `mWeekview.notifyDatasetChanged()`?

See also the async example in the repo
