### ISSUE TITLE
Link to *.ics files

### ISSUE THREAD

**Issue by nbricelj** [alamkanak/Android-Week-View#352]
Hello,

I am new at developing Android apps but I would like to make a simple app that would display a schedule for my faculty. 
The schedule is displayed here: http://urnik.fov.uni-mb.si/ ( you can choose between tabs - Professor, Classroom and Program).

In the drop down menu you can select a schedule to be displayed and on the right under **Možnosti: (Options)** you can select "Prenesi koledar" (Download Calendar)  which is basically a link to *.ics file. Every professor, every classroom and every program have unique *.ics file. 

My question is how to develop an app that will connect to those *.ics files and display a schedule (1- day or 3-day) ?

Thanks

**Comment by entropitor** [comment]
This belongs on stackoverflow or something like that, not here.
