### ISSUE TITLE
Show today date by default.

### ISSUE THREAD

**Issue by mustanseriqbal1** [alamkanak/Android-Week-View#357]
Is it possible to show today date by default after the loading month views..

**Comment by entropitor** [comment]
What do you mean exactly?

**Comment by mustanseriqbal1** [comment]
i mean like we can achieve by this function.
getWeekView().goToToday();
but i want to set the today view default as i soon as i open this calendar.

**Comment by entropitor** [comment]
I'm guessing you have set the number of days to 7 or larger?

**Comment by entropitor** [comment]
Set the attribute `showFirstDayOfWeekFirst` to false then.

**Comment by mustanseriqbal1** [comment]
Yes i have set number of days to 7. but i didn't try above attribute let me try and i will let you know.

**Comment by entropitor** [comment]
(If it doesn't work, let me know, then I'll reopen it, but that should be the problem)
