### ISSUE TITLE
API for customizing day name: MON~SUN

### ISSUE THREAD

**Issue by alinabenko108** [alamkanak/Android-Week-View#361]
Hi,
First of all, I would like to thank you for this helpful lib.
Next, I would like you to create a function or something to customize the day row.
Thanks in advance.
Looking forward to hearing from you soon.
Kind Regards,
Alina

**Comment by entropitor** [comment]
You can use `mWeekView.setDateTimeInterpreter()`

**Comment by alinabenko108** [comment]
Thanks a lot.
