### ISSUE TITLE
goToHour not working

### ISSUE THREAD

**Issue by tommygoh** [alamkanak/Android-Week-View#363]
Can somebody help me guiding this issue ?
When i tried to goToHour it didn't show any changes. it just started from 12 AM.
Am I doing something wrong ? Here is the code :

``` java
List<Events> eventList = responseEvent.getData().getEvents();
events = new ArrayList<>();
for (int i = 0; i < eventList.size(); i++){
Calendar startTime = Calendar.getInstance();
String[] localStartTime = eventList.get(i).getLocalStartTime().split("T");
String[] getStartTime = localStartTime[1].split(":");
String[] date = localStartTime[0].split("-");
startTime.set(Calendar.HOUR_OF_DAY, Integer.parseInt(getStartTime[0]));
startTime.set(Calendar.MINUTE, Integer.parseInt(getStartTime[1]));
startTime.set(Calendar.DATE, Integer.parseInt(date[2]));
startTime.set(Calendar.MONTH, Integer.parseInt(date[1]) - 1);
startTime.set(Calendar.YEAR, Integer.parseInt(date[0]));
Calendar endTime = (Calendar) startTime.clone();
endTime.add(Calendar.HOUR_OF_DAY, 1);
WeekViewEvent event = new WeekViewEvent(i + 1, eventList.get(i).getType(), null, startTime, endTime);
event.setColor(ContextCompat.getColor(DailyEventActivity.this, R.color.colorDarkGray));
events.add(event);
if (i == 0){
   selectedDate = startTime;
    }
}
//                if (eventList.size() < 1) {
//                    Calendar calendar = Calendar.getInstance();
//                    SimpleDateFormat df =  UserDefaults.getDateFormat();
//                    try {
//                        calendar.setTime(df.parse(getDate));
//                    } catch (ParseException e) {
//                        e.printStackTrace();
//                    }
//                    weekView.goToDate(calendar);
//                }
//                else{
//                    weekView.goToDate(selectedDate);
//                }
int height = weekView.getMeasuredHeight();
int textSize = weekView.getTextSize();
int padding = weekView.getHeaderRowPadding();
height = height - textSize - (2 * padding);
weekView.setHourHeight(height / 24);
weekView.goToHour(2);
weekView.notifyDatasetChanged();
```

**Comment by entropitor** [comment]
Sorry, but that code is really unreadable. Can you use triple backticks? 

E.g.

<pre>```java
My code here
```</pre>

**Comment by tommygoh** [comment]
@caske33 done. sorry. my first time here

**Comment by entropitor** [comment]
Which hour range is visible using this code?

**Comment by tommygoh** [comment]
from 00:00 until 23:00 @caske33 
isn't it if we set for e.g goToHour(2), then it means it will show 2:00 on the top ?

**Comment by entropitor** [comment]
Ah, but I think it will currently do nothing if the "endhour" will go over 24:00, can you try with `goToHour(1)`?

**Comment by tommygoh** [comment]
it does nothing also. i'm okay if it doesn't show all hours. just want to show the first hour of what i set @caske33

**Comment by entropitor** [comment]
Can you try to set the hourHeight to a larger value, so less hours are visible and try again then?

**Comment by tommygoh** [comment]
@caske33 i've set it to 100 for hourHeight. it just expanded but the goToHour not working. is there anything i missed out ?

**Comment by tommygoh** [comment]
@caske33 now it's working! it's that when i set hourHeight in xml file, it worked perfectly but when i set programmatically e.g weekView.setHourHeight(100), it didn't work somehow. don't know if this is a bug or not. thanks anyway ! and also there is one more issue. like when i set goToDate(), the event height is not correct but when i didn't set goToDate the event height is not correct. maybe i will open the new one for easier approach
