### ISSUE TITLE
Stack events for each day without time

### ISSUE THREAD

**Issue by longnguyencmg** [alamkanak/Android-Week-View#364]
Hello, I want to remove the time line and show all events in 1 columns because there are so many events. Is there any option like that?

**Comment by entropitor** [comment]
No, there is no option like that. But can't you just use a listview then? If you want everything in a list?

**Comment by longnguyencmg** [comment]
Thank you for your reply. Because I still want to show like 3 days and 7 days mode, and remove timeline, just show events by column since too many overlapped events in 1 day :(

**Comment by entropitor** [comment]
I guess you'll have to code this option yourself.

**Comment by longnguyencmg** [comment]
Yeah, thank u, I fixed myself already, however I got a problem with scrolling issue. The whole not move up like expected :(. If you can have a look at the screen, that's great. Thanks.

![screen shot 2016-09-19 at 11 59 46 pm](https://cloud.githubusercontent.com/assets/4001695/18641097/3ebdeb0a-7ec5-11e6-9a73-b0c606e46300.png)
![screen shot 2016-09-19 at 11 59 59 pm](https://cloud.githubusercontent.com/assets/4001695/18641098/3ec20d8e-7ec5-11e6-9f0b-bb3e401b9055.png)

**Comment by longnguyencmg** [comment]
Yeah, Thank you, I solved the problem. I tried to make it scroll 3 days or 7 days at once, but failed. Can you help with that? Cheers!

**Comment by entropitor** [comment]
That's another feature we currently do not have. I guess you'll have to rewrite the "snapping" of the horizontal scroll/swipe to collide with 3-days or 7-days boundaries instead of with 1-day boundaries.
