### ISSUE TITLE
Migrating To Retrofit 2.0+ or 2.1+ from Retrofit 1.9.0

### ISSUE THREAD

**Issue by derqie** [alamkanak/Android-Week-View#365]
Hi guys. My issue is related to retrofit library being used in the current version. At the moment the Api is using retrofit 1.9.0 but recently there was an update with retrofit to v2.1.0 for their library.
In the `AsynchronousActivity.java`, `public void success(List<Event> events, Response response)` and `public void failure(RetrofitError error)` method is not supported by retofit v1.9.0. How do I migrate and still make my requests to my server with the new retrofit API library?

**Comment by entropitor** [comment]
I guess this is a question you should ask on the retrofit issue tracker / stackoverflow. This has nothing to do with this library.
