### ISSUE TITLE
Show View only from current date

### ISSUE THREAD

**Issue by rakesh-ideal** [alamkanak/Android-Week-View#371]
Hello 
Please guide me how to stop previous dates from current date and show only from current date..
Thanks for great solution.

**Comment by entropitor** [comment]
What do you mean exactly? To not allow scrolling to the past?

**Comment by rakesh-ideal** [comment]
Yes and one more question currently by default it show current date but i want to set any date user want to show record of any date so plz guide me

**Comment by entropitor** [comment]
I think the scrolling is possible in the [Quivr-fork](https://github.com/Quivr/Android-Week-View). And you can use goToDate or something like that to go to a specific date.
