### ISSUE TITLE
Show only weekdays and one week

### ISSUE THREAD

**Issue by t0thkr1s** [alamkanak/Android-Week-View#372]
it would be nice to have only one week with weekdays. Or is it possible? I have not found any good solution...

**Comment by Jacky-Chen-Pro** [comment]
Maybe u can change the source code...

**Comment by t0thkr1s** [comment]
I thought there is a helping community here... but, after several hours I managed to do that despite the poor documentation! Thank you for your help!

**Comment by caske33** [comment]
I think this is implemented in the [Quivr-fork](https://github.com/Quivr/Android-Week-View)

(Btw you cannot expect an open source project to respond within a day, that's just impolite)

**Comment by MohandAndel** [comment]
Hey @tothkris , Can you share your solution?

**Comment by itsmrTech** [comment]
Check this out,maybe it could help you someway...
https://github.com/alamkanak/Android-Week-View/issues/302
