### ISSUE TITLE
Could not know how to use ur library

### ISSUE THREAD

**Issue by venkatkumar7** [alamkanak/Android-Week-View#376]
I attached this line " compile 'com.github.alamkanak:android-week-view:1.2.6' " in the project files and clicked sync now.Then pasted  the Xml codes , it is displaying in the preview window but couldn't run on the Smartphones ,the app opens with a white screen and crashes. please help me

**Comment by venkatkumar7** [comment]
provide any suggestions for this

**Comment by alxndr7** [comment]
Could fix it? I am de same problem, 
I'd appreciate your help.
