### ISSUE TITLE
Same event repeated three times

### ISSUE THREAD

**Issue by prof18** [alamkanak/Android-Week-View#381]
Hi,

i can't understand why an event is repeated three times in the same hour slot like in the screen.
![photo_2016-10-24_21-02-23](https://cloud.githubusercontent.com/assets/9467705/19659814/a5326c0c-9a2d-11e6-8a64-26ca97e64954.jpg)

Here's my code: 

```
  // Get a reference for the week view in the layout.
    mWeekView = (WeekView) view.findViewById(R.id.weekView);

    mWeekView.goToHour(System.currentTimeMillis());

    mainActivity.fab.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            mWeekView.goToToday();
            mWeekView.goToHour(System.currentTimeMillis());
        }
    });

    mWeekView.setOnEventClickListener(new WeekView.EventClickListener() {
        @Override
        public void onEventClick(WeekViewEvent event, RectF eventRect) {
            Toast.makeText(activity, "Event Clicked", Toast.LENGTH_SHORT).show();
        }
    });

    mWeekView.setMonthChangeListener(new MonthLoader.MonthChangeListener() {
        @Override
        public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
            // Populate the week view with some events.
            List<WeekViewEvent> events = new ArrayList<>();

            WeekViewEvent event = new WeekViewEvent(1,"Math Lecture with Mr. Adams",2016,10,24,18,0,2016,10,24,19,0);
            WeekViewEvent event1 = new WeekViewEvent(2,"event2",2016,11,24,18,0,2016,11,24,19,0);
            WeekViewEvent event2 = new WeekViewEvent(3,"event3",2016,12,24,18,0,2016,12,24,19,0);
            events.add(event);
            events.add(event1);
            events.add(event2);

            return events;
        }
    });
```

The layout is the same that you provided in the readme. How can i fix this?

**Comment by christstc** [comment]
Im having the same problem

**Comment by ghost** [comment]
Had the same issue so I ended up checking the documentation of the MonthChangedListener. The problem is you're returning the list of events inside your interface implementation, which is what's causing the issue.

_Very important interface, it's the base to load events in the calendar.
This method is called three times: once to load the previous month, once to load the next month and once to load the current month.
**That's why you can have three times the same event at the same place if you mess up with the configuration**_

**Comment by prof18** [comment]
Oh, it's the same theory that I thought yesterday night but I wasn't able to try out. Today I gonna try to populate the list outside the listener.

How have you dealed with this issue? (If I can ask you).

**Comment by ghost** [comment]
I'm still on the fence on whether or not I want to continue using this library so I haven't put much work into finding a solution yet. 

Off the top of my head you could try the following:
Add a statement that checks whether or not you've already loaded the events for the month given to you as a parameter inside the onMonthChange method..

**Comment by prof18** [comment]
Thanks! It seems the best way to do it.

I'm gonna try and next I'll write what I do.

**Comment by prof18** [comment]
Oh, it's the same theory that I thought yesterday night but I wasn't able
to try out. Today I gonna try to populate the list outside the listener.
How do you fix this issue? (If I can ask you).

**Comment by prof18** [comment]
I gave a deep look at the sample application and i've figured out what to do.

The code needed is the following:

```
        WeekViewEvent event = new WeekViewEvent(0,"Math Lecture with Mr. Adams",2016,10,27,23,0,2016,10,27,23,30);
        WeekViewEvent event1 = new WeekViewEvent(2,"event2",2016,11,24,18,0,2016,11,24,19,0);
        WeekViewEvent event2 = new WeekViewEvent(3,"event3",2016,12,24,18,0,2016,12,24,19,0);
        events.add(event);
        events.add(event1);
        events.add(event2);

        mWeekView.setMonthChangeListener(new MonthLoader.MonthChangeListener() {
            @Override
            public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
                // Populate the week view with some events.


                // Return only the events that matches newYear and newMonth.
                List<WeekViewEvent> matchedEvents = new ArrayList<WeekViewEvent>();
                for (WeekViewEvent event : events) {
                    if (eventMatches(event, newYear, newMonth)) {
                        matchedEvents.add(event);
                    }
                }
                return matchedEvents;
            }
        });

        return view;
    }

    /**
     * Checks if an event falls into a specific year and month.
     * @param event The event to check for.
     * @param year The year.
     * @param month The month.
     * @return True if the event matches the year and month.
     */
    private boolean eventMatches(WeekViewEvent event, int year, int month) {
        return (event.getStartTime().get(Calendar.YEAR) == year && event.getStartTime().get(Calendar.MONTH) == month-1) || (event.getEndTime().get(Calendar.YEAR) == year && event.getEndTime().get(Calendar.MONTH) == month - 1);
    }
```

We can find it in this class: https://github.com/alamkanak/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/AsynchronousActivity.java
