### ISSUE TITLE
[FEATURE REQUEST] Start time and end time of the days

### ISSUE THREAD

**Issue by EvanCooper9** [alamkanak/Android-Week-View#382]
Feature Request:
Currently, the day is displayed as  a full 12AM - 12PM.
Being able to change the start time and end time to each day (say 9AM-5PM) would be a great addition, since most events that people would put in their calendar are only during the working day.

**Comment by EvanCooper9** [comment]
For now, I'm using the the `goToHour(double hour)` method to hide the hours before 9Am

**Comment by caske33** [comment]
I think this is fixed in the [Quivr-fork](https://github.com/Quivr/Android-Week-View)

**Comment by jmsv** [comment]
@EvanCooper9 Hi Evan, could you elaborate please on how you did this? I'm trying to do the same

**Comment by EvanCooper9** [comment]
@jamesevickery  if you use `goToHour(double hour)`, you can have the top of the calendar align with a certain hour. So if you want your calendar to start at 9am, call `goToHour(9)` in your `onCreate`. I do it after everything else has loaded. You can also change your `hourHeight` property in the `.xml` in order to show a specific range of hours, since you've set the first visible hour in the calendar. It's been a while since I've worked on the project that I used this library for, so I may not be totally accurate with that explanation.

Also, if you're planning on developing something in iOS that uses a similar calendar library, check out a Swift library that I made [here](https://github.com/EvanCooper9/swift-week-view).

**Comment by jmsv** [comment]
@EvanCooper9 Okay thanks, I'll have a play with that. Does this just jump to the right hour or can you limit what hours it shows?

I'm not doing any iOS dev at the moment but I'll remember this for if I ever am! Thanks

**Comment by pabloctk** [comment]
Hi @alamkanak, thanks for this tool. It would be very helpful to implement both parameters **startTime** and **endTime** so we can setup the weekView for Working hours only.

Regards.
