### ISSUE TITLE
Detect scroll end & force reload of events

### ISSUE THREAD

**Issue by elmalote** [alamkanak/Android-Week-View#384]
Is it possible to detect when user is scrolling and scrolling has completely stopped?
mScroller.isFinished() doesn't return the correct value. Reports true even when it's still scrolling.

**Comment by marunjar** [comment]
Have you tried checking mCurrentScrollDirection/mCurrentFlingDirection?
These properties should both contain Direction.NONE when not scrolling.

**Comment by elmalote** [comment]
Thanks for your answer.
That is correct, my question was perhaps a little vague. 
I also need to detect when the user starts scrolling. I have solved this by using an interface.
Is there a way to trigger the weekView to load all the events from a list again, thus bypassing monthChanged?

**Comment by elmalote** [comment]
Nevermind fixed it, my call to notifyDataSetChanged wasn't being fired.
