### ISSUE TITLE
Support multi language and different time format

### ISSUE THREAD

**Issue by KimPark89** [alamkanak/Android-Week-View#39]
Hi, I need to modify labels that display the days of the week and the time of the day, so i could choose a different language for the name of the days and a different pattern for day and time (24 hours format without am/pm marker, day before month format, etc). Is it possible to do that?

**Comment by KimPark89** [comment]
I just noticed that there are some pull requests for these problems. I can close.

**Comment by AndroidDeveloperLB** [comment]
@KimPark89 If you wish, I've made a huge pull request that does it automatically for you, based on the current locale:
https://github.com/Quivr/Android-Week-View/pull/97
