### ISSUE TITLE
how  ı do start hour and end hour select. 

### ISSUE THREAD

**Issue by denizme** [alamkanak/Android-Week-View#391]
e.g. start hour : 08:00 , end hour 17:00

**Comment by kevicsalazar** [comment]
it's exactly what i need

**Comment by mehmetdniz** [comment]
saat 08 de başlayacak ve 17 de bitecek. Diğer saat dilimleri gösterilmeyecek.

**Comment by mehmetdniz** [comment]
The clock will start at 08 and finish at 17. Other time zones will not be shown.

**Comment by basmasrour** [comment]
No possibilities?

**Comment by JHNBOS** [comment]
You could play with the setupDateTimeInterpreter.
Inside there should be a methode called interpretTime. In here you could add some if statements to skip every hour higher than 17 and lower than 8

**Comment by monikarora** [comment]
#42 Hey check this (start & end time) work for me :+1:
