### ISSUE TITLE
How can i change begin/finish time in a day?

### ISSUE THREAD

**Issue by onurgurbuz** [alamkanak/Android-Week-View#399]
Hi,
I want to change begin or finish time in a day view. Is that any way?
Please, anyone can help me?

**Comment by berk-can** [comment]
@onurgurbuz I don't know if there is a method at the moment, but I can recommend to you to get screen height than according to your hour span, set hourHeight in Java (in your activity) then only wanted hours will be fit inside the calendar

**Comment by onurgurbuz** [comment]
@berk-can teşekkürler cevabın için. dediğin şekilde sadece saat aralıkları ayarlanıyor. kütüphaneyi değiştirip yapmayı denedim, başlangıç ve bitiş saatlerini manuel olarak ayarlayabildim fakat ekrana sığdırma ile alakalı işlemler vs. biraz uğraştırıyordu. ben de kullanıcıyı kısıtlayarak çözüm buldum.

**Comment by berk-can** [comment]
Çözdüysen sevindim, bakanlar genelde Turkce bilmedigi icin İngilizce bilenler de anlasin diye ingilizce cevap vermeye calistim, duzgun anlatamadiysam kusura bakma xD

**Comment by onurgurbuz** [comment]
istediğimi yapamadım ama çözüm için farklı bir yol buldum. teşekkürler tekrardan.

**Comment by basmasrour** [comment]
@onurgurbuz Did  you find solution? please tell us

**Comment by onurgurbuz** [comment]
@basmasrour no, but i am using goToHour for showing to users
