### ISSUE TITLE
Single Day view mode, how to set zoom to max ?

### ISSUE THREAD

**Issue by blitz33** [alamkanak/Android-Week-View#403]
Hi,

Thanks for this library, i encounter an issue with the display of event in single day view mode.

My event is blank of text,its duration is  15minutes so its very small, i need to zoom each time and the text appear. 

There is a mean to set Zoom to max by default ?

**Comment by JHNBOS** [comment]
In the layout XML file you can set:

app:hourHeight="250dp"
app:maxHourHeight="250dp"
app:minHourHeight="20dp"

If you add the weekview library to your project, not with gradle. Here is mine, with the short event fix

https://github.com/JHNBOS/MeetMeApp/blob/master/app/src/main/java/nl/jhnbos/meetmeapp/WeekView.java

**Comment by JHNBOS** [comment]
I meant, you need tot add the classes manually to your project. The attrs.xml in the "rest" folder and the classes in the Java folder.

https://github.com/alamkanak/Android-Week-View/tree/develop/library/src/main

**Comment by JHNBOS** [comment]
Then, you could copy-paste my code to fixe your problem
