### ISSUE TITLE
display events on week view as well as day view from sqlite database

### ISSUE THREAD

**Issue by saarthi1037** [alamkanak/Android-Week-View#410]
hey,
How to display all events which stored in sqlite databse .
I only get the previous one (single) event on week view.
I want to display my all events , which are stored in sqlite database .

my onMonthChange function is below - 

    @Override
    public List<? extends WeekViewEvent> onMonthChange(int newYear, int newMonth) {

        List<WeekViewEvent> events = new ArrayList<>();

            if (newMonth == sptmonth) {

                Calendar STARTTIME = Calendar.getInstance();
                STARTTIME.set(Calendar.HOUR_OF_DAY, spthrs);
                STARTTIME.set(Calendar.MINUTE, sptmins);
                STARTTIME.set(Calendar.DAY_OF_MONTH, sptday);
                STARTTIME.set(Calendar.MONTH, newMonth - 1);
                STARTTIME.set(Calendar.YEAR, newYear);
                Calendar ENDTIME = (Calendar) STARTTIME.clone();
                ENDTIME.set(Calendar.HOUR_OF_DAY, sptendhrs);
                ENDTIME.set(Calendar.MINUTE, sptendmins);
                ENDTIME.set(Calendar.MONTH, newMonth - 1);
                WeekViewEvent event = new WeekViewEvent(1, getEventTitle(STARTTIME), STARTTIME, ENDTIME);
                event.setColor(getResources().getColor(R.color.eventcolor));
                events.add(event);

            }
   
        return events;
    }

//spthrs, sptmins,sptday, sptendmin,sptendhrs are the values of starttime and endtime came from sqlite database.

![aaa](https://cloud.githubusercontent.com/assets/20809568/23985246/f4cd6a06-0a43-11e7-8db5-3ceacbfb5e69.png)

**Comment by saarthi1037** [comment]
plz, anybody help me ,ASAP.

**Comment by gosemathraj** [comment]
To get Events from db 

    private List<WeekViewEvent> weekViewEvents = new ArrayList<>();;
    private DbHelper dbHelper;

    @Override
    protected void onResume() {
        super.onResume();
        weekViewEvents  = dbHelper.getAllAppointments();
    }

    @Override
    public List<? extends WeekViewEvent> onMonthChange(int newYear, int newMonth) {
        Log.d(LOG_TAG,String.valueOf(newMonth) + "/" + String.valueOf(newYear));
        List<WeekViewEvent> events = getEvents(newYear,newMonth);
        return events;
    }

    private List<WeekViewEvent> getEvents(int newYear, int newMonth) {
        List<WeekViewEvent> tempEvents = new ArrayList<>();
        for(WeekViewEvent event : weekViewEvents){
            if(event.getStartTime().get(Calendar.MONTH) + 1 == newMonth &&
                    event.getStartTime().get(Calendar.YEAR) == newYear){
                tempEvents.add(event);
            }
        }
        return tempEvents;
    }

**Comment by saarthi1037** [comment]
@caske33 @alamkanak @lolobosse 
plz help me guyz. Give me solution...

**Comment by saarthi1037** [comment]
i got the solution,
using Arraylist i solved this issue.....

**Comment by ShubhmVats** [comment]
Can you share code ?  I want to add this functionality to my project

**Comment by empeusz** [comment]
@ShubhmVats have you managed to make it work? If so, could you share the code with me please? I'm struggiling with Room Persistence Library, so every line of code may come in handy! Thank you in advance :)
