### ISSUE TITLE
Same Event name is apprearing 3 times in single row

### ISSUE THREAD

**Issue by rishabhbsdei** [alamkanak/Android-Week-View#415]
Hi,
I am adding events on weekly calendar by your reference code below. But the name of event is appearing three time also when I click on that event it returns me same event id so there is no duplicate events added . Please check my code below also attaching a screen shot 
![screenshot_1490074131](https://cloud.githubusercontent.com/assets/13332233/24133479/44224b34-0e23-11e7-8145-32d0162f52c5.png)
 
 events = new ArrayList<WeekViewEvent>();

        Calendar startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 3);
        startTime.set(Calendar.MINUTE, 0);
        startTime.set(Calendar.MONTH, newMonth - 1);
        startTime.set(Calendar.YEAR, newYear);
        Calendar endTime = (Calendar) startTime.clone();
        endTime.add(Calendar.HOUR, 1);
        endTime.set(Calendar.MONTH, newMonth - 1);
        WeekViewEvent event = new WeekViewEvent(1, "ABC", startTime, endTime);
        //event.setColor(getResources().getColor(R.color.event_color_01));
        events.add(event);

        startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 3);
        startTime.set(Calendar.MINUTE, 30);
        startTime.set(Calendar.MONTH, newMonth-1);
        startTime.set(Calendar.YEAR, newYear);
        endTime = (Calendar) startTime.clone();
        endTime.set(Calendar.HOUR_OF_DAY, 4);
        endTime.set(Calendar.MINUTE, 30);
        endTime.set(Calendar.MONTH, newMonth-1);
        event = new WeekViewEvent(10, "XYZ", startTime, endTime);
        //event.setColor(getResources().getColor(R.color.event_color_02));
        events.add(event);

        startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 3);
        startTime.set(Calendar.MINUTE, 30);
        startTime.set(Calendar.MONTH, newMonth-1);
        startTime.set(Calendar.YEAR, newYear);
        startTime.set(Calendar.DATE,startTime.get(Calendar.DATE)+1);
        endTime = (Calendar) startTime.clone();
        endTime.set(Calendar.HOUR_OF_DAY, 4);
        endTime.set(Calendar.MINUTE, 30);
        endTime.set(Calendar.MONTH, newMonth-1);
        event = new WeekViewEvent(10, "YYM", startTime, endTime);
        //event.setColor(getResources().getColor(R.color.event_color_02));
        events.add(event);

**Comment by anvesh1212** [comment]
` onMonthChange()` method gets called three times (current month, previous month, next month of the view you are in), each time it gets called, it creates the event. therefore it show three same events in a row. make sure you clear the `events` before you starting adding `event` to it when `onChangeMonth()` is called

**Comment by rishabhbsdei** [comment]
How to restrict this method to get called only once? It should be called only when the month changed.

**Comment by anvesh1212** [comment]
I have simply added a HashMap which has key as a string of month and year and value as list of weekViewEvents of that particular month.  check the below code, it is self descriptive.

`

        private static final String TAG = AsynchronousActivity.class.getSimpleName();
    private List<WeekViewEvent> events;
    private HashMap<String,List<WeekViewEvent>> allEvents = new HashMap<String,List<WeekViewEvent>>() ;

    @Override
    public List<? extends WeekViewEvent> onMonthChange(int newYear, int newMonth) {


        if(allEvents.containsKey(newMonth+"-"+newYear))
            return allEvents.get(newMonth+"-"+newYear);

        this.events =  new ArrayList<WeekViewEvent>();

        this.events =  new ArrayList<WeekViewEvent>();
        RepeatedEvents week = new RepeatedEvents();
        week.setWeekView(getWeekView());
        this.events.addAll(week.getWeekEvents(newYear, newMonth, getApplicationContext()));
        allEvents.put(newMonth+"-"+newYear,this.events);
        Log.d(TAG, "final returning repeated event list has "+this.events.size()+" events.");

        return this.events;


`

`

**Comment by anvesh1212** [comment]
is it clear? if not let me know. or if the issue is solved close the issue.

**Comment by rishabhbsdei** [comment]
No, issue is not resolved. Events which are  showing on the weekly view must be created from events list which we are passing in onMonthChange() lisnener. I checked my events list it has only unique elements because I checked contains before add. But still shows me three times.
I have to get events from my server call which I need to hit on Month change.
Can I simply supply this events list weekly view without month change listener

**Comment by anvesh1212** [comment]
you got me wrong. 
if you are looking at weekView code, u can find three WeekViewEvent list
`

                mPreviousPeriodEvents = previousPeriodEvents;

                mCurrentPeriodEvents = currentPeriodEvents;

                mNextPeriodEvents = nextPeriodEvents;
` 

so one particular event of yours is created by three calls.

**Comment by rishabhbsdei** [comment]
Please look at my Code below and let me know how can I resolve this issue of repeated Events

package com.financialapp.allevasoft.fragments;

import android.graphics.RectF;
import android.os.Bundle;
import android.os.Handler;
import android.support.annotation.Nullable;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import com.alamkanak.weekview.MonthLoader;
import com.alamkanak.weekview.WeekView;
import com.alamkanak.weekview.WeekViewEvent;
import com.alamkanak.weekview.WeekViewLoader;
import com.financialapp.allevasoft.R;
import com.financialapp.allevasoft.activity.BaseActivity;
import com.financialapp.allevasoft.model.AppointmentResponseModel;
import com.financialapp.allevasoft.model.AssignmentRequest;
import com.financialapp.allevasoft.model.BaseRequest;
import com.financialapp.allevasoft.utils.Constant;
import com.financialapp.allevasoft.utils.UserData;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import org.cryptonode.jncryptor.CryptorException;

import java.io.UnsupportedEncodingException;
import java.lang.reflect.Type;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 * Created by rishabhbhardwaj on 17/3/17.
 */

public class WeeklyFragment extends BaseFragment {


    private View view;
    private WeekView mWeekView;
    ArrayList<AppointmentResponseModel> appointmentResponseModels;
    BaseActivity baseActivity;
    private static final SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    private static final SimpleDateFormat cloneDate = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
    Handler handler = new Handler();
    public static WeeklyFragment newInstance() {
        WeeklyFragment fragment = new WeeklyFragment();
        return fragment;
    }
    public WeeklyFragment(){

    }
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_weekly, container, false);
        initData(view);
        setViewListeners();
        bindData();
        return view;
    }

    @Override
    public void initData(View view) {
        super.initData(view);
        baseActivity = (BaseActivity)getActivity();
        // Get a reference for the week view in the layout.
        mWeekView = (WeekView) view.findViewById(R.id.weekView);

// Set an action when any event is clicked.
        mWeekView.setOnEventClickListener(new WeekView.EventClickListener() {
            @Override
            public void onEventClick(WeekViewEvent event, RectF eventRect) {
                Toast.makeText(getContext(),"Clicked"+event.getId(),Toast.LENGTH_LONG).show();
            }
        });

        mWeekView.setEventLongPressListener(new WeekView.EventLongPressListener() {
            @Override
            public void onEventLongPress(WeekViewEvent event, RectF eventRect) {

            }
        });
        events = new ArrayList<>();
        //getEvents(0,0);

        mWeekView.setMonthChangeListener(mMonthChangeListener);
       // getEvents(2017,3);
        mWeekView.notifyDatasetChanged();


       getEventsFromServer(2017,3);


    }
    HashMap<String,List> allEvents = new HashMap<String,List>() ;
    boolean isCalled;
    int lastMonth=0;
    MonthLoader.MonthChangeListener mMonthChangeListener = new MonthLoader.MonthChangeListener() {
        @Override
        public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
            // Populate the week view with some events.
            
            Log.e("DATA EVENTS", events + "");
            return events;
        }
    };
    List<WeekViewEvent> events;

    /***
     *@param startDate
     * Start Date to get appointments yyyy-MM-dd
     * @param endDate
     * End date to get appointment yyyy-MM-dd
     */
    public     List<WeekViewEvent> hitMonthlyAssignments(final String startDate, final String endDate)
    {


        AssignmentRequest assignmentRequest = new AssignmentRequest();
        assignmentRequest.appointmentId = 0;
        assignmentRequest.clientId = UserData.getInstance().getClientInfoModel().clientId+"";
        assignmentRequest.startDate = startDate;
        assignmentRequest.endDate = endDate;
        assignmentRequest.viewBy  =  "5";
        final Gson gson = new Gson();
        final String json = gson.toJson(assignmentRequest);
        BaseRequest baseRequest = new BaseRequest();
        try {
            baseRequest.param = utility.encryptData(json.getBytes());
        } catch (CryptorException e) {
            e.printStackTrace();
        }
        dialog.show();
        Call<String> call = apiService.postRequest(Constant.WebConstant.WS_CLIENT_SCHEDULE_LIST,UserData.getInstance().getRehabDetailModel().databaseCatalog,"bearer "+UserData.getInstance().getLoginResult().accessToken,baseRequest);
        call.enqueue(new Callback<String>() {
            @Override
            public void onResponse(Call<String> call, Response<String> response) {

                if (response.code() ==200)
                {
                    try {
                        if (events.size()>0)
                        {
                            events.clear();
                            mWeekView.notifyDatasetChanged();
                        }
                        Date date1 = new Date(System.currentTimeMillis());
                        String current= formatter.format(date1);
                        String jsonResponse = utility.decryptData(response.body());
                        Type listType = new TypeToken<ArrayList<AppointmentResponseModel>>(){}.getType();
                        appointmentResponseModels =gson.fromJson(jsonResponse,listType);

                        if (appointmentResponseModels!=null && !appointmentResponseModels.isEmpty())
                        {
                            WeekViewEvent event=null;
                            Date dateStart =null;Date dateEnd = null;
//                            if (!events.isEmpty())
//                                events.clear();
                            for (AppointmentResponseModel appointmentResponseModel: appointmentResponseModels)
                            {

                                Date mDate= new Date(Long.parseLong(appointmentResponseModel.startDate.substring(6,appointmentResponseModel.startDate.length()-2)));
                                String strDate = formatter.format(mDate)+" "+appointmentResponseModel.startTime;
                                String endDate = formatter.format(mDate)+" "+appointmentResponseModel.endTime;
                                try {
                                    dateStart = cloneDate.parse(strDate);
                                    dateEnd = cloneDate.parse(endDate);
                                } catch (ParseException e) {
                                    e.printStackTrace();
                                }
                                Calendar startTime = Calendar.getInstance();
                                startTime.setTime(dateStart);

                                Calendar endTime = (Calendar) startTime.clone();
                                endTime.setTime(dateEnd);
//                                endTime.set(Calendar.HOUR_OF_DAY, 4);
//                                endTime.set(Calendar.MINUTE, 30);
                                 event = new WeekViewEvent(Integer.parseInt(appointmentResponseModel.appointmentId), "Meeting with "+appointmentResponseModel.userRole, startTime, endTime);
                                // app
                                if (!events.contains(event))
                                      events.add(event);
                            }
                            if (!isCalled)
                                isCalled=true;
                            mWeekView.notifyDatasetChanged();
                          //  mWeekView.setEven
                            //mWeekView.setMonthChangeListener(mMonthChangeListener);

                        }
                    } catch (CryptorException e) {
                        e.printStackTrace();
                    } catch (UnsupportedEncodingException e) {
                        e.printStackTrace();
                    }
                }
                else
                    baseActivity.showSnackbar(response.raw().message()+"");

                if (dialog.isShowing())
                    dialog.dismiss();
            }

            @Override
            public void onFailure(Call<String> call, Throwable t) {
                if (dialog.isShowing())
                    dialog.dismiss();
                baseActivity.showSnackbar(getString(R.string.something_went_wrong));

            }
        });

        return events;
    }

    /***
     * Get Events of Month
     * @param mYear
     * @param mMonth
     */
    private void getEventsFromServer(int mYear,int mMonth)

    {
        Calendar calendar=Calendar.getInstance();
        if (mMonth >0 && mYear>0)
        {
            calendar.set(Calendar.MONTH,mMonth);
            calendar.set(Calendar.YEAR,mYear);
        }
        int month = calendar.get(Calendar.MONTH);

        int lastDAy =calendar.getActualMaximum(Calendar.DAY_OF_MONTH);

        int year = calendar.get(Calendar.YEAR);
        if (month<10)
            hitMonthlyAssignments(year+"-0"+month+"-01",year+"-0"+month+"-"+lastDAy);
        else
            hitMonthlyAssignments(year+"-"+month+"-01",year+"-"+month+"-"+lastDAy);
    }

}

**Comment by monxarat** [comment]
Hi Guys,

Please help me resolve this problem.

**Comment by anvesh1212** [comment]
Implement eventMatches() method. So that only events related to that particular month will be returned. You can get the method from AsynchronousActivity.java

**Comment by monxarat** [comment]
This is a problem in core.

**Comment by anvesh1212** [comment]
Even I had a same problem in the initial state but later I realized that for each and every call onMonthChange the same event is being returned, resulting in the repetition of the event.

so I controlled the return list by using hashmap and eventMatches

hashmap - help in returning the events, if the events of month are already retrieved previously.
eventMatch - helps in removing the events which do not belong to that particular month.

**Comment by rishabhbsdei** [comment]
Thanks for your reply.

**Comment by Nileshbhutka** [comment]
How to Dynemic Event set like we get Api  to date 2017 jan 25 10:25 to 2017 jan 25 11:45

**Comment by gurkankesgin** [comment]
I solve the problem to make comment line like below . Its prevent to call monthchange() 3 time . but Im not sure whats wrong now :) 

WeekView.Class

 ```
if (currentPeriodEvents == null)
                    currentPeriodEvents = mWeekViewLoader.onLoad(periodToFetch);
               /* if (previousPeriodEvents == null)
                    previousPeriodEvents = mWeekViewLoader.onLoad(periodToFetch-1);
                if (nextPeriodEvents == null)
                    nextPeriodEvents = mWeekViewLoader.onLoad(periodToFetch+1);*/


                // Clear events.
                mEventRects.clear();
                sortAndCacheEvents(currentPeriodEvents);
               /* sortAndCacheEvents(previousPeriodEvents);
                sortAndCacheEvents(nextPeriodEvents);*/
                calculateHeaderHeight();
```

**Comment by WillNilges** [comment]
I'm just gonna chuck my solution in here for future reference.
```
 @Override
    public List<WeekViewDisplayable<Event>> onMonthChange(Calendar startDate, Calendar endDate) {

        List<WeekViewDisplayable<Event>> weekViewEvents = new ArrayList<>();

        final int color1 = getResources().getColor(R.color.event_color_01);
        final int color2 = getResources().getColor(R.color.event_color_02);
        final int color3 = getResources().getColor(R.color.event_color_03);
        final int color4 = getResources().getColor(R.color.event_color_04);

        if (events != null){
            infoPrint("event size : " + events.size());
            for (int i = 0; i < events.size(); i++){
                Event e = events.get(i);
                WeekViewEvent wve = new WeekViewEvent();

                // Set ID (not the Google Calendar ID. I guess. Long.parseLong(e.getId()))
                wve.setId(i);

                // Set Title
                wve.setTitle(e.getSummary());

                //Set dates and times
                //IMPORTANT: Get the current year and month that the event is supposed to be displayed in.
                final int newYear = startDate.get(Calendar.YEAR);
                final int newMonth = startDate.get(Calendar.MONTH);

                // Start Time
                Calendar startCal = Calendar.getInstance();
                startCal.setTimeInMillis(e.getStart().getDateTime().getValue());
                //IMPORTANT: Call Calendar.set() as such, and it'll fix everything.
                startCal.set(Calendar.MONTH, newMonth);
                startCal.set(Calendar.YEAR, newYear);
                wve.setStartTime(startCal);

                // End Time
                Calendar endCal = Calendar.getInstance();
                endCal.setTimeInMillis(e.getEnd().getDateTime().getValue());
                //IMPORTANT: Call Calendar.set() as such, and it'll fix everything.
                endCal.set(Calendar.MONTH, newMonth);
                endCal.set(Calendar.YEAR, newYear);
                wve.setEndTime(endCal);

                wve.setColor(color1);

                wve.setIsAllDay(false);

                weekViewEvents.add(wve);
            }
        }
        return weekViewEvents;
    }

```

**Comment by charmas3r** [comment]
Here's a solution, kind of ugly but it works... 

    @Override
    public List<? extends WeekViewEvent> onMonthChange(int newYear, int newMonth) {

        if(!eventFlag) {
            if (allEvents.containsKey(mMonth + "-" + mYear)) {
                eventFlag = true;
                return allEvents.get(mMonth + "-" + mYear);
            }
        }

        events =  new ArrayList<WeekViewEvent>();

        Calendar startCal = Calendar.getInstance();
        startCal.set(Calendar.DAY_OF_MONTH, mDay);
        startCal.set(Calendar.HOUR_OF_DAY, mStartHour);
        startCal.set(Calendar.MINUTE, mStartMin);
        startCal.set(Calendar.MONTH, mMonth-1);
        startCal.set(Calendar.YEAR, mYear);
        Calendar endCal = (Calendar) startCal.clone();
        endCal.set(Calendar.HOUR_OF_DAY, mEndHour);
        endCal.set(Calendar.MINUTE, mEndMin);
        WeekViewEvent event = new WeekViewEvent(2, mName, startCal, endCal);
        event.setColor(getResources().getColor(R.color.event_color_02));
        events.add(event);

        allEvents.put(mMonth + "-" + mYear, events);
        Log.d("List:", "List returned");

        events =  new ArrayList<WeekViewEvent>();
        return events;
    }

**Comment by SellamAbderrahmane** [comment]
List<WeekViewEvent> events = new ArrayList<>();
        for(WeekViewEvent event:mEvents) {
            if (event.getStartTime().get(Calendar.MONTH) != newMonth && event.getStartTime().get(Calendar.YEAR) != newYear) {
                events.add(event);
            }
        }
        return events;
