### ISSUE TITLE
Events added after HTTP REST call not drawn

### ISSUE THREAD

**Issue by svavahb** [alamkanak/Android-Week-View#421]
We are trying to populate the calendar with events we get from our REST web service, using a similar solution as seen here: https://github.com/JHNBOS/MeetMeApp/blob/master/app/src/main/java/nl/jhnbos/meetmeapp/Week.java

However, after the asynchronous HTTP request finishes, the events are not drawn. We can see that they are in the WeekViewEvent List that is returned in onMonthChange, but the events never show up in the calendar.
When we were adding hard coded events in onMonthChange they showed up, but not if we add them elsewhere.

Is this a bug, or are we missing something?

Our code:
`public class ScheduleActivity extends AppCompatActivity implements MonthLoader.MonthChangeListener {

    ScheduleManager scheduleManager;
    JSONparser jsonparser;

    private static final int TYPE_DAY_VIEW = 1;
    private static final int TYPE_THREE_DAY_VIEW = 2;
    private static final int TYPE_WEEK_VIEW = 3;
    private int mWeekViewType = TYPE_THREE_DAY_VIEW;
    protected WeekView mWeekView;
    WeekView.EventClickListener mEventClickListener;
    WeekView.EventLongPressListener mEventLongPressListener;
    List<WeekViewEvent> allEvents;
    List<WeekViewEvent> ThisMonthsEvents;

        @Override
        public List<? extends WeekViewEvent> onMonthChange(int newYear, int newMonth) {
/*

            Calendar startTime = Calendar.getInstance();
            startTime.set(Calendar.HOUR_OF_DAY, 5);
            startTime.set(Calendar.MINUTE, 0);
            startTime.set(Calendar.MONTH, newMonth -1);
            startTime.set(Calendar.YEAR, newYear);
            startTime.add(Calendar.DATE, 1);
            Calendar endTime = (Calendar) startTime.clone();
            endTime.add(Calendar.HOUR_OF_DAY, 3);
            endTime.set(Calendar.MONTH, newMonth-1);
            WeekViewEvent event = new WeekViewEvent(3, "test0", startTime, endTime);

*/

            //event.setColor(getResources().getColor(R.color.event_color_02));
            //allEvents.add(event);
            System.out.println("all"+allEvents);

            for (int i = 0; i < allEvents.size(); i++) {
                System.out.println(allEvents.get(i).getStartTime().get(Calendar.MONTH)+" "+newMonth);
                if((allEvents.get(i).getStartTime().get(Calendar.MONTH) == newMonth)&&(allEvents.get(i).getStartTime().get(Calendar.YEAR) == newYear))
                    ThisMonthsEvents.add(allEvents.get(i));
            }

            System.out.println("THIS "+ThisMonthsEvents);

            mWeekView.notifyDatasetChanged();

            return ThisMonthsEvents;

         }

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_schedule);

        allEvents = new ArrayList<>();
        ThisMonthsEvents = new ArrayList<>();

        // Get a reference for the week view in the layout.
        mWeekView = (WeekView) findViewById(R.id.weekView);

        // Set an action when any event is clicked.
        mWeekView.setOnEventClickListener(mEventClickListener);

        // The week view has infinite scrolling horizontally. We have to provide the events of a
        // month every time the month changes on the week view.
        mWeekView.setMonthChangeListener(this);

        // Set long press listener for events.
        mWeekView.setEventLongPressListener(mEventLongPressListener);

        PlanguinRestClient.get("home?loggedInUser=svava",new RequestParams(), new JsonHttpResponseHandler(){
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONObject jsonSchedule) {
                try {
                    Schedule schedule = jsonparser.parseSchedule(jsonSchedule);
                    List<ScheduleItem> scheduleItems = schedule.getItems();
                    for (int i = 0; i < scheduleItems.size(); i++) {
                        System.out.println(scheduleItems.get(i));

                    }
                    allEvents.clear();
                    Calendar startTime = Calendar.getInstance();
                    startTime.set(Calendar.HOUR_OF_DAY, 5);
                    startTime.set(Calendar.MINUTE, 0);
                    startTime.set(Calendar.MONTH, 3);
                    startTime.set(Calendar.YEAR, 2017);
                    startTime.add(Calendar.DATE, 1);
                    Calendar endTime = (Calendar) startTime.clone();
                    endTime.add(Calendar.HOUR_OF_DAY, 3);
                    endTime.set(Calendar.MONTH, 3);
                    WeekViewEvent event = new WeekViewEvent(3, "test0", startTime, endTime);
                    allEvents.add(event);
                    //ThisMonthsEvents.clear();

                    //onTest(3,2017);
                    //mMonthChangeListener.onMonthChange(3,2017);
                    mWeekView.notifyDatasetChanged();

                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        });
    }
}`

**Comment by anvesh1212** [comment]
I think your app is processing events continuously. remove mWeekView.notifyDatassetChanged() in the loop. call it after the loop terminates. and Also remove mWeekView.notifyDatassetChanged() in onMonthChange().

hope it works fine after this modifications.
let me know if it worked or not. if yes then close the issue.

**Comment by svavahb** [comment]
Hi, thanks for your answer.
mWeekView.notifyDatasetChanged() is not in any loop. The only thing the loop is doing is printing out the events (just for debugging purposes).

I also removed the .notifyDatasethanged() in onMonthChange and it did not change anything, the event still does not show up.

**Comment by svavahb** [comment]
This got solved for no apparent reason. We could not find any change we had made that would have resulted in this suddenly working.... so i'll just close this issue :)
