### ISSUE TITLE
Cannot resolve method 'getEvents'

### ISSUE THREAD

**Issue by jamesleekko** [alamkanak/Android-Week-View#436]
As the picture show, I'm confused..

![image](https://cloud.githubusercontent.com/assets/26496074/26284471/ed0f9348-3e6e-11e7-9aab-3668955686d5.png)

**Comment by jamesleekko** [comment]
Why can't I use the method 'get Events' ?

**Comment by alamkanak** [comment]
This is a method which will provide the list of events for specific time range which will be shown in the calendar. You have to implement it yourself. For help, see the provided sample app.

**Comment by jamesleekko** [comment]
thanks.
