### ISSUE TITLE
How can I let event title show only once?

### ISSUE THREAD

**Issue by jamesleekko** [alamkanak/Android-Week-View#441]
WeekViewEvent event = new WeekViewEvent(1, "事件1", startTime, endTime);

After I add events, 
![issue](https://cloud.githubusercontent.com/assets/26496074/26495188/2712f672-4255-11e7-8014-0b6fe253ed1b.jpg)

**Comment by en-Vishal** [comment]
how to solve this issue

**Comment by Ankur008** [comment]
Anyone got the solution?
