### ISSUE TITLE
Week View does not go to specified date when rendering 7 visible days

### ISSUE THREAD

**Issue by udaysrinath** [alamkanak/Android-Week-View#445]
This works: 

``` weekView.setNumberOfVisibleDays(6);``` 
```weekView.goToDate(currentCalDate);```

This does NOT work:

``` weekView.setNumberOfVisibleDays(7);``` 
```weekView.goToDate(currentCalDate);```

This is off by 7 days, pointing to the previous week.
Also, every time I rotate, it keeps going back a week, which is weird.

@alamkanak Could you please take a look at this issue?

**Comment by prabhatsubedi** [comment]
I am facing same issue.

**Comment by Taharo** [comment]
**Its work for me**
```
//Kotlin
Handler().postDelayed({
                weekView?.goToToday()
                }
            }, 100)
```

**Comment by udaysrinath** [comment]
@Taharo - Does the switch to any specified date work for you when 7 days are rendered?

**Comment by udaysrinath** [comment]
Seems to be resolved on fork : https://github.com/Quivr/Android-Week-View/issues/58, closing issue.
