### ISSUE TITLE
goToHour(..) not working

### ISSUE THREAD

**Issue by dirkvranckaert** [alamkanak/Android-Week-View#45]
I want the current hour to be scrolled to by default, but using the goToHour(..) method does not work. See my code snippet below.

Code snippet:

    Calendar calendar = Calendar.getInstance();
    mWeekView.goToDate(calendar);
    mWeekView.goToHour(calendar.get(Calendar.HOUR_OF_DAY)); // Not working... Also tried with Calendar.HOUR...

Using release 1.1.2

**Comment by caske33** [comment]
Where are you placing this snippet? 

I think the bug lies in the initialisation of the library. A part of it might be happening while drawing for the first time, so I think that's where the problem lies.

**Comment by dirkvranckaert** [comment]
For test purpose I've put in a postDelayed... But the goToDate works, just not the goToHour. The delay i used was 2 seconds. So that should be fine (tested on genymotion emulator and 1+1 phone)

**Comment by caske33** [comment]
goToHour works for me, so I'm guessing you're doing something wrong yourself, not the library.

**Comment by KimPark89** [comment]
goToHour() works fine for me. I call it just after having inizializated weekView and setted listeners. Also remeber that goToHour() accept a double, so if you want that weekView'll go to 7,45 (hour has 60 minutes) you must put 7,75 (100 fractional values from 7,00 to 8,00).

**Comment by dirkvranckaert** [comment]
Indeed it seems to work now. But still there are two bugs with that:

1. I used a calendar, passed that to scroll horizontally to the date and on
the next line I used that same Calendar instance to get the hours and pass
it to the goToHour method, but the hours seemed to be reset to zero (as the
seconds and minutes) in the Calendar object. So that is a bug in the
goToDate method.
2. I fixed that by having two calendar instances (hopefully number one gets
fixed soon so I don't have to use this tricky work-a-round). In my case the
hour to scroll to was 16 (4PM). But because I was working on a large screen
the bottom of the week view would be past midnight. So the library throws
an error. And is a big mistake in my opinion. Don't know the exact name of
the exception thrown right now because I'm not at my PC right now. But if a
custom exception gets thrown, you did the calculations already. So you
should just scroll as low as possible. That makes the library pretty
worthless to me right now because I cannot know when the week view cannot
render correctly and what value I should pass instead (so the max scroll
value).

**Comment by KimPark89** [comment]
@dirkvranckaert @caske33

1. Yes, goToDate() resets Calendar's hour, minutes, seconds and milliseconds but it's not a bug. It creates a second instance of Calendar with today's date and then it calculate the milliseconds difference from the 2 instances. Then with that value it calculates the offset for the scroll (to the new date). However I think it can be fixed by getting hour, minutes, seconds and milliseconds from the first instance (new date) and putting in the second one (today).

2. I agree with you.

**Comment by caske33** [comment]
1. I believe this has to be fixed. Either by cloning the given instance, or passing it to the today instance
2. This has been bugging me for a while (I had seen the code before), but I haven't had time to change it yet. 

I hope to have some time to work on this library next week.

**Comment by dirkvranckaert** [comment]
Who should publish a new version of the lib? I'm waiting for some of the
fixes to publish a new version of one of my apps...

**Comment by caske33** [comment]
Only @alamkanak is able to (as far as I know), but the published version contains all commits from the master branch. 

PS @dirkvranckaert These changes are rather small, so maybe you can fix them yourself and send in a PR (pull request).
https://github.com/alamkanak/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L1347-L1391 contains the section that needs changing.

**Comment by hdo555** [comment]
im still seeing this issue where goToDate isnt working as expected. 

Im using WeekView in a Fragment where it is initialized in onCreateView and calls to goToDate are being called afterwards. 

there shouldn't be anything more to this right?

using version 1.2.6

EDIT: I was able to get goToDate to work BUT i had to also call goToHour. Not sure if that was the intended use.

**Comment by entropitor** [comment]
goToDate only takes the date into consideration. If you want to change the hour you also have to call goToHour indeed.
