### ISSUE TITLE
Adding subtitle to the event

### ISSUE THREAD

**Issue by CrossPT** [alamkanak/Android-Week-View#458]
Is this possible? Or it's just the title avaiable?

**Comment by SeaRoth** [comment]
All I know is the location shows if you populate it 

# Android Studio:
![image](https://user-images.githubusercontent.com/3461713/32224952-9cff1dda-be00-11e7-9813-001969ded924.png)

# Android-Week-View:
![image](https://user-images.githubusercontent.com/3461713/32224880-5f9cc58c-be00-11e7-85ed-85c23e064f36.png)

# Google:
![image](https://user-images.githubusercontent.com/3461713/32224910-79ef5648-be00-11e7-8ae1-5f64f525ad3e.png)

**Comment by FnR2** [comment]
No its not possible but you can sepereate your title text with \n  and seperated text  look like subtitle
