### ISSUE TITLE
Add margin between hours

### ISSUE THREAD

**Issue by CrossPT** [alamkanak/Android-Week-View#460]
is it possible to achieve a effect like this image below?
![image](https://user-images.githubusercontent.com/10212814/30886947-28db1008-a311-11e7-8ab6-7c9ac9f56ad9.png)

**Comment by SeaRoth** [comment]
Dude is this question real?

How much effort did you put into finding this out? It took me 14 seconds.

![image](https://user-images.githubusercontent.com/3461713/32224579-4151ae72-bdff-11e7-9263-e7fa2caeeca7.png)
