### ISSUE TITLE
duplicate value every mounth .

### ISSUE THREAD

**Issue by gurkankesgin** [alamkanak/Android-Week-View#467]
I add a event but it shown every mounth same day same hour .

For example : event date  = 01.01.2017  , 01.02.2017 , 01.03.2017 .... same event again

**Comment by SkyleKayma** [comment]
In onMonthChange(), you have to check if your event is in the actual month that is load. (The new month and new year are given in parameters)

**Comment by psosnowka** [comment]
Try this:
onMonthChange(int newYear, int newMonth){
      List<Events> list = new ....
      if(YourEventMonthNubmer == new Month){
            //set details of your event here
              list.add(event)
      }
      return list
}
