### ISSUE TITLE
Add listener for changing/scrolling month

### ISSUE THREAD

**Issue by dirkvranckaert** [alamkanak/Android-Week-View#47]
I need a listener when scrolling through the calendar and the month changes.

Something like:

    mWeekView.setMonthScrolledListener(this);
    ...
    public void onMonthScrolled(int newYear, int newMonth) {
        // I would update some parts of my ui like the actionbar title with the current year and month (Google calendar wise)
    }

**Comment by caske33** [comment]
I'm planning on making such a listener for notifying you when the (first) visible day has changed. You'll be able to acheive your goal with that listener.

**Comment by dirkvranckaert** [comment]
Any update on when you are planning the new features / new release?

**Comment by caske33** [comment]
I don't have any plans, no. It should be done in a month normally, probably faster.

(btw I'm not the maintainer, so I can't make a release)
