### ISSUE TITLE
Question: Possible to prevent scrolling to other days?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [alamkanak/Android-Week-View#490]
Suppose I want to view only a single, specific week, for example, is it possible to do it without letting the user to go to others?

**Comment by AndroidDeveloperLB** [comment]
Seems it is possible , here:

https://github.com/alamkanak/Android-Week-View/issues/433

**Comment by gakhar306** [comment]
How?

**Comment by AndroidDeveloperLB** [comment]
Look at the link.
