### ISSUE TITLE
Issues & Queries for Weekview

### ISSUE THREAD

**Issue by HasmukhBhadani** [alamkanak/Android-Week-View#51]
Thanks for sharing this library, 

Here i have Query need help,
1) How i can add dynamic event in week view ?
 -Date :: 1/13/2015
-FromTime ::12:30
-ToTime :: 5:30
  as above mention there are my data which i am getting in response from server, how i can add it ?

2)How i can manage "onMonthChange" ?
-I used AsyncTask for send request to the server, as result how i can add event after getting responce in "onPostExecute" 

3) Add event in 3 times
- i think this is open issue, while i am adding any event in weekview in will add 3 times

Here is the code i am trying to modify it and set dynamic event but no luck !!!

@Override
	public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {

		// Populate the week view with some events.
		List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();

		String date1 = "2015-01-12 02:30 am";
		SimpleDateFormat form = new SimpleDateFormat("yyyy-MM-dd hh:mm a");
		java.util.Date d1 = null;
		Calendar cal;

		try 
		{
			d1 = form.parse(date1);
		} 
		catch (java.text.ParseException e) 
		{
			e.printStackTrace();
		}

		cal = Calendar.getInstance();
		cal.setTime(d1);

		Calendar startTime = Calendar.getInstance();
		startTime.set(Calendar.DAY_OF_MONTH, cal.get(Calendar.DAY_OF_MONTH));
		startTime.set(Calendar.HOUR_OF_DAY, cal.get(Calendar.HOUR_OF_DAY));
		startTime.set(Calendar.MINUTE, cal.get(Calendar.MINUTE));
		startTime.set(Calendar.MONTH, cal.get(Calendar.MONTH));
		
		Calendar endTime = (Calendar) startTime.clone();		
		endTime.set(Calendar.DAY_OF_MONTH,12);
		endTime.set(Calendar.HOUR_OF_DAY,4);
		endTime.set(Calendar.MINUTE,30);
		endTime.set(Calendar.MONTH, 0);

		WeekViewEvent event = new WeekViewEvent(1, getEventTitle(startTime), startTime, endTime);
		event.setColor(getResources().getColor(R.color.event_color_01));
		events.add(event);
	
		return events;
	}

Please give me solution or idea.

Thanks in advance.

**Comment by caske33** [comment]
https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158

**Comment by alamkanak** [comment]
https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158
