### ISSUE TITLE
How to change time axis to predefined name

### ISSUE THREAD

**Issue by anurajr1** [alamkanak/Android-Week-View#542]
I want to change the week view time part(y axis) to predefined names. Suppose name of 10 students in a classroom. x axis can be the same date also.

**Comment by l-k22** [comment]
I wanted to change the x-axis to locations, did you manage to change the y-axis? If so what was your approach?

**Comment by swatiomar27** [comment]
Hi, I also have a requirement to change the week view time part(y axis) to predefined names. Suppose name of 40 persons. x axis should be time. How you achieved this? Could you please help? Also want vertical scrolling till the last item reached. How can i use that ?
