### ISSUE TITLE
Can I implement the view in the attachment based on this library? 

### ISSUE THREAD

**Issue by WenEthan** [alamkanak/Android-Week-View#548]
<img width="1192" alt="Screen Shot 2019-05-24 at 10 16 57 AM" src="https://user-images.githubusercontent.com/6867780/58298347-b5b93800-7e0d-11e9-8cb4-5621822e99a7.png">

**Comment by edablogs** [comment]
did you find any solution to make this view?
i m also looking for same solution.

**Comment by cnbscience** [comment]
I think it's pretty straigh forward and , I have modified these lines in goToNearestOrigin(), I have experimented it with 3. days I am sure you can make it as a parameter.
 
double leftDays = mCurrentOrigin.x / ((mWidthPerDay*(No_of_days_you_want_to_move) + mColumnGap);

int nearestOrigin = (int) (mCurrentOrigin.x - leftDays * ((mWidthPerDay*(No_of_days_you_want_to_move)) + mColumnGap));

mScroller.startScroll((int) mCurrentOrigin.x, (int) mCurrentOrigin.y, -nearestOrigin, 0, (int) (Math.abs(nearestOrigin) / (mWidthPerDay*(No_of_days_you_want_to_move)) * mScrollDuration));

**Comment by cnbscience** [comment]
Never mind, the above answer is not for this question, sorry for that

**Comment by alamkanak** [comment]
Unfortunately, you cannot produce the attached design with the current library. But you can modify the library source code to achieve that design.
