### ISSUE TITLE
How to change some events background color

### ISSUE THREAD

**Issue by kingnightdrifter** [alamkanak/Android-Week-View#552]
Hi community,

Can you please help me how to change a specific event background color. Actually the event which have been cancelled i want to show then with differnt color. 

Thanks in advance.

**Comment by kingnightdrifter** [comment]
Hi,
I have solved it, please let me know if anyone need helo i ll send code snippt

**Comment by SamarthSevak** [comment]
Please send thanks.

**Comment by alamkanak** [comment]
Since you solved it I will close the issue
