### ISSUE TITLE
Split onMonthChange() in 2 methods: 1) only onMonthChange listener 2) only events manager

### ISSUE THREAD

**Issue by KimPark89** [alamkanak/Android-Week-View#57]
Is it possible to split onMonthChange() method in 2 separate methods? One that works like a simple onMonthChange() listener and it doesn't do anything else (it doesn't manage the events) and another one that manages only the creation of the events. Actually onMonthChange() makes both of these tasks and I can't call this method by myself to do some stuff without creating the events again, nor I can't create the events if I don't call it.

I try to explain better with an example. When onMonthChange() is called, I need to start an asyncTask inside it to get the events those comply with some parameters (nextMonth and nextYear) downloading them from a server. But when asyncTask returns the results (the events) the onMonthChange() has just finished his job and returned no events (because the asyncTask dind't return the events yet).

**Comment by caske33** [comment]
See [this comment](https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158)

Basically, the first time onMonthChange is called, you call your asyncTask. 
When that's completed you save your events somewhere in your activity/fragment/... (somewhere where you can access them synchronously). 
After saving the events you call `mWeekView.notifyDatasetChanged();`
This will trigger another round of onMonthChange() events. Now you have the data, so you can provide it in your return argument.

Notes: you should cache whether you're already loading the events for a specific month too. When the weekview is created, the previous, the current and next month will be loaded (in that order). 
So when you call `mWeekView.notifyDatasetChanged();` on the completion of the first request, the other 2 might not have finished and will be called again. (Basically, if you don't have this check, the current month will be loaded twice and the next month 3 times).

I suggest this issue to be left open as a reminder that we should update the readme with this explanation or at least a link to a wiki with a page of extra information for async loading.

**Comment by KimPark89** [comment]
Thank you, it works. And I agree with you for updating the readme. I think this is a pretty common problem.
