### ISSUE TITLE
Set optional range for events prefetch instead of 3 months

### ISSUE THREAD

**Issue by fourier** [alamkanak/Android-Week-View#58]
For the applications where the main view is a day view the week prefetch is enough. 3 months is too big range for this kind of applications and reduce the application responsiveness for on the activity launch. We need to have a way to configure prefetch range.

**Comment by caske33** [comment]
Although possible, this will require rewriting a large part of the library. 

I suggest however that this change be as much backwards compable as possible. (Easy transition should be possible)

Here are some points that need to be solved.

1. onMonthChangeListener should be replaced with a more general onLoad (what will/should the arguments be?), this should probably be part of a new "WeekViewLoader" interface
2. When will the next onLoad event take place? (now it's when at the 15th day of the month, I believe). #50 might be useful here, although I think it should be part of the new WeekViewLoader interface
3. A way to express the unit period of prefetching (e.g. a month in the current implementation), also part of the WeekViewLoader interface


My answers to those questions would be
```java
public interface WeekViewLoader{
    public double toWeekViewUnitPeriodIndex(Calendar instance);
    public List<WeekViewEvent> onLoad(int periodIndex);
}
```
The `toWeekViewUnitPeriodIndex(Calendar instance)` would convert a Calendar instance to a double giving information about the index for the onLoad event + information about progress to the next unit (for point 2.). So if you round this number, you get the index passed to onLoad. If the fraction part of this double is larger than 0.5, than a new "month" should be loaded. This way the weekview is also completly decoupled from what the real unit is of prefetching. 
Of course this interface is rahter abstract, so the library could come with some implemented classes (like below for the onMonthChangeListener), each with their own unit of time and a new more intuitive interface.

For backwards compability, this could be solved with (pseudo-code)
```java
public class MonthLoader implements WeekViewLoader{
    private OnMonthChangeListener mOnMonthChangeListener;
    public MonthLoader(OnMonthChangeListener listener){
        this.mOnMonthChangeListener = listener
    }
    public double toWeekViewUnitPeriodIndex(Calendar instance){
        return instance.get(Calendar.YEAR)*12+instance.get(Calendar.MONTH)+instance.get(Calendar.DAY_OF_MONTH)/30;
    }
    public List<WeekViewEvent> onLoad(int periodIndex){
        mOnMonthChangeListener.onMonthChange(periodIndex/12,periodIndex%12);
    }
}
```

**Comment by caske33** [comment]
@fourier This is now possible since 1.2.4
