### ISSUE TITLE
Create event on Particular Date

### ISSUE THREAD

**Issue by swanandvaidya** [alamkanak/Android-Week-View#61]
Can we create an event on a particular date?
Any help would be appreciated.
Thanks in advance.

**Comment by caske33** [comment]
I would take a look in the sample app and adjust that to your needs.
https://github.com/alamkanak/Android-Week-View/blob/master/sample/src/main/java/com/alamkanak/weekview/sample/MainActivity.java#L112-L122

**Comment by swanandvaidya** [comment]
Thank you, but this is hard coded event and i don't want to do that.

**Comment by swanandvaidya** [comment]
I have created my own event and i want to display those events on a particular date is it possible?
Thanks.

**Comment by KimPark89** [comment]
Calendar startTime = Calendar.getInstance();
startTime.setTime(myEvent.getData());
startTime.set(Calendar.HOUR_OF_DAY, myEvent.getStartHour());
startTime.set(Calendar.MINUTE, myEvent.getStartMinute());

Calendar endTime = (Calendar) startTime.clone();
endTime.set(Calendar.HOUR_OF_DAY, myEvent.getEndHour());
endTime.set(Calendar.MINUTE, myEvent.getEndMinute());

WeekViewEvent event = new WeekViewEvent(index, getEventTitle(myEvent.getTitle()), startTime, endTime);
event.setColor(myEvent.getColor());

events.add(event);

**Comment by fourier** [comment]
I would like to extend this question: how to insert a new event and refresh a view without reloading full 3 months?

**Comment by KimPark89** [comment]
good question
@caske33

**Comment by caske33** [comment]
save the months in your activity/fragment and call weekview.notifydatasetchanged(). The weekview will request the months again, but now that you've got them saved you can just return the "cached" versions.

I explained it in more detail in this comment: https://github.com/alamkanak/Android-Week-View/issues/57#issuecomment-70665204

**Comment by fourier** [comment]
The problem for me is what the class responsible for async loading of events will have no idea if the onMonthChange called for real (so we need to initiate the async request) or just to reload the current day with the new event added(the event may arrive through the different source, like push-notification). Of course I can add state variables but this will make code unnecessary more complicated and error-prone (it is already, since the async nature of dowloading events). Maybe it should be an easier way to insert an event and update the current view?

**Comment by caske33** [comment]
So basically you want the library to do what I described earlier (instead of the apps using the library)?

In that case, my proposal for #58 should probably be extended to support both sync and async ways of returning the events.

**Comment by fourier** [comment]
Yes, sort of. Basically there should be more customizable ways to deliver events into the library, not only the OnMonthChangeListener. This one obviously not flexible enough.

**Comment by alamkanak** [comment]
Closing this because the events *can* be created on a particular date.

**Comment by tkosev** [comment]
hello guys I am using this library at work and I would like to ask if we can remove the titlebar in the one day view where it shows something like w 10/2 
Kind regards and Thank you

**Comment by anilthummar** [comment]
> on a particular date.

hii getting lang issues in this calendar 
Pls check below image.



![dateissues](https://user-images.githubusercontent.com/7361686/49226188-e47cc580-f40b-11e8-918b-48a6f7427a43.png)
