### ISSUE TITLE
How can I do to load 4 months of events?

### ISSUE THREAD

**Issue by josefrvaldes** [alamkanak/Android-Week-View#62]
Hello, first of all thank you for this library, it's amazing! but I have a few questions:

I have loaded events of every month of the year. I know that your library only allow you tu load 3 months at a time. But if I'm showing December, January and February, how can I do to show January, February and March when you scroll forward?

This is my code and it doesn't work:

public List<WeekViewEvent> onMonthChange(int newYear, int newMonth)
    {
        // Populate the week view with some events.
        List<WeekViewEvent> events = new ArrayList<>();

        for(Cita c : citas)
        {
            Calendar startTime = c.getFecha();

            Log.d("DEBUG: ","onMonthChanged: newMonth = "+newMonth+", startTime.MONTH = "+String.valueOf(startTime.MONTH));
            if(newMonth == startTime.MONTH)
            {
                Calendar endTime = (Calendar) startTime.clone();
                endTime.add(Calendar.MINUTE, c.getIntervalo());
                WeekViewEvent event = new WeekViewEvent(1, getEventTitle(c), startTime, endTime);
                switch(c.getIdEstado())
                {
                    case 0:event.setColor(getResources().getColor(R.color.event_color_01));break;
                    case 1:event.setColor(getResources().getColor(R.color.event_color_02));break;
                    case 3:event.setColor(getResources().getColor(R.color.event_color_03));break;
                    case 5:event.setColor(getResources().getColor(R.color.event_color_04));break;
                    case 8:event.setColor(getResources().getColor(R.color.event_color_05));break;
                    default:event.setColor(getResources().getColor(R.color.event_color_01));break;
                }
                events.add(event);
            }
        }
        return events;
    }

List of citas is loaded with events for the whole year, but if I scroll to march, no event is shown.

**Comment by caske33** [comment]
newMonth uses a 1-based API (so 1 means January), while Calendar uses a 0-based API. 

Does that solve your problem?

**Comment by josefrvaldes** [comment]
I don't think so, but I'll it check anyway.
I don't think so because I've already checked that if one event is in february in my database, it is shown in february in my app, so I think it is not the problem.

**Comment by josefrvaldes** [comment]
Thank you very much caske33, you were right, it was that problem. I thought I was doing it right but as Calendar is a bit tricky, it was a mistake that I hadn't noticed.

**Comment by caske33** [comment]
@josefrvaldes can you close the issue then? (I don't have the rights and the main collaborator is currently a bit inactive)
