### ISSUE TITLE
L/R Swipe doesn't work with Android-Week-View as Fragment in iosched SlidingTab

### ISSUE THREAD

**Issue by R0ns3n** [alamkanak/Android-Week-View#63]
Hi,

I implement your framwork as a Fragment in iosched SlidingTabLayout. In this szenario the left-right swipe doesn't work correct. If I swipe to fast the SlidingTab will swipe. I only can swipe the Week-View if I swipe on the View a few millimeters. Is there any workaround to get the Swipe work again or can you fix this issue?

Best Regards
R0ns3n

**Comment by caske33** [comment]
@R0ns3n What if you change the `xScrollingSpeed` property of the weekView to a value higher than 1.0? 

If you set it to 2.0, it should scroll double as fast as normal.

**Comment by alamkanak** [comment]
Its a really bad practice to use a scrollabe view inside another scrollable view. Then android does not know which view to scroll when you swipe. I'd recommend you not to use week view inside a scrollable since it already supports scroll.

**Comment by Morgan2cc** [comment]
Isn't it easy to add a tag to the xml definition so that the weekview ignores all onTouch events? 
It doesn't seem like bad practice that we want to use the beauty of the design in a static (non horizontally scrollable) way. Ugh.
