### ISSUE TITLE
Issue when event duration more than 2 days

### ISSUE THREAD

**Issue by thelittlefireman** [alamkanak/Android-Week-View#75]
When a event takes more than 2 days it's not show correctly please fix with this : 

private void cacheEvent(WeekViewEvent event) {

		if (!isSameDay(event.getStartTime(), event.getEndTime())) {

			int numDayInEvent = daysBetween(event.getStartTime(), event.getEndTime());
			// for startTime+1 ==> numDayInEvent -1
			Log.v(this.getClass().getName(), "cacheEvent + numDayInEvents" + numDayInEvent);
			for (int indexDay = 0; indexDay <= numDayInEvent; indexDay++) {
				Calendar endTime = (Calendar) event.getStartTime().clone();
				endTime.set(Calendar.DAY_OF_YEAR, event.getStartTime().get(Calendar.DAY_OF_YEAR) + indexDay);
				endTime.set(Calendar.HOUR_OF_DAY, 23);
				endTime.set(Calendar.MINUTE, 59);
				Calendar startTime = (Calendar) event.getStartTime().clone();
				startTime.set(Calendar.DAY_OF_YEAR, event.getStartTime().get(Calendar.DAY_OF_YEAR) + indexDay);
				startTime.set(Calendar.HOUR_OF_DAY, 0);
				startTime.set(Calendar.MINUTE, 0);
				if (indexDay == numDayInEvent) {

					WeekViewEvent eventEnd = new WeekViewEvent(event.getmCalendarID(), event.getId(),
							event.getAccountType(), event.getAccountName(), event.getName(), event.getmDescription(),
							event.getmLocalication(), startTime, event.getEndTime(), event.isAllDay(),
							event.isCanBeModify());
					eventEnd.setColor(event.getColor());
					mEventRects.add(new EventRect(eventEnd, event, null));
				}

				else if (indexDay == 0) {
					WeekViewEvent eventStart = new WeekViewEvent(event.getmCalendarID(), event.getId(),
							event.getAccountType(), event.getAccountName(), event.getName(), event.getmDescription(),
							event.getmLocalication(), event.getStartTime(), endTime, event.isAllDay(),
							event.isCanBeModify());
					eventStart.setColor(event.getColor());
					mEventRects.add(new EventRect(eventStart, event, null));
				}
				else {

					WeekViewEvent eventMiddle = new WeekViewEvent(event.getmCalendarID(), event.getId(),
							event.getAccountType(), event.getAccountName(), event.getName(), event.getmDescription(),
							event.getmLocalication(), startTime, endTime, event.isAllDay(), event.isCanBeModify());
					eventMiddle.setColor(event.getColor());
					mEventRects.add(new EventRect(eventMiddle, event, null));
				}
			}
		}

		else
			mEventRects.add(new EventRect(event, event, null));
	}

	public static int  daysBetween(Calendar startDate, Calendar endDate) {
		long end = endDate.getTimeInMillis();
		long start = startDate.getTimeInMillis();
		return (int) Math.ceil(((float) ((float)Math.abs(end - start)/(float) (24*60*60*1000))));
	}

**Comment by aiwiguna** [comment]
when will you update to fix this bug?

**Comment by caske33** [comment]
This should be fixed in 1.2.4
