### ISSUE TITLE
goToDate()

### ISSUE THREAD

**Issue by AleBestia** [alamkanak/Android-Week-View#76]
The method goToDate(Calendar date) doesn't work, and, as a result, also the method goToToday().

**Comment by caske33** [comment]
Are you calling it during onCreate() or something like that? Because that will be fixed by #69

**Comment by AleBestia** [comment]
Yes, I tried to call it during onCreate() and also during onStart();
Oh, ok, I'll wait thank you.

2015-02-11 9:35 GMT+01:00 Jens Claes <notifications@github.com>:

**Comment by AleBestia** [comment]
I've temporarily fixed my problem on this way:

2015-02-11 22:25 GMT+01:00 Alessandro Muzzi <alessandromuzzi17@gmail.com>:

**Comment by maxwolffe** [comment]
I'm having trouble with this too. I think it may be from line 1362 in WeekView.java. I think the x displacement calculated from the date difference may be the problem? I'm able to get the displacement that I want by passing in a date a year and a bit in the future. Also! Great library.

**Comment by AleBestia** [comment]
At this moment I don't know what's write at line 1362 but, if I understood
how this view works, I think that when the goToDate() method is called from
OnCreate(), the layout hasn't been shown, so..when the library tries to get
the width of a single day column, the result is 0 and so it make 0 the
offset.
Il 15/feb/2015 18:46 "Max Wolffe" <notifications@github.com> ha scritto:

**Comment by caske33** [comment]
All problems with goToDate() should be fixed, but it's just waiting for @alamkanak to get better and be able to test them and merge them in.

**Comment by alamkanak** [comment]
Problem fixed. See #69
