### ISSUE TITLE
Long Event + small event doesn't show correctly

### ISSUE THREAD

**Issue by thelittlefireman** [alamkanak/Android-Week-View#78]
Hi,
I just find an issue : 
When you put a long event wich take a big part of the day and after you have small events, they disapear, or maybe they are placed under the large bar : 

Just look by yourself : 
Before : 
![before](https://cloud.githubusercontent.com/assets/5165783/6229284/5047214e-b6b6-11e4-9d14-f4962362b18a.jpg)

After : 
![after](https://cloud.githubusercontent.com/assets/5165783/6229285/5808c680-b6b6-11e4-95be-b6fb6748b983.jpg)

That's verry embarrassing =/ please fix it quickly

**Comment by thelittlefireman** [comment]
i find where the issue is : 

int maxRowCount = columns.get(0).size();
		for (int i = 0; i < maxRowCount; i++) {
			// Set the left and right values of the event.
			float j = 0;
			for (List<EventRect> column : columns) {
				if (column.size() >= i + 1) {
					EventRect eventRect = column.get(i);
					eventRect.width = 1f / columns.size();
					eventRect.left = j / columns.size();
					eventRect.top = eventRect.event.getStartTime().get(Calendar.HOUR_OF_DAY) * 60
							+ eventRect.event.getStartTime().get(Calendar.MINUTE);
					eventRect.bottom = eventRect.event.getEndTime().get(Calendar.HOUR_OF_DAY) * 60
							+ eventRect.event.getEndTime().get(Calendar.MINUTE);
					mEventRects.add(eventRect);
				}
				j++;
			}
		}

The loop doesn't get all the events of the "Columns"

**Comment by thelittlefireman** [comment]
And This is the solution : please add it quickly
/**/
//


private void expandEventsToMaxWidth(List<EventRect> collisionGroup) {

		// Expand the events to maximum possible width.

		List<List<EventRect>> columns = new ArrayList<List<EventRect>>();
		columns.add(new ArrayList<EventRect>());

		for (EventRect eventRect : collisionGroup) {
			boolean isPlaced = false;

			for (List<EventRect> column : columns) {

				if (column.size() == 0) {
					column.add(eventRect);
					isPlaced = true;

				}

				else if (!isEventsCollide(eventRect.event, column.get(column.size() - 1).event)) {
					column.add(eventRect);
					isPlaced = true;
					break;

				}
			}

			if (!isPlaced) {
				List<EventRect> newColumn = new ArrayList<EventRect>();
				newColumn.add(eventRect);
				columns.add(newColumn);

			}

		}

		/*// Calculate left and right position for all the events.
		int maxRowCount = columns.size();
        //int maxRowCount = columns.get(0).size();
		for (int i = 0; i < maxRowCount; i++) {
			// Set the left and right values of the event.
			float j = 0;
			for (List<EventRect> column : columns) {
				if (column.size() >= i + 1) {
					EventRect eventRect = column.get(i);
					eventRect.width = 1f / columns.size();
					eventRect.left = j / columns.size();
					eventRect.top = eventRect.event.getStartTime().get(Calendar.HOUR_OF_DAY) * 60
							+ eventRect.event.getStartTime().get(Calendar.MINUTE);
					eventRect.bottom = eventRect.event.getEndTime().get(Calendar.HOUR_OF_DAY) * 60
							+ eventRect.event.getEndTime().get(Calendar.MINUTE);
					mEventRects.add(eventRect);
				}
				j++;
			}
		}*/
        //il vont avoir le même left and width
        float j = 0;
        //pour chaque colones qu'il y a
        for(List<EventRect> column : columns){
            //pour chaque eventRect de la colone

            for(EventRect eRect : column){
                EventRect eventRect = eRect;
                eventRect.width = 1f / columns.size();
                eventRect.left = j / columns.size();
                eventRect.top = eventRect.event.getStartTime().get(Calendar.HOUR_OF_DAY) * 60
                        + eventRect.event.getStartTime().get(Calendar.MINUTE);
                eventRect.bottom = eventRect.event.getEndTime().get(Calendar.HOUR_OF_DAY) * 60
                        + eventRect.event.getEndTime().get(Calendar.MINUTE);
                mEventRects.add(eventRect);
            }
            j++;



        }
	}

**Comment by caske33** [comment]
I'm going to close this, but @thelittlefireman if this is still a problem in 1.2.5, then please reopen this issue.
