### ISSUE TITLE
Zoom on weekView

### ISSUE THREAD

**Issue by sylvaindd** [alamkanak/Android-Week-View#8]
Hi,

I'd like to know if there is a way to zoom/pinch on a week view ?
And is it possible to display only days from Monday to Friday ?

Thank you

**Comment by caske33** [comment]
I've been working on implementing this. Just some slight problems left, but expect a PR soon.

**Comment by sylvaindd** [comment]
HI,
That would be very nice. I kinda upgraded my implementation but it's still not smooth.
Anyway, if you could keep me informed about your implementation, that would be nice.

**Comment by caske33** [comment]
I got it working so it follows the current position in the view. 

The two problems I currently still have is that 
- [ ] it sometimes still starts scrolling while zooming (especially annoying when it comes to horizontal scrolling)
- [ ] there should be a dynamic minium hourHeight (that depends on the screenHeight, otherwise the view is sometimes smaller than the available height).

(You'll be able to set the min and max hourHeight manually too btw)

**Comment by sylvaindd** [comment]
I actually managed to resolve this problem : 
"otherwise the view is sometimes smaller than the available height"
If you used a ScaleGestureDetector  did you return true in onScale and onScaleBegin ?
I had a problem with the scroll and zoom not working correctly together by returning false.

**Comment by caske33** [comment]
I do return true, but I'm not sure what I should do in the onTouch handler. Right now I do
`return mScaleDetector.onTouchEvent(event) && mGestureDetector.onTouchEvent(event);`
instead of
`return mGestureDetector.onTouchEvent(event);`

**Comment by sylvaindd** [comment]
I currently do this : 
	mScaleDetector.onTouchEvent(event);
	return mGestureDetector.onTouchEvent(event);
Which I guess is pretty much the same as what you're doing

**Comment by caske33** [comment]
I think your implementation is even better. (in case the first one ever returns false)

**Comment by caske33** [comment]
I have a commit ready, but it's kinda based on some other PR's that I've open. So I'll make a PR whenever I've got a better base to make a clean PR.

You can see the commit 6621e8365436fb4c7833fc812d83c1b21a5f674b on the [Quivr-fork](https://github.com/Quivr/Android-Week-View)

**Comment by sylvaindd** [comment]
Thanks, but I'll wait the clean PR, I can't make it work right now.

**Comment by obaslan** [comment]
Does the last commit really keep the center when zoomed in? Topmost hour remains the same for me not the center.

**Comment by caske33** [comment]
It keeps indeed the top hour not the center. 

I think people usually look somewhere on the top of their screen. (about 1/4 from the top). But there's no real data about this, so I went with the easiest option to program (and to maintain!)

**Comment by obaslan** [comment]
@caske33 Do you know an easy way of reading the positions of the 2-touch coordinates and keeping the position of that hour fixed? I know the getTimeFromPoint method exists but how to make use of it here? Besides goToHour only sets the top hour.

**Comment by caske33** [comment]
No, not at all. 

As I said, I went with the easy option and the one that didn't require a lot of the pixel-fiddling.

**Comment by obaslan** [comment]
I see. Well I hope someone does it one day. Thank you for your contribution regarding the vertical zoom.

**Comment by obaslan** [comment]
@caske33 Is it possible to limit the HourHeight zoom to vertical zoom only. I would like to perform a horizontal zoom to change the numberOfVisibleDays?

**Comment by caske33** [comment]
Normally it should be only a vertical zoom?

**Comment by obaslan** [comment]
@caske33 I used your commit https://github.com/alamkanak/Android-Week-View/commit/6621e8365436fb4c7833fc812d83c1b21a5f674b but it works when doing horizontal finger zoom.

**Comment by caske33** [comment]
I'm not really sure how to change that :disappointed:. But feel free to do it yourself.

**Comment by sylvaindd** [comment]
Hi there,

There has been a while since I opened this post :o.
I needed the weekview for a new Android project and decided to fork it (with @thelittlefireman) and change it to fit what we needed in order to make it easier to use for our projects.

I gave a look at the zoom I wrote before, and actually managed to make it way better.

What has been changed :
-Disable scrolling while zooming
-Zoom centers where you started the zoom
-It can't no longer make display issues where we could have a blank space before 00AM or 12PM.

It's working just fine for me, I've not tested it a lot tho but it should be ok.

Here is the fork : https://github.com/thelittlefireman/Esirdreamteam-Android-Week-View

If you want to take a look, it's basically only the OnScaleGestureListenerWeekView class that is needed for the zoom.

@obaslan It should do what you wanted :). I'll also try the horizontal zoom to change the number of days visible.

**Comment by marunjar** [comment]
@sylvaindd is there any chance that you create pull requests for some of your changes?

i think disabling scrolling while zooming should already be done via mIsZooming
but centering zoom at the starting point would be a cool feature 
and if there are display issues that can be fixed i think we should also fix them in this lib

**Comment by sylvaindd** [comment]
@marunjar, it seems like @alamkanak released these features yesterday. I didn't try it, but it looks like it has the same behavior as mine.

**Comment by obaslan** [comment]
@sylvaindd Thanks for this contribution.
