### ISSUE TITLE
Non-colliding events splitting

### ISSUE THREAD

**Issue by VarunBarad** [alamkanak/Android-Week-View#80]
Hello,
I have this weird problem where sometimes even though times of two different events are not colliding, they are still not taking the entire space and splitting(like in the screenshot below).
![screenshot_2015-02-21-22-07-01](https://cloud.githubusercontent.com/assets/8678857/6314920/a5cc8a7e-ba16-11e4-83b2-b27bc87c42ba.png)

Although on different day where I have events with exact same timings show nicely without any hitches.
![screenshot_2015-02-21-22-07-51](https://cloud.githubusercontent.com/assets/8678857/6314928/21bb0bb0-ba17-11e4-8e01-d92f897f7a10.png)

As we have already used this plugin in our production application. We would really appreciate help on this.

To see the problem for yourself, below is the link to our application and demo credentials:

Application: [https://play.google.com/store/apps/details?id=com.crawded.android](https://play.google.com/store/apps/details?id=com.crawded.android)

User ID: johnsmith@crawded.com
Password: student12345

The problem is visible in events from 07:00 to 13:00 on 2015-02-10
The problem is visible in classes from

**Comment by caske33** [comment]
Is it possible to get the startdates and enddates of all the events you listed above?

**Comment by VarunBarad** [comment]
Which format would you prefer?

**Comment by caske33** [comment]
preferably with milliseconds information.

**Comment by alamkanak** [comment]
I think, if you set the second and millisecond property of the start time and end time of your events to zero, the problem will be solved. Let us know if it does not work.

**Comment by VarunBarad** [comment]
Thanks
Setting the millisecond property solved it
