### ISSUE TITLE
WeekViewEvent ID

### ISSUE THREAD

**Issue by oleomachado** [alamkanak/Android-Week-View#82]
Hi, I think that would be nice if you allow the "id" parameter of WeekViewEvent to be of another type  beside "long". Maybe accept an Object?
In my project the event id (in database) is an Guid in String format. I just changed to Object which allow me to send a String or another class with even more information.

**Comment by alamkanak** [comment]
If you want to store some custom fields with each event then create a new class extending the `WeekViewEvent`, adding your custom fields. Then use that class instead.

```java
public class CustomWeekViewEvent extends WeekViewEvent {
	private String stringId;

	public CustomWeekViewEvent() {
	}

	public CustomWeekViewEvent(long id, String name, int startYear, int startMonth, int startDay, int startHour, int startMinute, int endYear, int endMonth, int endDay, int endHour, int endMinute) {
		super(id, name, startYear, startMonth, startDay, startHour, startMinute, endYear, endMonth, endDay, endHour, endMinute);
	}

	public CustomWeekViewEvent(long id, String name, Calendar startTime, Calendar endTime) {
		super(id, name, startTime, endTime);
	}

	public String getStringId() {
		return stringId;
	}

	public void setStringId(String stringId) {
		this.stringId = stringId;
	}
}
```
