### ISSUE TITLE
i custommized this weekview according to my need

### ISSUE THREAD

**Issue by lak27** [alamkanak/Android-Week-View#84]
PLEASE HELP 
in WEEKVIEW it has timing of one hour gap
I customized it to be of 15 mins but i m not able to render my events accordingly
the top value is still being calculated according to per hour view

My time on the left side begins from 9:30 in the morning and goes on as 9:45,10:00,10:15 upto 7:30 pm

**Comment by caske33** [comment]
Is this still a problem @lak27 ? I'm going to close this until further notice.
