### ISSUE TITLE
Adding events dynamically?

### ISSUE THREAD

**Issue by kdeez** [alamkanak/Android-Week-View#87]
Sorry to ask this question again, but I was having trouble adding events dynamically. I tried to understand the issue by looking through the sample application but it had seemed to be hard coded into the application. How am I able to add events from user input? If anyone who has this figured out, I was hoping you could give me a little bit of guidance on this problem.

**Comment by rachitmishra** [comment]
Hi,

1. Declare ArrayList<WeekViewEvent> mEvents.

2. Initialise it in onCreate() of your activity.
    mEvents = new ArrayList<WeekViewEvent>();

3. mWeekView.setMonthChangeListener(new WeekView.MonthChangeListener() {
            @Override
            public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
                return getEvents(newYear, newMonth); // filter event list by month & year
            }
        });

4. On user input create new WeekViewEvent weekEvent = new WeekViewEvent();
     // set your event values
    mEvents.clear();
    mEvents.add(weekEvent); // you can have a number of events inside a loop or cursor loader
    mWeekView.notifyDatasetChanged();

~ thanks

**Comment by kdeez** [comment]
Thank you for the help! I think I almost got it. Just one little question, is there a method defined as "getEvents"? or is that user defined?

**Comment by rachitmishra** [comment]
getEvents is your user defined method, in which you process your events in the master list (i.e. events), and return a list of just those which fall in month & year, you got from the monthChangeListner. 

Example

```private List<WeekViewEvent> getEventsForMonth(int year, int month) {
        List<WeekViewEvent> tempList = new ArrayList<WeekViewEvent>();
        for (WeekViewEvent weekViewEvent : events) {
            if (weekViewEvent.mStartTime.get(Calendar.MONTH) == month && weekViewEvent.mStartTime.get(Calendar.YEAR) ==
                    year) {
                tempList.add(weekViewEvent);
            }
        }

        return tempList;
    }```
