### ISSUE TITLE
WeekViewEvent.mId isn't used anywhere

### ISSUE THREAD

**Issue by dgrant** [alamkanak/Android-Week-View#88]
The id isn't used anywhere. Can it be gotten rid of?

**Comment by rachitmishra** [comment]
It depends how you want to use, say that an event with some server id or database local id.

**Comment by dgrant** [comment]
Ah, ok I didn't realize the WeekViewEvent is passed on some listeners (like clicklistener). I'm not currently implementing any of these listeners.

**Comment by dgrant** [comment]
Sorry I meant to close this... Sorry for wasting everyone's time with this one.

**Comment by rachitmishra** [comment]
@dgrant it's okay!
