### ISSUE TITLE
Set number of hours to display

### ISSUE THREAD

**Issue by EmanueleHB** [alamkanak/Android-Week-View#89]
A method to set a numberOfVisibleHours would be really useful.

**Comment by caske33** [comment]
See also #8 and my branch https://github.com/Quivr/Android-Week-View/commits/iss8-vertical-zooming which needs other PR's to be merged, before I can make a PR, because it currently depends too much on code from other PR's.

**Comment by hellchoseme** [comment]
Nice. I'm trying to implement it right now, but I'm stuck on a point. Do you now how could I get the height of the area where the events are drawn?

**Comment by caske33** [comment]
I'm guessing `getHeight() - mHourHeight * 24 - mHeaderTextHeight - mHeaderRowPadding * 2 - mHeaderMarginBottom` will give you that code. (it's the height of the screen minus all the other stuff, that isn't part of the hour-ranges).

**Comment by EmanueleHB** [comment]
Can't do that, I'm trying to set mHourHeight from inside the view with something like

'''java
mHourHeight = mAreaHeight/mNumberOfHours
'''

**Comment by caske33** [comment]
Oops, I meant`getAreaHeight() == getHeight() - mHeaderTextHeight - mHeaderRowPadding * 2 - mHeaderMarginBottom`

**Comment by EmanueleHB** [comment]
Great, i got it working. One last thing, how can I cache a value set in Acitivty's onCreate and use it when the weekView is drawn?

**Comment by caske33** [comment]
See the usage of mScrollToHour in 8b92d78

**Comment by caske33** [comment]
Closing in favor of #42.
