### ISSUE TITLE
drag events to new date time

### ISSUE THREAD

**Issue by saldisobi** [alamkanak/Android-Week-View#9]

**Comment by wiaamLB** [comment]
Hello
Did you implement that feature ?

**Comment by saldisobi** [comment]
yup, I did that

**Comment by wiaamLB** [comment]
can i get the  methode?

**Comment by furqankhwaja** [comment]
Can you show the code on how to drag and drop events? @saldisobi

**Comment by ashishparmar** [comment]
@saldisobi : hello can you please share your drag code ..?

**Comment by nivritgupta** [comment]
@furqankhwaja  did you find any solution or alternative calendar

**Comment by vajjasivateja** [comment]
@saldisobi can you please help to implement the drag and drop feature?
