### ISSUE TITLE
constructor with custom date

### ISSUE THREAD

**Issue by KimPark89** [alamkanak/Android-Week-View#90]
Hi, 
currently when WeekView is instantiated it starts always with the today date, I think it can be usefull have a constructor where put a custom date. So when I switch my device from port to land (and viceversa) i can instantiate WeekView with the current date that i was displaying, instead of today date.

**Comment by caske33** [comment]
mWeekView.goToDate(customDate);

**Comment by KimPark89** [comment]
Yes I know, I tried "mWeekView.goToDate(customDate)" but after the switch the calendar shows the today date again but slightly shifted, like it tried to scroll to the custom date but it didn't work.

**Comment by caske33** [comment]
@alamkanak still has to release the commit with the fix I guess...

**Comment by KimPark89** [comment]
I want to try to manually apply the changes, waiting for Alamkanak to release the changes. I downloaded the project zip, now what do I need to do? Do I need to open the project or import it (as project, module, sample)?

**Comment by caske33** [comment]
I'm assuming you're working with gradle.

you need to put it as a gradle module (next to your app folder)
And in your settings.gradle (root folder) add ':weekview:library'
And in your app/build.gradle you should add `compile project(':weekview:library')`

**Comment by KimPark89** [comment]
Thank you,
I also removed this line from weekview/build.gradle, then it worked: 
*apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'*

**Comment by githubdoramon** [comment]
@caske33 and @alamkanak, any news on releasing the version with the goToDate fix?

**Comment by caske33** [comment]
I'm not sure if @alamkanak has published a new version since, but the commit was merged so it probably should work.

**Comment by githubdoramon** [comment]
I have just downloaded the source and after a few fights with Android Studio got it working.... Thanks @caske33
