### ISSUE TITLE
Dynamically add / update events

### ISSUE THREAD

**Issue by piotrwojtowicz** [alamkanak/Android-Week-View#91]
Hello guys, 

First of all, great library, it saved me a lot of time. Keep up good work guys. 

When using it I got two questions: 

1. Is there a possibility to add WeekViewEvents in other way than in onMonthChange?

In my scenario when activity with WeekView appears, WeekView is calling three times onMonthChange (by library design), in that function I have asynchronous call to my REST web service to get data for provided newYear and newMonth. So I will have that data some time later (for sure after onMonthChange will be already finished), how can I add this data later to WeekView and notify it about changes (notifyDatasetChanged)?

2. How can I access data in WeekView to modify some event (basing on it's Id) and refresh WeekView?

In my scenario user taps on event, make some changes to start / end time and saves changes which should be sent to web service and later (if success) this changes should be updated in calendar. 

any help or tips would be appreciated :)
Piotr

**Comment by piotrwojtowicz** [comment]
I see that there are some tips on forum how to do it. I will try them.

**Comment by eiclu** [comment]
How did you resolve this?

**Comment by entropitor** [comment]
@LookitheFirst You can check the sample app in this repository
